import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { CollaborationBridge, CollaborationMessageService } from "../src/collaboration-bridge.js";
import { collaborationPlanDigest, type AgentAssignment, type Collaboration, type CollaborationPlanSnapshot } from "../src/collaboration.js";
import { Workspace } from "../src/storage.js";

const compiledCli = resolve(process.cwd(), "dist/src/agent-collaboration-cli.js");
const now = "2026-08-21T00:00:00.000Z";
async function run(args: string[], env: NodeJS.ProcessEnv): Promise<{ status: number | null; stdout: string; stderr: string }> { return await new Promise((accept, reject) => { const child = spawn(process.execPath, [compiledCli, ...args], { env: { ...process.env, ...env }, stdio: ["ignore", "pipe", "pipe"] }); let stdout = ""; let stderr = ""; child.stdout.setEncoding("utf8"); child.stderr.setEncoding("utf8"); child.stdout.on("data", (part: string) => { stdout += part; }); child.stderr.on("data", (part: string) => { stderr += part; }); child.on("error", reject); child.on("close", (status) => accept({ status, stdout, stderr })); }); }

function fixture(t: test.TestContext) {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-agent-cli-")); t.after(() => rmSync(root, { recursive: true, force: true })); const storage = new Workspace(resolve(root, ".cjhx"));
  const collaboration: Collaboration = { schemaVersion: 1, id: "collaboration-1", workspaceId: "workspace-1", changeId: "CHANGE-1", taskId: "task-1", title: "CLI", objective: "Coordinate", status: "running", limits: { maxAssignments: 4, maxDepth: 1, maxParallel: 2, maxMessages: 10, timeoutMinutes: 60 }, usage: { assignments: 2, runningAssignments: 2, messages: 0, tokens: 0 }, createdBy: "owner", createdAt: now, updatedAt: now };
  const assignment = (id: string, agentId: string, role: "implementer" | "coordinator", runId: string): AgentAssignment => ({ schemaVersion: 1, id, collaborationId: collaboration.id, depth: 0, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, agentId, role, objective: role, acceptanceCriteria: ["done"], mode: "read-only", dependencyIds: [], status: "running", agentRunId: runId, worktreeLeaseId: `worktree-${id}`, proposedBy: { kind: "human", actor: "owner" }, createdAt: now, startedAt: now });
  const sender = assignment("assignment-sender", "worker", "implementer", "agent-run-sender"); const coordinator = assignment("assignment-coordinator", "lead", "coordinator", "agent-run-lead"); const basis = { collaborationId: collaboration.id, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, allowedAgentIds: [sender.agentId, coordinator.agentId], allowedRoles: [sender.role, coordinator.role], limits: collaboration.limits, worktreePolicy: { writersRequireIsolatedWorktree: true as const, allowReadOnlySharedSnapshot: true, baseRevision: "HEAD", baseCommit: "a".repeat(40), autoMerge: false as const, autoPush: false as const }, delegationPolicy: { mode: "plan-bounded" as const, allowAgentDelegation: true, requireAcceptanceCriteria: true as const, requireKnownAgent: true as const }, harnessRuleSnapshotDigest: "sha256:rules" }; const plan: CollaborationPlanSnapshot = { schemaVersion: 1, id: "collaboration-plan-1", digest: collaborationPlanDigest(basis), ...basis, createdAt: now }; collaboration.planSnapshotId = plan.id; collaboration.planDigest = plan.digest; storage.saveCollaborationPlanSnapshot(plan); storage.saveCollaboration(collaboration); storage.saveAgentAssignment(sender); storage.saveAgentAssignment(coordinator); for (const item of [sender, coordinator]) { storage.saveWorktreeLease({ schemaVersion: 1, id: item.worktreeLeaseId!, collaborationId: collaboration.id, assignmentId: item.id, workspaceId: collaboration.workspaceId, repositoryRoot: root, path: root, branch: `cjhx/${item.id}`, baseRevision: "HEAD", baseCommit: "a".repeat(40), status: "active", createdAt: now }); storage.saveAgentRun({ id: item.agentRunId!, taskId: item.taskId, changeId: item.changeId, workspaceId: item.workspaceId, agentId: item.agentId, agentName: item.agentId, agentKind: "custom", status: "running", startedAt: now, stdout: "", stderr: "", collaborationId: collaboration.id, assignmentId: item.id, worktreeLeaseId: item.worktreeLeaseId }); } const messages = new CollaborationMessageService(storage); return { storage, messages, sender, coordinator };
}

test("cjhx-agent uses only the loopback capability protocol", async (t) => {
  const { messages, sender, coordinator } = fixture(t); const bridge = new CollaborationBridge(messages); const address = await bridge.listen(); t.after(() => bridge.close()); const senderCapability = messages.issueCapability({ assignmentId: sender.id, runId: sender.agentRunId!, permissions: ["message.send", "message.read-own"] }); const coordinatorCapability = messages.issueCapability({ assignmentId: coordinator.id, runId: coordinator.agentRunId!, permissions: ["message.read-own"] }); const senderEnv = { CJHX_COLLABORATION_URL: address.url, CJHX_COLLABORATION_TOKEN: senderCapability.token };
  let result = await run(["assignment"], senderEnv); assert.equal(result.status, 0, result.stderr); assert.equal((JSON.parse(result.stdout) as { id: string }).id, sender.id);
  result = await run(["message", "send", "--to", `assignment:${coordinator.id}`, "--type", "handoff", "--subject", "Ready", "--body", "token=private implementation ready"], senderEnv); assert.equal(result.status, 0, result.stderr); assert.equal((JSON.parse(result.stdout) as { body: string }).body, "token=[REDACTED] implementation ready");
  result = await run(["inbox"], { CJHX_COLLABORATION_URL: address.url, CJHX_COLLABORATION_TOKEN: coordinatorCapability.token }); assert.equal(result.status, 0, result.stderr); const inbox = JSON.parse(result.stdout) as Array<{ id: string }>; assert.equal(inbox.length, 1);
  result = await run(["message", "consume", "--id", inbox[0]!.id], { CJHX_COLLABORATION_URL: address.url, CJHX_COLLABORATION_TOKEN: coordinatorCapability.token }); assert.equal(result.status, 0, result.stderr); assert.equal((JSON.parse(result.stdout) as { status: string }).status, "consumed");
});

test("cjhx-agent refuses non-loopback Bridge URLs", async () => {
  const result = await run(["inbox"], { CJHX_COLLABORATION_URL: "https://example.com", CJHX_COLLABORATION_TOKEN: "secret" }); assert.equal(result.status, 1); assert.match(result.stderr, /environment is unavailable/);
});
