import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { AgentService, type AgentExecutionPlan, type AgentExecutor } from "../src/agents.js";
import { CollaborationMessageService } from "../src/collaboration-bridge.js";
import { CollaborationScheduler } from "../src/collaboration-scheduler.js";
import { CollaborationService } from "../src/collaboration-service.js";
import { HarnessService } from "../src/harness.js";
import { Workspace } from "../src/storage.js";
import type { Task } from "../src/tasks.js";
import { WorktreeLeaseService } from "../src/worktree-leases.js";

async function waitUntil(assertion: () => boolean, timeout = 3_000): Promise<void> { const start = Date.now(); while (Date.now() - start < timeout) { if (assertion()) return; await new Promise((resolve_) => setTimeout(resolve_, 25)); } assert.fail("timed out waiting for collaboration state"); }
async function fixture(t: test.TestContext, delay = 220, executorCapabilities: string[] = []) {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-collaboration-scheduler-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repository = resolve(root, "repo"); execFileSync("git", ["init", "-b", "main", repository]); writeFileSync(resolve(repository, "package.json"), JSON.stringify({ scripts: { test: "node -e \"process.exit(0)\"" } })); writeFileSync(resolve(repository, "README.md"), "base\n"); execFileSync("git", ["-C", repository, "add", "."]); execFileSync("git", ["-C", repository, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const script = resolve(root, "agent.mjs"); writeFileSync(script, `if(process.argv.includes("--version")){console.log("worker 1.0");process.exit(0)} await new Promise(r=>setTimeout(r,${delay})); console.log("FINAL RESPONSE: completed "+process.env.CJHX_ASSIGNMENT_ID);`); chmodSync(script, 0o700);
  const storage = new Workspace(resolve(root, ".cjhx")); const task: Task = { id: "task-1", workspaceId: "workspace-1", changeId: "CHANGE-1", title: "Parallel task", description: "", owner: "owner", priority: "P1", riskLevel: "L2", status: "in_progress", authority: "local-draft", acceptanceCriteria: ["Done"], dependencies: [], evidenceRefs: [], history: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const workspace = { id: "workspace-1", kind: "local" as const, rootPath: repository }; const harness = new HarnessService(storage, { task: () => task, workspace: () => workspace }); const executionPlans: AgentExecutionPlan[] = []; const executor: AgentExecutor | undefined = executorCapabilities.length ? { id: "test-bounded-executor", capabilities: () => new Set(executorCapabilities), start: (plan) => { executionPlans.push(plan); return spawn(plan.command, plan.arguments, { cwd: plan.cwd, env: plan.environment, stdio: ["pipe", "pipe", "pipe"], shell: false, detached: process.platform !== "win32" }); } } : undefined; const agents = new AgentService(storage, { task: () => task, workspace: () => workspace, harness, ...(executor ? { executor } : {}) }); await agents.save({ id: "worker", name: "Worker", kind: "pi", command: process.execPath, arguments: [script, "{prompt}"], versionArguments: [script, "--version"], promptTransport: "argument", timeoutMinutes: 5, environmentKeys: [] }, { approved: true });
  const worktrees = new WorktreeLeaseService(storage, { workspace: () => workspace }); const collaborations = new CollaborationService(storage, { task: () => task, workspace: () => workspace, agentIds: () => agents.summary().profiles.map((item) => item.id), harnessSnapshotDigest: (taskId) => harness.effectiveForTask(taskId).digest, resolveBaseCommit: (workspaceId, revision) => worktrees.resolveBaseCommit(workspaceId, revision) }); const messages = new CollaborationMessageService(storage); const scheduler = new CollaborationScheduler(storage, collaborations, agents, messages, worktrees, { bridgeUrl: "http://127.0.0.1:4318" }); return { root, script, storage, repository, agents, collaborations, messages, worktrees, scheduler, executionPlans };
}

function startPlan(collaborations: CollaborationService, limits: { maxParallel: number; maxTokens?: number }) { const collaboration = collaborations.create({ taskId: "task-1", title: "Parallel", objective: "Run assignments", createdBy: "owner", limits }); const plan = collaborations.previewPlan(collaboration.id, { allowedAgentIds: ["worker"], allowedRoles: ["implementer", "reviewer"], baseRevision: "HEAD" }); collaborations.start(collaboration.id, { approved: true, approvedPlanDigest: plan.digest }); return collaboration; }

test("independent Assignments execute concurrently in isolated worktrees", async (t) => {
  const { storage, agents, collaborations, scheduler } = await fixture(t); const collaboration = startPlan(collaborations, { maxParallel: 2 }); const first = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement A", acceptanceCriteria: ["A done"], actor: "owner" }); const second = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "write", objective: "Review B", acceptanceCriteria: ["B reviewed"], actor: "owner" }); const result = scheduler.schedule(collaboration.id); assert.equal(result.started.length, 2); assert.equal(storage.getAgentAssignment(first.id).status, "running"); assert.equal(storage.getAgentAssignment(second.id).status, "running"); const roots = agents.listRuns().filter((run) => run.collaborationId === collaboration.id).map((run) => run.executionRoot); assert.equal(new Set(roots).size, 2); assert.ok(roots.every(Boolean)); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded"); assert.deepEqual(collaborations.assignments(collaboration.id).map((item) => item.status), ["succeeded", "succeeded"]);
});

test("local process execution fails closed for read-only Assignments", async (t) => {
  const { collaborations, scheduler, agents } = await fixture(t); const collaboration = startPlan(collaborations, { maxParallel: 1 }); const assignment = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "read-only", objective: "Inspect only", acceptanceCriteria: ["Report"], actor: "owner" }); assert.equal(scheduler.schedule(collaboration.id).started.length, 0); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "failed"); assert.match(collaborations.assignments(collaboration.id).find((item) => item.id === assignment.id)?.output?.summary ?? "", /cannot enforce read-only/); assert.equal(agents.listRuns().filter((item) => item.collaborationId === collaboration.id).length, 0);
});

test("scheduler approves the exact Worktree Harness snapshot", async (t) => {
  const { repository, collaborations, scheduler, agents } = await fixture(t, 80); writeFileSync(resolve(repository, "cjhx.harness.json"), JSON.stringify({ schemaVersion: 1, id: "collaboration", version: "1.0.0", scope: "workspace", mode: "enforce", rules: [{ id: "tests", description: "Run tests", requiredChecks: ["npm.test"] }] })); execFileSync("git", ["-C", repository, "add", "."]); execFileSync("git", ["-C", repository, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "add harness"]); const collaboration = startPlan(collaborations, { maxParallel: 1 }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Tests pass"], actor: "owner" }); scheduler.schedule(collaboration.id); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded"); const run = agents.listRuns().find((item) => item.collaborationId === collaboration.id)!; assert.equal(run.complianceStatus, "passed"); assert.equal(run.ruleSnapshotDigest, agents.dependencies.harness!.listSnapshots().find((item) => item.id === run.ruleSnapshotId)?.digest);
});

test("approved base commit remains fixed when HEAD moves", async (t) => {
  const { repository, collaborations, scheduler, worktrees } = await fixture(t, 80); const collaboration = startPlan(collaborations, { maxParallel: 1 }); const approved = collaborations.detail(collaboration.id).plan!.worktreePolicy.baseCommit; writeFileSync(resolve(repository, "later.txt"), "not approved\n"); execFileSync("git", ["-C", repository, "add", "."]); execFileSync("git", ["-C", repository, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "move head"]); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Done"], actor: "owner" }); scheduler.schedule(collaboration.id); const lease = worktrees.list(collaboration.id)[0]!; assert.equal(lease.baseCommit, approved); assert.notEqual(lease.baseCommit, execFileSync("git", ["-C", repository, "rev-parse", "HEAD"], { encoding: "utf8" }).trim()); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded");
});

test("approved cancellation terminates an active Agent Run", async (t) => {
  const { agents, collaborations, scheduler } = await fixture(t, 10_000); const collaboration = startPlan(collaborations, { maxParallel: 1 }); const assignment = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Long work", acceptanceCriteria: ["Done"], actor: "owner" }); scheduler.schedule(collaboration.id); await waitUntil(() => collaborations.assignments(collaboration.id)[0]?.status === "running"); const runId = collaborations.assignments(collaboration.id)[0]!.agentRunId!; scheduler.cancel(collaboration.id, { approved: true }); assert.equal(collaborations.detail(collaboration.id).collaboration.status, "cancelled"); assert.equal(collaborations.assignments(collaboration.id)[0]?.status, "cancelled"); await waitUntil(() => agents.getRun(runId).status !== "running"); assert.equal(agents.getRun(runId).status, "failed"); assert.equal(collaborations.assignments(collaboration.id).find((item) => item.id === assignment.id)?.status, "cancelled");
});

test("scheduler shutdown fails closed active Collaborations", async (t) => {
  const { agents, collaborations, scheduler } = await fixture(t, 10_000); const collaboration = startPlan(collaborations, { maxParallel: 1 }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Long work", acceptanceCriteria: ["Stopped"], actor: "owner" }); scheduler.schedule(collaboration.id); await waitUntil(() => collaborations.assignments(collaboration.id)[0]?.status === "running"); const runId = collaborations.assignments(collaboration.id)[0]!.agentRunId!; scheduler.close(); assert.equal(collaborations.detail(collaboration.id).collaboration.status, "failed"); await waitUntil(() => agents.getRun(runId).status !== "running");
});

test("cancellation terminates descendant Agent processes", async (t) => {
  if (process.platform === "win32") return; const { root, script, collaborations, scheduler } = await fixture(t, 10_000); const marker = resolve(root, "descendant-survived.txt"); writeFileSync(script, `import{spawn}from"node:child_process";if(process.argv.includes("--version")){console.log("worker 1.0");process.exit(0)}spawn(process.execPath,["-e",${JSON.stringify(`setTimeout(()=>require("fs").writeFileSync(${JSON.stringify(marker)},"survived"),800);setTimeout(()=>{},5000)`) }],{stdio:"ignore"});await new Promise(r=>setTimeout(r,10000));`); const collaboration = startPlan(collaborations, { maxParallel: 1 }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Spawn descendant", acceptanceCriteria: ["Cancelled"], actor: "owner" }); scheduler.schedule(collaboration.id); await waitUntil(() => collaborations.assignments(collaboration.id)[0]?.status === "running"); scheduler.cancel(collaboration.id, { approved: true }); await new Promise((resolve_) => setTimeout(resolve_, 1_100)); assert.equal(existsSync(marker), false);
});

test("expired Collaborations fail closed before launching work", async (t) => {
  const { storage, agents, collaborations, scheduler } = await fixture(t); const collaboration = startPlan(collaborations, { maxParallel: 1 }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Late work", acceptanceCriteria: ["Done"], actor: "owner" }); const stored = collaborations.detail(collaboration.id).collaboration; stored.startedAt = new Date(Date.now() - 121 * 60_000).toISOString(); storage.saveCollaboration(stored); const result = scheduler.schedule(collaboration.id); assert.equal(result.collaboration.status, "failed"); assert.equal(collaborations.assignments(collaboration.id)[0]?.status, "failed"); assert.equal(agents.listRuns().filter((item) => item.collaborationId === collaboration.id).length, 0);
});

test("dependency Assignments wait for predecessors before starting", async (t) => {
  const { collaborations, scheduler } = await fixture(t, 120); const collaboration = startPlan(collaborations, { maxParallel: 2 }); const first = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Done"], actor: "owner" }); const second = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "write", objective: "Review", acceptanceCriteria: ["Reviewed"], dependencyIds: [first.id], actor: "owner" }); assert.equal(scheduler.schedule(collaboration.id).started.length, 1); assert.equal(collaborations.assignments(collaboration.id).find((item) => item.id === second.id)?.status, "ready"); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded"); assert.ok(collaborations.assignments(collaboration.id).find((item) => item.id === second.id)?.startedAt);
});

test("Worktree provisioning failure terminalizes the Assignment", async (t) => {
  const { repository, collaborations, scheduler } = await fixture(t); const collaboration = startPlan(collaborations, { maxParallel: 1 }); const assignment = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Done"], actor: "owner" }); const segment = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(-20) || "item"; mkdirSync(resolve(repository, "..", ".cjhx-worktrees", segment("repo"), segment(collaboration.id), segment(assignment.id)), { recursive: true }); const result = scheduler.schedule(collaboration.id); assert.equal(result.started.length, 0); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "failed"); const failed = collaborations.assignments(collaboration.id)[0]!; assert.equal(failed.status, "failed"); assert.match(failed.output?.summary ?? "", /Worktree provisioning failed/);
});

test("local process execution fails closed for hard Token limits", async (t) => {
  const { collaborations, scheduler } = await fixture(t); const collaboration = startPlan(collaborations, { maxParallel: 1, maxTokens: 100_000 }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Bounded work", acceptanceCriteria: ["Done"], actor: "owner" }); assert.equal(scheduler.schedule(collaboration.id).started.length, 0); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "failed"); assert.match(collaborations.assignments(collaboration.id)[0]?.output?.summary ?? "", /cannot enforce the Collaboration Token limit/);
});

test("parallel hard Token grants reserve disjoint aggregate capacity", async (t) => {
  const { collaborations, scheduler, executionPlans } = await fixture(t, 120, ["tokens.hard-limit"]); const collaboration = startPlan(collaborations, { maxParallel: 2, maxTokens: 10_000 }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "A", acceptanceCriteria: ["A"], actor: "owner" }); collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "write", objective: "B", acceptanceCriteria: ["B"], actor: "owner" }); assert.equal(scheduler.schedule(collaboration.id).started.length, 2); assert.equal(executionPlans.length, 2); assert.ok(executionPlans.every((plan) => Number.isInteger(plan.tokenLimit) && (plan.tokenLimit ?? 0) > 0)); assert.ok(executionPlans.reduce((total, plan) => total + (plan.tokenLimit ?? 0), 0) <= 10_000); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded");
});

test("Collaboration token budgets stop later Assignment launches", async (t) => {
  const { collaborations, scheduler } = await fixture(t, 80); const collaboration = startPlan(collaborations, { maxParallel: 1, maxTokens: 1 }); const first = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Done"], actor: "owner" }); const second = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "read-only", objective: "Review", acceptanceCriteria: ["Reviewed"], dependencyIds: [first.id], actor: "owner" }); scheduler.schedule(collaboration.id); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "blocked"); assert.equal(collaborations.assignments(collaboration.id).find((item) => item.id === second.id)?.status, "blocked"); assert.equal(collaborations.detail(collaboration.id).collaboration.usage.runningAssignments, 0);
});
