import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { chmodSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { AgentService } from "../src/agents.js";
import { CollaborationMessageService } from "../src/collaboration-bridge.js";
import { CollaborationScheduler } from "../src/collaboration-scheduler.js";
import { CollaborationService } from "../src/collaboration-service.js";
import { HarnessService } from "../src/harness.js";
import { Workspace } from "../src/storage.js";
import type { Task } from "../src/tasks.js";
import { WorktreeLeaseService } from "../src/worktree-leases.js";

async function waitUntil(assertion: () => boolean, timeout = 3_000): Promise<void> { const start = Date.now(); while (Date.now() - start < timeout) { if (assertion()) return; await new Promise((resolve_) => setTimeout(resolve_, 25)); } assert.fail("timed out waiting for collaboration state"); }
async function fixture(t: test.TestContext, delay = 220) {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-collaboration-scheduler-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repository = resolve(root, "repo"); execFileSync("git", ["init", "-b", "main", repository]); writeFileSync(resolve(repository, "package.json"), JSON.stringify({ scripts: { test: "node -e \"process.exit(0)\"" } })); writeFileSync(resolve(repository, "README.md"), "base\n"); execFileSync("git", ["-C", repository, "add", "."]); execFileSync("git", ["-C", repository, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const script = resolve(root, "agent.mjs"); writeFileSync(script, `if(process.argv.includes("--version")){console.log("worker 1.0");process.exit(0)} await new Promise(r=>setTimeout(r,${delay})); console.log("FINAL RESPONSE: completed "+process.env.CJHX_ASSIGNMENT_ID);`); chmodSync(script, 0o700);
  const storage = new Workspace(resolve(root, ".cjhx")); const task: Task = { id: "task-1", workspaceId: "workspace-1", changeId: "CHANGE-1", title: "Parallel task", description: "", owner: "owner", priority: "P1", riskLevel: "L2", status: "in_progress", authority: "local-draft", acceptanceCriteria: ["Done"], dependencies: [], evidenceRefs: [], history: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const workspace = { id: "workspace-1", kind: "local" as const, rootPath: repository }; const harness = new HarnessService(storage, { task: () => task, workspace: () => workspace }); const agents = new AgentService(storage, { task: () => task, workspace: () => workspace, harness }); await agents.save({ id: "worker", name: "Worker", kind: "pi", command: process.execPath, arguments: [script, "{prompt}"], versionArguments: [script, "--version"], promptTransport: "argument", timeoutMinutes: 5, environmentKeys: [] }, { approved: true });
  const collaborations = new CollaborationService(storage, { task: () => task, workspace: () => workspace, agentIds: () => agents.summary().profiles.map((item) => item.id), harnessSnapshotDigest: (taskId) => harness.effectiveForTask(taskId).digest }); const messages = new CollaborationMessageService(storage); const worktrees = new WorktreeLeaseService(storage, { workspace: () => workspace }); const scheduler = new CollaborationScheduler(storage, collaborations, agents, messages, worktrees, { bridgeUrl: "http://127.0.0.1:4318" }); return { storage, repository, agents, collaborations, messages, worktrees, scheduler };
}

function startPlan(collaborations: CollaborationService, limits: { maxParallel: number; maxTokens?: number }) { const collaboration = collaborations.create({ taskId: "task-1", title: "Parallel", objective: "Run assignments", createdBy: "owner", limits }); const plan = collaborations.previewPlan(collaboration.id, { allowedAgentIds: ["worker"], allowedRoles: ["implementer", "reviewer"], baseRevision: "HEAD" }); collaborations.start(collaboration.id, { approved: true, approvedPlanDigest: plan.digest }); return collaboration; }

test("independent Assignments execute concurrently in isolated worktrees", async (t) => {
  const { storage, agents, collaborations, scheduler } = await fixture(t); const collaboration = startPlan(collaborations, { maxParallel: 2 }); const first = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement A", acceptanceCriteria: ["A done"], actor: "owner" }); const second = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "read-only", objective: "Review B", acceptanceCriteria: ["B reviewed"], actor: "owner" }); const result = scheduler.schedule(collaboration.id); assert.equal(result.started.length, 2); assert.equal(storage.getAgentAssignment(first.id).status, "running"); assert.equal(storage.getAgentAssignment(second.id).status, "running"); const roots = agents.listRuns().filter((run) => run.collaborationId === collaboration.id).map((run) => run.executionRoot); assert.equal(new Set(roots).size, 2); assert.ok(roots.every(Boolean)); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded"); assert.deepEqual(collaborations.assignments(collaboration.id).map((item) => item.status), ["succeeded", "succeeded"]);
});

test("dependency Assignments wait for predecessors before starting", async (t) => {
  const { collaborations, scheduler } = await fixture(t, 120); const collaboration = startPlan(collaborations, { maxParallel: 2 }); const first = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Done"], actor: "owner" }); const second = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "read-only", objective: "Review", acceptanceCriteria: ["Reviewed"], dependencyIds: [first.id], actor: "owner" }); assert.equal(scheduler.schedule(collaboration.id).started.length, 1); assert.equal(collaborations.assignments(collaboration.id).find((item) => item.id === second.id)?.status, "ready"); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "succeeded"); assert.ok(collaborations.assignments(collaboration.id).find((item) => item.id === second.id)?.startedAt);
});

test("Collaboration token budgets stop later Assignment launches", async (t) => {
  const { collaborations, scheduler } = await fixture(t, 80); const collaboration = startPlan(collaborations, { maxParallel: 1, maxTokens: 1 }); const first = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "implementer", mode: "write", objective: "Implement", acceptanceCriteria: ["Done"], actor: "owner" }); const second = collaborations.addAssignment(collaboration.id, { agentId: "worker", role: "reviewer", mode: "read-only", objective: "Review", acceptanceCriteria: ["Reviewed"], dependencyIds: [first.id], actor: "owner" }); scheduler.schedule(collaboration.id); await waitUntil(() => collaborations.detail(collaboration.id).collaboration.status === "blocked"); assert.equal(collaborations.assignments(collaboration.id).find((item) => item.id === second.id)?.status, "ready"); assert.equal(collaborations.detail(collaboration.id).collaboration.usage.runningAssignments, 0);
});
