import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { CollaborationBridge, CollaborationMessageService } from "../src/collaboration-bridge.js";
import { collaborationPlanDigest, type AgentAssignment, type Collaboration, type CollaborationPlanSnapshot } from "../src/collaboration.js";
import { PolicyDenied } from "../src/errors.js";
import { Workspace } from "../src/storage.js";

const now = "2026-08-21T00:00:00.000Z";
function fixture(t: test.TestContext, maxMessages = 5) {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-collaboration-bridge-")); t.after(() => rmSync(root, { recursive: true, force: true })); const storage = new Workspace(resolve(root, ".cjhx"));
  const collaboration: Collaboration = { schemaVersion: 1, id: "collaboration-1", workspaceId: "workspace-1", changeId: "CHANGE-1", taskId: "task-1", title: "Agent collaboration", objective: "Coordinate work", status: "running", limits: { maxAssignments: 8, maxDepth: 2, maxParallel: 3, maxMessages, timeoutMinutes: 60 }, usage: { assignments: 2, runningAssignments: 2, messages: 0, tokens: 0 }, createdBy: "owner", createdAt: now, updatedAt: now };
  const sender: AgentAssignment = { schemaVersion: 1, id: "assignment-sender", collaborationId: collaboration.id, depth: 0, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, agentId: "pi", role: "implementer", objective: "Implement", acceptanceCriteria: ["Implementation complete"], mode: "write", dependencyIds: [], status: "running", agentRunId: "agent-run-sender", worktreeLeaseId: "worktree-lease-sender", proposedBy: { kind: "human", actor: "owner" }, createdAt: now, startedAt: now };
  const receiver: AgentAssignment = { schemaVersion: 1, id: "assignment-receiver", collaborationId: collaboration.id, depth: 0, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, agentId: "reviewer", role: "coordinator", objective: "Review", acceptanceCriteria: ["Review complete"], mode: "read-only", dependencyIds: [], status: "running", agentRunId: "agent-run-receiver", worktreeLeaseId: "worktree-lease-receiver", proposedBy: { kind: "human", actor: "owner" }, createdAt: now, startedAt: now };
  const basis = { collaborationId: collaboration.id, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, allowedAgentIds: [sender.agentId, receiver.agentId], allowedRoles: [sender.role, receiver.role], limits: collaboration.limits, worktreePolicy: { writersRequireIsolatedWorktree: true as const, allowReadOnlySharedSnapshot: true, baseRevision: "HEAD", baseCommit: "a".repeat(40), autoMerge: false as const, autoPush: false as const }, delegationPolicy: { mode: "plan-bounded" as const, allowAgentDelegation: true, requireAcceptanceCriteria: true as const, requireKnownAgent: true as const }, harnessRuleSnapshotDigest: "sha256:rules" }; const plan: CollaborationPlanSnapshot = { schemaVersion: 1, id: "collaboration-plan-1", digest: collaborationPlanDigest(basis), ...basis, createdAt: now }; collaboration.planSnapshotId = plan.id; collaboration.planDigest = plan.digest; storage.saveCollaborationPlanSnapshot(plan); storage.saveCollaboration(collaboration); storage.saveAgentAssignment(sender); storage.saveAgentAssignment(receiver); for (const assignment of [sender, receiver]) { storage.saveWorktreeLease({ schemaVersion: 1, id: assignment.worktreeLeaseId!, collaborationId: collaboration.id, assignmentId: assignment.id, workspaceId: collaboration.workspaceId, repositoryRoot: root, path: root, branch: `cjhx/${assignment.id}`, baseRevision: "HEAD", baseCommit: "a".repeat(40), status: "active", createdAt: now }); storage.saveAgentRun({ id: assignment.agentRunId!, taskId: assignment.taskId, changeId: assignment.changeId, workspaceId: assignment.workspaceId, agentId: assignment.agentId, agentName: assignment.agentId, agentKind: "custom", status: "running", startedAt: now, stdout: "", stderr: "", collaborationId: collaboration.id, assignmentId: assignment.id, worktreeLeaseId: assignment.worktreeLeaseId }); } const service = new CollaborationMessageService(storage); return { storage, service, sender, receiver };
}

function auth(token: string): Record<string, string> { return { authorization: `Bearer ${token}`, "content-type": "application/json" }; }

test("Assignment capabilities exchange immutable scoped Agent messages", (t) => {
  const { storage, service, sender, receiver } = fixture(t); const senderCapability = service.issueCapability({ assignmentId: sender.id, runId: sender.agentRunId!, permissions: ["message.send", "message.read-own"] }); const receiverCapability = service.issueCapability({ assignmentId: receiver.id, runId: receiver.agentRunId!, permissions: ["message.send", "message.read-own"] });
  const sent = service.send(senderCapability.token, { recipient: { kind: "assignment", id: receiver.id }, type: "request", subject: "Review implementation", body: "api_key=secret-value Please inspect the patch" }); assert.equal(sent.body, "api_key=[REDACTED] Please inspect the patch"); assert.equal(service.inbox(senderCapability.token).length, 0); const inbox = service.inbox(receiverCapability.token); assert.equal(inbox.length, 1); assert.equal(inbox[0]?.status, "delivered"); const consumed = service.consume(receiverCapability.token, sent.id); assert.equal(consumed.status, "consumed"); assert.ok(consumed.consumedAt); assert.throws(() => service.consume(senderCapability.token, sent.id), PolicyDenied); assert.equal(storage.getAgentMessage(sent.id).digest, sent.digest); assert.equal(storage.getCollaboration(sender.collaborationId).usage.messages, 1);
  service.revoke(receiverCapability.id); assert.throws(() => service.inbox(receiverCapability.token), /expired, revoked, or insufficient/); const run = storage.getAgentRun(sender.agentRunId!); run.status = "succeeded"; run.completedAt = now; storage.saveAgentRun(run); assert.throws(() => service.inbox(senderCapability.token), /authoritative active/);
});

test("message limits remain bound to the approved plan", (t) => {
  const { storage, service, sender, receiver } = fixture(t, 1); const capability = service.issueCapability({ assignmentId: sender.id, runId: sender.agentRunId!, permissions: ["message.send"] }); const collaboration = storage.getCollaboration(sender.collaborationId); collaboration.limits.maxMessages = 100; storage.saveCollaboration(collaboration); service.send(capability.token, { recipient: { kind: "assignment", id: receiver.id }, type: "inform", subject: "One", body: "First" }); assert.throws(() => service.send(capability.token, { recipient: { kind: "assignment", id: receiver.id }, type: "inform", subject: "Two", body: "Second" }), /message limit/);
});

test("Collaboration Bridge is loopback-only and capability protected", async (t) => {
  const { service, sender, receiver } = fixture(t); const senderCapability = service.issueCapability({ assignmentId: sender.id, runId: sender.agentRunId!, permissions: ["message.send", "message.read-own"] }); const receiverCapability = service.issueCapability({ assignmentId: receiver.id, runId: receiver.agentRunId!, permissions: ["message.read-own"] }); const bridge = new CollaborationBridge(service); const address = await bridge.listen(); t.after(() => bridge.close()); assert.equal(address.host, "127.0.0.1");
  let response = await fetch(`${address.url}/v1/messages`, { method: "POST", headers: auth(senderCapability.token), body: JSON.stringify({ recipient: { kind: "assignment", id: receiver.id }, type: "handoff", subject: "Handoff", body: "Ready for review" }) }); assert.equal(response.status, 201); const message = await response.json() as { id: string };
  response = await fetch(`${address.url}/v1/inbox`, { headers: { authorization: `Bearer ${receiverCapability.token}` } }); assert.equal(response.status, 200); assert.equal((await response.json() as unknown[]).length, 1);
  response = await fetch(`${address.url}/v1/messages/${message.id}/consume`, { method: "POST", headers: auth(receiverCapability.token), body: "{}" }); assert.equal(response.status, 200);
  response = await fetch(`${address.url}/v1/inbox`); assert.equal(response.status, 403);
});

test("messages cannot cross Collaboration scope or outlive an active Assignment", (t) => {
  const { service, sender } = fixture(t); const capability = service.issueCapability({ assignmentId: sender.id, runId: sender.agentRunId!, permissions: ["message.send", "message.read-own"] }); assert.throws(() => service.send(capability.token, { recipient: { kind: "assignment", id: "assignment-outside" }, type: "inform", subject: "Cross scope", body: "No" }), /outside the Collaboration/); sender.status = "succeeded"; service.storage.saveAgentAssignment(sender); assert.throws(() => service.inbox(capability.token), /no longer matches authoritative active/);
});
