import assert from "node:assert/strict";
import { mkdtempSync, rmSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { ToolBroker } from "../src/adapters.js";
import { GitHubIntegrationManager } from "../src/github-config.js";
import { GitLabIntegrationManager } from "../src/gitlab-config.js";
import { SourceControlIntegrationManager } from "../src/source-control-config.js";
import { Workspace } from "../src/storage.js";

async function gateway(t: test.TestContext) { const seen: { url?: string; method?: string; privateToken?: string; authorization?: string; body?: string }[] = []; const server = createServer((request, response) => { let body = ""; request.on("data", (chunk: Buffer) => { body += chunk.toString(); }); request.on("end", () => { seen.push({ url: request.url, method: request.method, ...(typeof request.headers["private-token"] === "string" ? { privateToken: request.headers["private-token"] } : {}), ...(request.headers.authorization ? { authorization: request.headers.authorization } : {}), ...(body ? { body } : {}) }); response.writeHead(200, { "content-type": "application/json" }); response.end(request.url?.includes("/git/ref/") ? '{"object":{"sha":"0123456789012345678901234567890123456789"}}' : '{"id":1,"name":"repo","full_name":"owner/repo"}'); }); }); await new Promise<void>((accept) => server.listen(0, "127.0.0.1", accept)); t.after(() => server.close()); const address = server.address(); if (!address || typeof address === "string") throw new Error("missing address"); return { url: `http://127.0.0.1:${address.port}`, seen }; }
function fixture(t: test.TestContext) { const root = mkdtempSync(resolve(tmpdir(), "cjhx-source-config-")); t.after(() => rmSync(root, { recursive: true, force: true })); const workspace = new Workspace(resolve(root, ".cjhx")); workspace.initialize(); const tools = new ToolBroker(); const source = new SourceControlIntegrationManager(workspace, tools); return { workspace, tools, source, gitlab: new GitLabIntegrationManager(workspace, source), github: new GitHubIntegrationManager(workspace, source) }; }

test("GitLab configuration saves privately and activates SourceControlAdapter", async (t) => { const remote = await gateway(t); const { workspace, tools, gitlab } = fixture(t); const summary = await gitlab.save({ baseUrl: remote.url, authType: "private-token", credential: "gl-secret", projectId: "42" }); assert.equal(summary.active, true); assert.equal("credential" in summary, false); assert.equal(statSync(resolve(workspace.integrations, "gitlab.json")).mode & 0o777, 0o600); const adapter = tools.getAdapter("sourceControl"); assert.ok(adapter); await adapter.createBranch("42", "feature", "main"); assert.equal(remote.seen.at(-1)?.privateToken, "gl-secret"); assert.match(remote.seen.at(-1)?.url ?? "", /projects\/42\/repository\/branches/); });

test("GitHub and GitLab configurations coexist and can switch active provider", async (t) => { const remote = await gateway(t); const { workspace, tools, source, gitlab, github } = fixture(t); await gitlab.save({ baseUrl: remote.url, authType: "private-token", credential: "gl", projectId: "42" }); const githubSummary = await github.save({ baseUrl: remote.url, authType: "bearer", credential: "gh", repository: "owner/repo" }); assert.equal(githubSummary.active, true); assert.equal(gitlab.summary().configured, true); assert.equal(gitlab.summary().active, false); assert.equal(source.summary().activeProvider, "github"); const adapter = tools.getAdapter("sourceControl"); assert.ok(adapter); await adapter.getRepository("owner/repo"); assert.equal(remote.seen.at(-1)?.authorization, "Bearer gh"); gitlab.activate(); assert.equal(source.summary().activeProvider, "gitlab"); const restoredTools = new ToolBroker(); const restoredSource = new SourceControlIntegrationManager(workspace, restoredTools); new GitLabIntegrationManager(workspace, restoredSource); new GitHubIntegrationManager(workspace, restoredSource); assert.equal(restoredSource.summary().activeProvider, "gitlab"); assert.equal(restoredTools.hasAdapter("sourceControl"), true); });

test("removing an inactive source-control config preserves the active adapter", async (t) => { const remote = await gateway(t); const { tools, source, gitlab, github } = fixture(t); await gitlab.save({ baseUrl: remote.url, authType: "private-token", credential: "gl" }); await github.save({ baseUrl: remote.url, authType: "bearer", credential: "gh", repository: "owner/repo" }); gitlab.remove(); assert.equal(source.summary().activeProvider, "github"); assert.equal(tools.hasAdapter("sourceControl"), true); });
