import assert from "node:assert/strict";
import { mkdtempSync, realpathSync, rmSync } from "node:fs";
import { createServer, request as httpRequest } from "node:http";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { InMemoryDevOpsAdapter, InMemoryJiraAdapter, ToolBroker } from "../src/adapters.js";
import { CJHXFramework } from "../src/framework.js";
import { createUiServer } from "../src/ui.js";

async function fixture(t: test.TestContext, options: { jira?: InMemoryJiraAdapter; devops?: InMemoryDevOpsAdapter } = {}) {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const app = new CJHXFramework(resolve(root, ".cjhx"), { ...((options.jira || options.devops) ? { tools: new ToolBroker({ ...(options.jira ? { jira: options.jira } : {}), ...(options.devops ? { devops: options.devops } : {}) }) } : {}) }); app.initialize();
  const ui = createUiServer(app, { host: "127.0.0.1", port: 0, open: false });
  const address = await ui.listen(); t.after(async () => await ui.close());
  return { app, ui, base: address.url };
}

async function json(response: Response): Promise<Record<string, unknown>> {
  return await response.json() as Record<string, unknown>;
}

test("UI serves the control surface and workspace snapshot", async (t) => {
  const { base } = await fixture(t);
  const page = await fetch(base); assert.equal(page.status, 200); const html = await page.text(); assert.match(html, /CJHX Agile Workflow/); assert.match(html, /data-view="dashboard"[^>]*>.*>Dashboard</); assert.match(html, /data-view="goals"[^>]*>.*>目标</); assert.match(html, />工作空间</); assert.match(html, /data-view="changes"[^>]*>.*>研发流程</); assert.match(html, /data-view="agents"[^>]*>.*>智能体</); assert.match(html, /data-view="automations"[^>]*>.*>自动化</); assert.match(html, /id="token-meter"/); assert.match(html, /id="primary-action" hidden><\/button>/); assert.doesNotMatch(html, /data-view="board"/);
  const scriptResponse = await fetch(`${base}/app.js`); assert.equal(scriptResponse.status, 200); const script = await scriptResponse.text(); assert.match(script, /contentOnlyPrimaryActionViews\s*=\s*new Set\(\["dashboard",\s*"goals",\s*"automations",\s*"agents",\s*"skills",\s*"runs"\]\)/); assert.match(script, /primaryAction\.hidden\s*=\s*contentOnlyPrimaryActionViews\.has\(app\.view\)/); assert.match(script, /目标（Goal）<\/h1>.*data-action="new-goal">＋ 设置目标/s); assert.match(script, /<h1>自动化<\/h1>.*data-action="new-automation">＋ 新建自动化/s); assert.match(script, /<h1>智能体配置<\/h1>.*data-action="configure-agent">＋ 添加智能体/s); assert.match(script, /<h1>Skill Library<\/h1>.*data-action="install-skill">＋ 安装 Skill/s); assert.match(script, /<h1>运行记录<\/h1>.*data-action="run-workflow">↯ 运行 Workflow/s); assert.doesNotMatch(script, /Dashboard<\/h1>.*data-action="new-goal">＋ 设置目标.*dashboard-kpis/s);
  const response = await fetch(`${base}/api/snapshot`); assert.equal(response.status, 200);
  const body = await json(response); assert.deepEqual(body.changes, []); assert.deepEqual(body.skills, []); assert.deepEqual(body.runs, []);
});

test("UI stylesheet keeps long pages inside visible scroll containers", async (t) => {
  const { base } = await fixture(t); const response = await fetch(`${base}/styles.css`); assert.equal(response.status, 200); const css = await response.text();
  assert.match(css, /\.main\{[^}]*min-height:0/); assert.match(css, /\.content\{[^}]*min-height:0[^}]*overflow:auto/); assert.match(css, /\.scrollbar,.modal[^}]*\{scrollbar-width:thin;scrollbar-color:var\(--border\) transparent/); assert.match(css, /\.modal\{[^}]*scrollbar-gutter:stable/);
});

test("UI rejects non-loopback Host headers", async (t) => {
  const { base } = await fixture(t);
  const result = await new Promise<{ status: number; body: string }>((accept, reject) => {
    const request = httpRequest(`${base}/api/snapshot`, { headers: { host: "attacker.example" } }, (response) => { let body = ""; response.setEncoding("utf8"); response.on("data", (part: string) => { body += part; }); response.on("end", () => accept({ status: response.statusCode ?? 0, body })); });
    request.on("error", reject); request.end();
  });
  assert.equal(result.status, 403); assert.match(String((JSON.parse(result.body) as { error: string }).error), /host/i);
});

test("UI API manages local workspaces and codebase projections", async (t) => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-repo-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repo = resolve(root, "repo"); await import("node:fs").then(({ mkdirSync, writeFileSync }) => { mkdirSync(repo); writeFileSync(resolve(repo, "README.md"), "workspace API search\n"); }); const { execFileSync } = await import("node:child_process"); execFileSync("git", ["init", "-b", "main", repo]); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; let response = await fetch(`${base}/api/workspaces`, { method: "POST", headers, body: JSON.stringify({ kind: "local", path: repo }) }); assert.equal(response.status, 201); const workspace = await json(response); const id = String(workspace.id); response = await fetch(`${base}/api/workspaces/${id}/tree`); assert.equal(response.status, 403); response = await fetch(`${base}/api/workspaces/${id}/tree`, { headers }); assert.equal(response.status, 200); assert.equal((await response.json() as Array<Record<string, unknown>>)[0]?.name, "README.md"); response = await fetch(`${base}/api/workspaces/${id}/search?q=workspace`, { headers }); assert.equal(response.status, 200); assert.equal((await response.json() as unknown[]).length, 1); response = await fetch(`${base}/api/workspaces/${id}/commits`, { headers }); const commits = await response.json() as Array<Record<string, unknown>>; assert.equal(commits.length, 1); response = await fetch(`${base}/api/workspaces/${id}/commits/${commits[0]?.sha as string}/check`, { headers }); assert.equal((await json(response)).valid, true); response = await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "WS-1", workspaceId: id, title: "Workspace change", owner: "workspace-owner" }) }); assert.equal((await json(response)).workspaceId, id); response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "WS-1", workspaceId: id, title: "Workspace task", owner: "workspace-owner" }) }); assert.equal((await json(response)).workspaceId, id); response = await fetch(`${base}/api/workspaces/${id}/kanban`, { headers }); const scopedBoard = await json(response); assert.equal((scopedBoard.items as Array<Record<string, unknown>>).length, 1); assert.equal((scopedBoard.items as Array<Record<string, unknown>>)[0]?.source, "cjhx"); response = await fetch(`${base}/api/board`); assert.equal(response.status, 403); response = await fetch(`${base}/api/board`, { headers }); assert.equal(((await json(response)).items as unknown[]).length, 1); response = await fetch(`${base}/api/workspaces/${id}/team`, { headers }); assert.equal(((await response.json() as Array<Record<string, unknown>>)[0]?.name), "workspace-owner"); const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal((snapshot.workspaces as unknown[]).length, 1);
});

test("UI API configures agents and starts approved task development", async (t) => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-agent-repo-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repo = resolve(root, "repo"); const script = resolve(root, "agent.mjs"); const { chmodSync, mkdirSync, writeFileSync } = await import("node:fs"); mkdirSync(repo); writeFileSync(resolve(repo, "README.md"), "agent workspace\n"); writeFileSync(resolve(repo, "package.json"), JSON.stringify({ scripts: { typecheck: "node -e \"process.exit(0)\"" } })); writeFileSync(resolve(repo, "cjhx.harness.json"), JSON.stringify({ schemaVersion: 1, id: "ui-harness", version: "1.0.0", scope: "workspace", mode: "enforce", rules: [{ id: "quality", description: "Require typecheck", instruction: "Keep changes type safe.", requiredChecks: ["npm.typecheck"], gates: [{ target: "task.verification", requires: ["check:npm.typecheck"] }] }] })); writeFileSync(script, `if(process.argv.includes("--version")){console.log("agent 1.0");process.exit(0)} console.log("implemented",process.argv.at(-1));`); chmodSync(script, 0o700); const { execFileSync } = await import("node:child_process"); execFileSync("git", ["init", "-b", "main", repo]); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; let response = await fetch(`${base}/api/workspaces`, { method: "POST", headers, body: JSON.stringify({ kind: "local", path: repo }) }); const workspace = await json(response); response = await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "AGENT-1", workspaceId: workspace.id, title: "Agent task", owner: "dev" }) }); assert.equal(response.status, 201); response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "AGENT-1", workspaceId: workspace.id, title: "Implement feature", owner: "dev" }) }); const task = await json(response); const profile = { id: "codex", name: "Codex", kind: "codex", command: process.execPath, arguments: [script, "{prompt}"], versionArguments: [script, "--version"], promptTransport: "argument", timeoutMinutes: 5, environmentKeys: [], approved: true };
  response = await fetch(`${base}/api/agents/codex`, { method: "PUT", headers, body: JSON.stringify(profile) }); assert.equal(response.status, 200); assert.equal((await json(response)).default, true); response = await fetch(`${base}/api/agents`); assert.equal(response.status, 403); response = await fetch(`${base}/api/agents`, { headers }); assert.equal(((await json(response)).profiles as unknown[]).length, 1);
  response = await fetch(`${base}/api/tasks/${task.id as string}/harness`); assert.equal(response.status, 403); response = await fetch(`${base}/api/tasks/${task.id as string}/harness`, { headers }); assert.equal(response.status, 200); const harness = await json(response); const ruleSnapshot = harness.snapshot as Record<string, unknown>; assert.match(String(ruleSnapshot.digest), /^sha256:/); assert.deepEqual((ruleSnapshot.effective as Record<string, unknown>).requiredChecks, ["npm.typecheck"]);
  response = await fetch(`${base}/api/tasks/${task.id as string}/agent-runs`, { method: "POST", headers, body: JSON.stringify({ agentId: "codex", approved: false }) }); assert.equal(response.status, 400); response = await fetch(`${base}/api/tasks/${task.id as string}/agent-runs`, { method: "POST", headers, body: JSON.stringify({ agentId: "codex", approved: true, approvedRuleDigest: ruleSnapshot.digest }) }); assert.equal(response.status, 202); const run = await json(response); await new Promise((accept) => setTimeout(accept, 220)); response = await fetch(`${base}/api/agent-runs/${run.id as string}`); assert.equal(response.status, 403); response = await fetch(`${base}/api/agent-runs/${run.id as string}`, { headers }); const completed = await json(response); assert.equal(completed.status, "succeeded"); assert.equal(completed.complianceStatus, "passed"); response = await fetch(`${base}/api/harness/reports/${completed.complianceReportId as string}`); assert.equal(response.status, 403); response = await fetch(`${base}/api/harness/reports/${completed.complianceReportId as string}`, { headers }); assert.equal((await json(response)).status, "passed"); const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal((snapshot.agents as Record<string, unknown>).defaultAgentId, "codex"); assert.equal("stdout" in ((snapshot.agentRuns as Array<Record<string, unknown>>)[0] ?? {}), false); assert.equal((snapshot.agentRuns as Array<Record<string, unknown>>)[0]?.complianceStatus, "passed");
});

test("UI API manages resumable Agent sessions, immutable context, and confirmed memory", async (t) => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-memory-repo-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repo = resolve(root, "repo"); const script = resolve(root, "agent.mjs"); const { chmodSync, mkdirSync, writeFileSync } = await import("node:fs"); mkdirSync(repo); writeFileSync(resolve(repo, "README.md"), "conversation workspace\n"); writeFileSync(script, `if(process.argv.includes("--version")){console.log("agent 1.0");process.exit(0)} console.log("FINAL RESPONSE: completed turn");`); chmodSync(script, 0o700); const { execFileSync } = await import("node:child_process"); execFileSync("git", ["init", "-b", "main", repo]); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; let response = await fetch(`${base}/api/workspaces`, { method: "POST", headers, body: JSON.stringify({ kind: "local", path: repo }) }); const workspace = await json(response); await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "MEM-1", workspaceId: workspace.id, title: "Conversation", owner: "owner" }) }); response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "MEM-1", workspaceId: workspace.id, title: "Remember context", owner: "owner", acceptanceCriteria: ["Resume the session"] }) }); const task = await json(response);
  await fetch(`${base}/api/agents/local`, { method: "PUT", headers, body: JSON.stringify({ id: "local", name: "Local", kind: "custom", command: process.execPath, arguments: [script, "{prompt}"], versionArguments: [script, "--version"], promptTransport: "argument", timeoutMinutes: 5, environmentKeys: [], approved: true }) });
  response = await fetch(`${base}/api/agent-sessions`, { method: "POST", headers, body: JSON.stringify({ taskId: task.id, title: "Memory work", actor: "owner" }) }); assert.equal(response.status, 201); const session = await json(response);
  response = await fetch(`${base}/api/agent-sessions/${session.id as string}/turns/preview`, { method: "POST", headers, body: JSON.stringify({ userMessage: "Implement the memory flow", agentId: "local" }) }); assert.equal(response.status, 200); const preview = await json(response); const executionContext = preview.executionContext as Record<string, unknown>; assert.match(String(executionContext.digest), /^sha256:/); assert.equal(executionContext.userMessage, "Implement the memory flow"); assert.match(String(executionContext.renderedPrompt), /Implement the memory flow/); assert.match(String((preview.memorySnapshot as Record<string, unknown>).renderedContext), /untrusted reference data/i); response = await fetch(`${base}/api/execution-contexts/${executionContext.id as string}`); assert.equal(response.status, 403); response = await fetch(`${base}/api/execution-contexts/${executionContext.id as string}`, { headers }); assert.equal((await json(response)).userMessage, "Implement the memory flow");
  response = await fetch(`${base}/api/agent-sessions/${session.id as string}/turns`, { method: "POST", headers, body: JSON.stringify({ userMessage: "Implement the memory flow", agentId: "local", approved: true, approvedContextDigest: executionContext.digest }) }); assert.equal(response.status, 202); await new Promise((accept) => setTimeout(accept, 120)); response = await fetch(`${base}/api/agent-sessions/${session.id as string}`, { headers }); const detail = await json(response); assert.equal((detail.turns as Array<Record<string, unknown>>)[0]?.assistantResponse, "completed turn");
  response = await fetch(`${base}/api/memories`, { method: "POST", headers, body: JSON.stringify({ scope: { kind: "task", id: task.id }, kind: "decision", content: "Keep task history bounded.", importance: 5, pinned: true, actor: "owner", sourceRefs: [{ type: "task", id: task.id }] }) }); assert.equal(response.status, 201); const memory = await json(response); response = await fetch(`${base}/api/memories?taskId=${task.id as string}`); assert.equal(response.status, 403); response = await fetch(`${base}/api/memories?taskId=${task.id as string}`, { headers }); assert.equal((await response.json() as unknown[]).length, 1); response = await fetch(`${base}/api/memories/${memory.id as string}/forget`, { method: "POST", headers, body: JSON.stringify({ actor: "owner", reason: "obsolete" }) }); assert.equal((await json(response)).status, "forgotten");
});

test("UI API manages daily repository reviews and token usage behind the session token", async (t) => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-automation-repo-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repo = resolve(root, "repo"); const { mkdirSync, writeFileSync } = await import("node:fs"); mkdirSync(repo); writeFileSync(resolve(repo, "package.json"), JSON.stringify({ name: "review" })); writeFileSync(resolve(repo, "package-lock.json"), JSON.stringify({ lockfileVersion: 3 })); const { execFileSync } = await import("node:child_process"); execFileSync("git", ["init", "-b", "main", repo]); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; let response = await fetch(`${base}/api/workspaces`, { method: "POST", headers, body: JSON.stringify({ kind: "local", path: repo }) }); const workspace = await json(response); await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "AUTO-UI", workspaceId: workspace.id, title: "Automation", owner: "owner" }) }); response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "AUTO-UI", workspaceId: workspace.id, title: "Blocked", owner: "owner", status: "blocked", acceptanceCriteria: ["done"] }) }); assert.equal(response.status, 201); const task = await json(response);
  response = await fetch(`${base}/api/automations`); assert.equal(response.status, 403); response = await fetch(`${base}/api/automations`, { method: "POST", headers, body: JSON.stringify({ name: "Daily health", workspaceId: workspace.id, branch: "main", schedule: { days: "weekdays", time: "09:00", timezone: "Asia/Shanghai" }, checks: ["dependencies", "test-failures", "change-risk", "release-health", "blocked-tasks"], thresholds: { staleTaskBusinessDays: 3, reviewWaitingHours: 48, repeatedTestFailureCount: 3, highRiskChangeScore: 60 } }) }); assert.equal(response.status, 201); const automation = await json(response); response = await fetch(`${base}/api/automations/${automation.id as string}/run`, { method: "POST", headers, body: "{}" }); assert.equal(response.status, 202); const run = await json(response); assert.equal(run.status, "partial"); response = await fetch(`${base}/api/automation-reports`, { headers }); const reports = await response.json() as Array<Record<string, unknown>>; assert.equal(reports.length, 1); response = await fetch(`${base}/api/automation-reports/${reports[0]?.id as string}`, { headers }); let report = await json(response); assert.equal(report.stale, false); assert.equal((report.blockedTaskSummary as unknown[]).length, 1); assert.equal((report.releaseSummary as Record<string, unknown>).prediction !== undefined, true); assert.match(String(report.signalSnapshotDigest), /^sha256:/); response = await fetch(`${base}/api/automation-findings?automationId=${automation.id as string}`, { headers }); assert.ok((await response.json() as unknown[]).length >= 1); response = await fetch(`${base}/api/automations/${automation.id as string}/usage`, { headers }); assert.equal((await json(response)).runs, 0); response = await fetch(`${base}/api/automation-runs/${run.id as string}/usage`, { headers }); assert.equal((await json(response)).runs, 0); response = await fetch(`${base}/api/automations/${automation.id as string}`, { method: "PUT", headers, body: JSON.stringify({ name: "Daily updated", workspaceId: workspace.id, branch: "main", schedule: { days: "daily", time: "10:00", timezone: "Asia/Shanghai" }, checks: ["dependencies", "blocked-tasks"], thresholds: { staleTaskBusinessDays: 5, reviewWaitingHours: 72, repeatedTestFailureCount: 2, highRiskChangeScore: 70 } }) }); assert.equal(response.status, 200); assert.equal((await json(response)).name, "Daily updated");
  writeFileSync(resolve(repo, "README.md"), "changed\n"); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "change"]); response = await fetch(`${base}/api/automation-reports/${reports[0]?.id as string}`, { headers }); report = await json(response); assert.equal(report.stale, true);
  response = await fetch(`${base}/api/agent-usage/active`); assert.equal(response.status, 403); response = await fetch(`${base}/api/agent-usage/active`, { headers }); assert.equal(response.status, 200); assert.equal(((await json(response)).summary as Record<string, unknown>).runs, 0); response = await fetch(`${base}/api/agent-usage/tasks/${task.id as string}`, { headers }); assert.equal(response.status, 200); assert.equal((await json(response)).runs, 0);
});

test("UI API manages Goal contracts, immutable snapshots, and Dashboard projections", async (t) => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-goal-repo-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repo = resolve(root, "repo"); const { mkdirSync, writeFileSync } = await import("node:fs"); mkdirSync(repo); writeFileSync(resolve(repo, "README.md"), "goal UI\n"); const { execFileSync } = await import("node:child_process"); execFileSync("git", ["init", "-b", "main", repo]); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]);
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; let response = await fetch(`${base}/api/workspaces`, { method: "POST", headers, body: JSON.stringify({ kind: "local", path: repo }) }); const workspace = await json(response); response = await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "GOAL-UI", workspaceId: workspace.id, title: "Goal delivery", owner: "owner" }) }); assert.equal(response.status, 201);
  response = await fetch(`${base}/api/goals`); assert.equal(response.status, 403); response = await fetch(`${base}/api/goals`, { method: "POST", headers, body: JSON.stringify({ workspaceId: workspace.id, title: "降低发布失败率", statement: "将发布失败率降低到 5%", owner: "platform-team", priority: "high", targetDate: "2026-12-31", linkedChangeIds: ["GOAL-UI"], inScope: ["生产发布"], outOfScope: ["开发环境"], constraints: ["不得绕过 Harness"], sourceRefs: [{ kind: "confluence", id: "GOAL-BRIEF-1" }], successCriteria: [{ id: "failure-rate", name: "发布失败率", type: "metric", status: "on-track", baseline: 12, current: 8, target: 5, unit: "%", direction: "decrease", source: "devops", verificationDescription: "读取最近 30 天发布结果" }] }) }); assert.equal(response.status, 201); const goal = await json(response); assert.equal(goal.status, "draft"); assert.match(String(goal.currentSnapshotDigest), /^sha256:/);
  response = await fetch(`${base}/api/goals/${goal.id as string}/status`, { method: "POST", headers, body: JSON.stringify({ status: "active" }) }); assert.equal(response.status, 200); assert.equal((await json(response)).status, "active"); response = await fetch(`${base}/api/goals/${goal.id as string}`, { headers }); const assessment = await json(response); assert.equal(assessment.health, "on-track"); assert.equal((assessment.linkedChanges as unknown[]).length, 1); response = await fetch(`${base}/api/goals/${goal.id as string}/snapshots`, { headers }); assert.equal((await response.json() as unknown[]).length, 2); response = await fetch(`${base}/api/dashboard`); assert.equal(response.status, 403); response = await fetch(`${base}/api/dashboard`, { headers }); const dashboard = await json(response); assert.equal((dashboard.kpis as Record<string, unknown>).activeGoals, 1); const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal(((snapshot.goals as Record<string, unknown>).statuses as Record<string, unknown>).active, 1);
});

test("UI API requires its session token for mutations", async (t) => {
  const { base } = await fixture(t);
  const response = await fetch(`${base}/api/changes`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: "PAY-1", title: "Pay", owner: "team" }) });
  assert.equal(response.status, 403); assert.match(String((await json(response)).error), /token/i);
});

test("UI API creates changes and drives evidence-gated transitions", async (t) => {
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  let response = await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "PAY-1", title: "批量取消", owner: "product", riskLevel: "L2" }) });
  assert.equal(response.status, 201); assert.equal((await json(response)).state, "intent_draft");
  response = await fetch(`${base}/api/changes/PAY-1/transitions`, { method: "POST", headers, body: JSON.stringify({ target: "intent_confirmed", actor: "owner", reason: "confirmed" }) });
  assert.equal(response.status, 400); assert.match(String((await json(response)).error), /intent-approval/);
  response = await fetch(`${base}/api/changes/PAY-1/evidence`, { method: "POST", headers, body: JSON.stringify({ kind: "intent-approval", source: "jira", status: "approved", subjectRef: "jira://PAY-1" }) });
  assert.equal(response.status, 201);
  response = await fetch(`${base}/api/changes/PAY-1/transitions`, { method: "POST", headers, body: JSON.stringify({ target: "intent_confirmed", actor: "owner", reason: "confirmed" }) });
  assert.equal(response.status, 200); assert.equal((await json(response)).state, "intent_confirmed");
  const snapshot = await json(await fetch(`${base}/api/snapshot`)); const changes = snapshot.changes as Array<Record<string, unknown>>;
  assert.equal(changes.length, 1); assert.deepEqual(changes[0]?.nextTransitions, [{ target: "requirement_ready", missingEvidence: ["requirement-spec"] }, { target: "intent_draft", missingEvidence: [] }]);
});

test("UI API scans and toggles locally installed Skills", async (t) => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-local-skills-")); t.after(() => rmSync(root, { recursive: true, force: true }));
  const catalog = resolve(root, "catalog"); const instructions = resolve(catalog, "review-guide"); const { mkdirSync, writeFileSync } = await import("node:fs"); mkdirSync(instructions, { recursive: true }); writeFileSync(resolve(instructions, "SKILL.md"), "---\nname: review-guide\ndescription: Review local changes.\n---\n");
  const state = resolve(root, ".cjhx"); const app = new CJHXFramework(state, { localSkillRoots: [catalog] }); app.initialize(); const ui = createUiServer(app, { host: "127.0.0.1", port: 0, open: false }); const address = await ui.listen(); t.after(async () => await ui.close()); const base = address.url; const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  let response = await fetch(`${base}/api/local-skills`); assert.equal(response.status, 403); response = await fetch(`${base}/api/local-skills`, { headers }); assert.equal(response.status, 200); let catalogBody = await json(response); const skill = (catalogBody.skills as Array<Record<string, unknown>>)[0]!; assert.equal(skill.name, "review-guide"); assert.equal(skill.enabled, false); assert.equal(skill.path, realpathSync(instructions));
  response = await fetch(`${base}/api/local-skills/${skill.id as string}/enable`, { method: "POST", headers, body: "{}" }); assert.equal(response.status, 200); assert.equal((await json(response)).enabled, true);
  response = await fetch(`${base}/api/local-skills/${skill.id as string}/disable`, { method: "POST", headers, body: "{}" }); assert.equal(response.status, 200); assert.equal((await json(response)).enabled, false);
  const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal("localSkills" in snapshot, false);
});

test("UI API installs and runs a Skill against a change", async (t) => {
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "PAY-2", title: "需求", owner: "product" }) });
  let response = await fetch(`${base}/api/skills/install`, { method: "POST", headers, body: JSON.stringify({ packagePath: resolve(process.cwd(), "examples/skills/requirement-decompose") }) });
  assert.equal(response.status, 201); assert.equal(((await json(response)).manifest as Record<string, unknown>).id, "requirement.decompose");
  response = await fetch(`${base}/api/skills/requirement.decompose/runs`, { method: "POST", headers, body: JSON.stringify({ changeId: "PAY-2", input: { requirement: "支持批量取消；保留审计日志" } }) });
  assert.equal(response.status, 201); assert.equal((await json(response)).status, "succeeded");
  const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal((snapshot.runs as unknown[]).length, 1); assert.equal((snapshot.skills as unknown[]).length, 1);
});

test("UI API creates, imports, and transitions board tasks", async (t) => {
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "PAY-3", title: "任务看板", owner: "product" }) });
  let response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "PAY-3", title: "实现接口", owner: "backend", priority: "P1", riskLevel: "L2", acceptanceCriteria: ["返回逐单结果"] }) });
  assert.equal(response.status, 201); const task = await json(response); assert.equal(task.status, "todo"); assert.equal(task.authority, "local-draft");
  response = await fetch(`${base}/api/tasks/${task.id as string}/transitions`, { method: "POST", headers, body: JSON.stringify({ target: "in_progress", actor: "backend", reason: "started" }) });
  assert.equal(response.status, 200); assert.equal((await json(response)).status, "in_progress");
  await fetch(`${base}/api/skills/install`, { method: "POST", headers, body: JSON.stringify({ packagePath: resolve(process.cwd(), "examples/skills/requirement-decompose") }) });
  response = await fetch(`${base}/api/skills/requirement.decompose/runs`, { method: "POST", headers, body: JSON.stringify({ changeId: "PAY-3", input: { requirement: "实现审计；补充文档" } }) }); const run = await json(response);
  response = await fetch(`${base}/api/runs/${run.id as string}/tasks/import`, { method: "POST", headers, body: JSON.stringify({ changeId: "PAY-3" }) }); assert.equal(response.status, 201); assert.equal((await response.json() as unknown[]).length, 2);
  const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal((snapshot.tasks as unknown[]).length, 3); assert.deepEqual(snapshot.integrations, { jiraConfigured: false, jiraConfig: { configured: false, source: "none", credentialConfigured: false }, devopsConfigured: false, devopsConfig: { configured: false, source: "none", credentialConfigured: false }, sourceControl: { configured: false, source: "none" }, gitLabConfig: { configured: false, active: false, source: "none", credentialConfigured: false }, gitHubConfig: { configured: false, active: false, source: "none", credentialConfigured: false } });
});

test("UI API publishes and synchronizes Jira-owned tasks", async (t) => {
  const jira = new InMemoryJiraAdapter(); const { base, ui } = await fixture(t, { jira }); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "PAY-4", title: "Jira task", owner: "product" }) });
  let response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "PAY-4", title: "发布任务", owner: "backend" }) }); const draft = await json(response);
  response = await fetch(`${base}/api/tasks/${draft.id as string}/jira/publish`, { method: "POST", headers, body: JSON.stringify({ approved: false }) }); assert.equal(response.status, 400);
  response = await fetch(`${base}/api/tasks/${draft.id as string}/jira/publish`, { method: "POST", headers, body: JSON.stringify({ approved: true }) }); assert.equal(response.status, 200); const published = await json(response); assert.equal(published.authority, "jira");
  jira.setStatus(published.jiraIssueKey as string, "Review"); response = await fetch(`${base}/api/tasks/${draft.id as string}/jira/sync`, { method: "POST", headers, body: "{}" }); assert.equal(response.status, 200); assert.equal((await json(response)).status, "review"); response = await fetch(`${base}/api/board`, { headers }); const boardItem = ((await json(response)).items as Array<Record<string, unknown>>)[0]; assert.equal(boardItem?.source, "jira"); assert.equal(boardItem?.status, "review"); assert.equal(boardItem?.writable, true);
  const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.deepEqual(snapshot.integrations, { jiraConfigured: true, jiraConfig: { configured: true, source: "runtime", credentialConfigured: false }, devopsConfigured: false, devopsConfig: { configured: false, source: "none", credentialConfigured: false }, sourceControl: { configured: false, source: "none" }, gitLabConfig: { configured: false, active: false, source: "none", credentialConfigured: false }, gitHubConfig: { configured: false, active: false, source: "none", credentialConfigured: false } });
});

test("UI API tests, saves, redacts, and removes Jira configuration", async (t) => {
  const gateway = createServer((request, response) => { response.writeHead(200, { "content-type": "application/json" }); response.end(request.url === "/health" ? '{"status":"ok"}' : '{"key":"PAY-10","status":"To Do"}'); }); await new Promise<void>((accept) => gateway.listen(0, "127.0.0.1", accept)); t.after(() => gateway.close()); const address = gateway.address(); if (!address || typeof address === "string") throw new Error("missing gateway address");
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; const config = { baseUrl: `http://127.0.0.1:${address.port}`, authType: "bearer", credential: "jira-token", projectKey: "PAY", issueType: "Task", timeoutSeconds: 5 };
  let response = await fetch(`${base}/api/jira/config/test`, { method: "POST", headers, body: JSON.stringify(config) }); assert.equal(response.status, 200);
  response = await fetch(`${base}/api/jira/config`, { method: "PUT", headers, body: JSON.stringify(config) }); assert.equal(response.status, 200); const summary = await json(response); assert.equal(summary.configured, true); assert.equal(summary.credentialConfigured, true); assert.equal("credential" in summary, false);
  await fetch(`${base}/api/changes`, { method: "POST", headers, body: JSON.stringify({ id: "PAY-10", title: "Configured Jira", owner: "product" }) }); response = await fetch(`${base}/api/tasks`, { method: "POST", headers, body: JSON.stringify({ changeId: "PAY-10", title: "Publish", owner: "backend" }) }); const task = await json(response); response = await fetch(`${base}/api/tasks/${task.id as string}/jira/publish`, { method: "POST", headers, body: JSON.stringify({ approved: true }) }); assert.equal(response.status, 200); assert.equal((await json(response)).authority, "jira");
  response = await fetch(`${base}/api/jira/config`, { method: "DELETE", headers, body: "{}" }); assert.equal(response.status, 200); assert.equal((await json(response)).configured, false);
});

test("UI API configures and switches GitLab and GitHub adapters", async (t) => {
  const gateway = createServer((_request, response) => { response.writeHead(200, { "content-type": "application/json" }); response.end('{"id":1,"name":"repo","full_name":"owner/repo"}'); }); await new Promise<void>((accept) => gateway.listen(0, "127.0.0.1", accept)); t.after(() => gateway.close()); const address = gateway.address(); if (!address || typeof address === "string") throw new Error("missing gateway address");
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; const endpoint = `http://127.0.0.1:${address.port}`;
  let response = await fetch(`${base}/api/gitlab/config`, { method: "PUT", headers, body: JSON.stringify({ baseUrl: endpoint, apiPath: "/api/v4", authType: "private-token", credential: "gl-secret", projectId: "42", timeoutSeconds: 5 }) }); assert.equal(response.status, 200); assert.equal((await json(response)).active, true);
  response = await fetch(`${base}/api/github/config`, { method: "PUT", headers, body: JSON.stringify({ baseUrl: endpoint, apiPath: "", authType: "bearer", credential: "gh-secret", repository: "owner/repo", timeoutSeconds: 5 }) }); assert.equal(response.status, 200); assert.equal((await json(response)).active, true);
  let snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal((snapshot.integrations as Record<string, Record<string, unknown>>).sourceControl?.activeProvider, "github"); assert.equal((snapshot.integrations as Record<string, Record<string, unknown>>).gitLabConfig?.credentialConfigured, true); assert.equal("credential" in ((snapshot.integrations as Record<string, Record<string, unknown>>).gitHubConfig ?? {}), false);
  response = await fetch(`${base}/api/gitlab/config/activate`, { method: "POST", headers, body: "{}" }); assert.equal(response.status, 200); snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.equal((snapshot.integrations as Record<string, Record<string, unknown>>).sourceControl?.activeProvider, "gitlab");
});

test("UI API tests, saves, redacts, and removes DevOps configuration", async (t) => {
  const gateway = createServer((request, response) => { response.writeHead(200, { "content-type": "application/json" }); response.end(request.url === "/health" ? '{"status":"ok"}' : "[]"); }); await new Promise<void>((accept) => gateway.listen(0, "127.0.0.1", accept)); t.after(() => gateway.close()); const address = gateway.address(); if (!address || typeof address === "string") throw new Error("missing gateway address");
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token }; const config = { baseUrl: `http://127.0.0.1:${address.port}`, authType: "bearer", credential: "secret-token", projectId: "PAY", timeoutSeconds: 5 };
  let response = await fetch(`${base}/api/devops/config/test`, { method: "POST", headers, body: JSON.stringify(config) }); assert.equal(response.status, 200); assert.equal((await json(response)).status, "connected");
  response = await fetch(`${base}/api/devops/config`, { method: "PUT", headers, body: JSON.stringify(config) }); assert.equal(response.status, 200); const summary = await json(response); assert.equal(summary.configured, true); assert.equal(summary.credentialConfigured, true); assert.equal("credential" in summary, false);
  response = await fetch(`${base}/api/devops/config`); assert.equal(response.status, 200); assert.equal("credential" in await json(response), false);
  response = await fetch(`${base}/api/devops/config`, { method: "DELETE", headers, body: "{}" }); assert.equal(response.status, 200); assert.equal((await json(response)).configured, false);
});

test("UI API displays and operates DevOps projections with approval", async (t) => {
  const devops = new InMemoryDevOpsAdapter(); devops.pipelines.set("pay-ci", { id: "pay-ci", name: "支付 CI", kind: "ci", changeId: "PAY-5", status: "healthy" }); devops.artifacts.set("artifact-1", { artifactId: "artifact-1", name: "payment-api", version: "1.0.0", changeId: "PAY-5", status: "ready" }); devops.services.set("payment-api", { id: "payment-api", name: "支付服务", environment: "test", changeId: "PAY-5", status: "running" });
  const { base, ui } = await fixture(t, { devops }); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  let response = await fetch(`${base}/api/devops/overview?changeId=PAY-5`); assert.equal(response.status, 200); const overview = await json(response); assert.equal((overview.pipelines as unknown[]).length, 1); assert.equal((overview.artifacts as unknown[]).length, 1);
  response = await fetch(`${base}/api/devops/pipelines/trigger`, { method: "POST", headers, body: JSON.stringify({ pipelineId: "pay-ci", kind: "ci", actor: "owner", reason: "build", approved: false }) }); assert.equal(response.status, 400);
  response = await fetch(`${base}/api/devops/pipelines/trigger`, { method: "POST", headers, body: JSON.stringify({ pipelineId: "pay-ci", kind: "ci", changeId: "PAY-5", actor: "owner", reason: "build", approved: true }) }); assert.equal(response.status, 202); assert.equal((await json(response)).status, "running");
  response = await fetch(`${base}/api/devops/services/control`, { method: "POST", headers, body: JSON.stringify({ serviceId: "payment-api", action: "stop", actor: "operator", reason: "maintenance", approved: true }) }); assert.equal(response.status, 202); assert.equal((await json(response)).status, "stopped");
  const snapshot = await json(await fetch(`${base}/api/snapshot`)); assert.deepEqual(snapshot.integrations, { jiraConfigured: false, jiraConfig: { configured: false, source: "none", credentialConfigured: false }, devopsConfigured: true, devopsConfig: { configured: true, source: "runtime", credentialConfigured: false }, sourceControl: { configured: false, source: "none" }, gitLabConfig: { configured: false, active: false, source: "none", credentialConfigured: false }, gitHubConfig: { configured: false, active: false, source: "none", credentialConfigured: false } });
});

test("UI API runs a declarative Workflow", async (t) => {
  const { base, ui } = await fixture(t); const headers = { "content-type": "application/json", "x-cjhx-ui-token": ui.token };
  for (const name of ["requirement-decompose", "test-case-generate"]) await fetch(`${base}/api/skills/install`, { method: "POST", headers, body: JSON.stringify({ packagePath: resolve(process.cwd(), `examples/skills/${name}`) }) });
  const definition = { id: "ui-workflow", version: "1.0.0", name: "UI Workflow", steps: [{ id: "decompose", skill: "requirement.decompose", input: { requirement: { $ref: "input.requirement" } } }, { id: "tests", skill: "test.case.generate", input: { feature: "批量取消", acceptanceCriteria: ["返回结果"], tasks: { $ref: "steps.decompose.output.tasks" } } }] };
  const response = await fetch(`${base}/api/workflows/runs`, { method: "POST", headers, body: JSON.stringify({ definition, input: { requirement: "支持批量取消；记录审计日志" } }) });
  assert.equal(response.status, 201); const run = await json(response); assert.equal(run.status, "succeeded"); assert.equal(run.workflowId, "ui-workflow");
});

test("UI refuses non-loopback binding", () => {
  const root = mkdtempSync(resolve(tmpdir(), "cjhx-ui-bind-"));
  try { const app = new CJHXFramework(resolve(root, ".cjhx")); assert.throws(() => createUiServer(app, { host: "0.0.0.0", port: 0, open: false }), /loopback/); }
  finally { rmSync(root, { recursive: true, force: true }); }
});
