import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, realpathSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";
import { Workspace } from "../src/storage.js";
import { WorkspaceHub, type RemoteWorkspaceBrowser, type WorkspaceChangeRequest, type WorkspaceComment, type WorkspaceCommit, type WorkspaceCommitCheck, type WorkspaceFile, type WorkspaceIssue, type WorkspaceRef } from "../src/workspace-hub.js";
import type { JsonObject } from "../src/models.js";

function localFixture(t: test.TestContext) { const root = mkdtempSync(resolve(tmpdir(), "cjhx-workspace-")); t.after(() => rmSync(root, { recursive: true, force: true })); const repo = resolve(root, "repo"); mkdirSync(resolve(repo, "src"), { recursive: true }); writeFileSync(resolve(repo, "README.md"), "# Demo\nworkspace search target\n"); writeFileSync(resolve(repo, "src", "app.ts"), "export const answer = 42;\n"); execFileSync("git", ["init", "-b", "main", repo]); execFileSync("git", ["-C", repo, "add", "."]); execFileSync("git", ["-C", repo, "-c", "user.name=CJHX", "-c", "user.email=cjhx@example.com", "commit", "-m", "initial"]); const storage = new Workspace(resolve(root, ".cjhx")); const hub = new WorkspaceHub(storage, { remote: () => undefined, changes: () => [], tasks: () => [], runs: () => [] }); return { root, repo, hub }; }

test("local workspace browses files, Git refs, commits, checks, and worktrees", async (t) => { const { root, repo, hub } = localFixture(t); const workspace = hub.addLocal({ path: resolve(repo, "src") }); assert.equal(workspace.rootPath, realpathSync(repo)); assert.equal(hub.list().length, 1); assert.deepEqual((await hub.tree(workspace.id)).map((entry) => entry.name), ["src", "README.md"]); assert.match((await hub.file(workspace.id, "README.md")).content, /workspace search/); assert.equal(hub.search(workspace.id, "answer")[0]?.path, "src/app.ts"); assert.equal((await hub.refs(workspace.id))[0]?.name, "main"); const commit = (await hub.commits(workspace.id))[0]; assert.ok(commit); const check = await hub.inspectCommit(workspace.id, commit.sha); assert.equal(check.valid, true); assert.deepEqual(check.changedFiles.sort(), ["README.md", "src/app.ts"]); await assert.rejects(async () => await hub.file(workspace.id, "../outside"), /escapes|does not exist/); const target = resolve(root, "feature-worktree"); assert.throws(() => hub.addWorktree(workspace.id, { path: target, ref: "HEAD", createBranch: "feature", approved: false }), /approval/); const trees = hub.addWorktree(workspace.id, { path: target, ref: "HEAD", createBranch: "feature", approved: true }); assert.equal(trees.length, 2); assert.equal(hub.removeWorktree(workspace.id, { path: target, approved: true }).length, 1); assert.throws(() => hub.createRef(workspace.id, { name: "release", revision: "HEAD", type: "tag", approved: false }), /approval/); assert.ok(hub.createRef(workspace.id, { name: "release", revision: "HEAD", type: "tag", approved: true }).some((ref) => ref.name === "release")); assert.ok(!hub.deleteRef(workspace.id, { name: "release", type: "tag", approved: true }).some((ref) => ref.name === "release")); });

class RemoteFixture implements RemoteWorkspaceBrowser {
  getRepository(): Promise<JsonObject> { return Promise.resolve({ name: "remote", default_branch: "main" }); }
  listTree(): Promise<JsonObject[]> { return Promise.resolve([{ path: "src", name: "src", type: "tree" }, { path: "README.md", name: "README.md", type: "blob" }]); }
  getFile(_id: string, path: string, ref?: string): Promise<WorkspaceFile> { return Promise.resolve({ path, content: "remote file", encoding: "utf8", size: 11, ...(ref ? { ref } : {}) }); }
  listRefs(): Promise<WorkspaceRef[]> { return Promise.resolve([{ name: "main", type: "branch", sha: "abc" }]); }
  listCommits(): Promise<WorkspaceCommit[]> { return Promise.resolve([{ sha: "abc", shortSha: "abc", subject: "remote", author: "dev", authoredAt: "2026-01-01T00:00:00Z" }]); }
  inspectCommit(): Promise<WorkspaceCommitCheck> { return Promise.resolve({ sha: "abc", valid: true, signature: "verified", whitespaceErrors: [], changedFiles: ["README.md"], checks: [] }); }
  listIssues(): Promise<WorkspaceIssue[]> { return Promise.resolve([{ id: "1", number: 1, title: "Issue", state: "open", assignees: [], labels: [] }]); }
  listChangeRequests(): Promise<WorkspaceChangeRequest[]> { return Promise.resolve([{ id: "2", number: 2, title: "PR", state: "open", assignees: [], labels: [], sourceBranch: "feature", targetBranch: "main" }]); }
  listComments(): Promise<WorkspaceComment[]> { return Promise.resolve([{ id: "3", author: "reviewer", body: "Looks good" }]); }
}

test("local workspace never exposes its CJHX state directory", async (t) => { const root = mkdtempSync(resolve(tmpdir(), "cjhx-private-state-")); t.after(() => rmSync(root, { recursive: true, force: true })); execFileSync("git", ["init", "-b", "main", root]); writeFileSync(resolve(root, "README.md"), "public\n"); const storage = new Workspace(resolve(root, ".cjhx")); storage.initialize(); storage.saveIntegrationConfig("secret", { credential: "never-show" }); const hub = new WorkspaceHub(storage, { remote: () => undefined, changes: () => [], tasks: () => [], runs: () => [] }); const workspace = hub.addLocal({ path: root }); assert.equal((await hub.tree(workspace.id)).some((entry) => entry.name === ".cjhx"), false); await assert.rejects(async () => await hub.file(workspace.id, ".cjhx/integrations/secret.json"), /CJHX state/); assert.equal(hub.search(workspace.id, "never-show").length, 0); symlinkSync(resolve(root, ".cjhx", "integrations", "secret.json"), resolve(root, "secret-link")); symlinkSync(resolve(root, ".git", "config"), resolve(root, "git-config-link")); await assert.rejects(async () => await hub.file(workspace.id, "secret-link"), /CJHX state|protected state/); await assert.rejects(async () => await hub.file(workspace.id, "git-config-link"), /CJHX state|protected state/); });

test("virtual workspace projects remote repository, issues, change requests, and comments", async (t) => { const root = mkdtempSync(resolve(tmpdir(), "cjhx-virtual-workspace-")); t.after(() => rmSync(root, { recursive: true, force: true })); const remote = new RemoteFixture(); const tasks: import("../src/tasks.js").Task[] = []; const hub = new WorkspaceHub(new Workspace(resolve(root, ".cjhx")), { remote: () => remote, changes: () => [], tasks: () => tasks, runs: () => [] }); const workspace = await hub.addVirtual({ provider: "github", repositoryId: "owner/repo" }); tasks.push({ id: "task-1", workspaceId: workspace.id, changeId: "CHANGE-1", title: "Local task", description: "", owner: "dev", priority: "P2", riskLevel: "L1", status: "todo", authority: "local-draft", acceptanceCriteria: [], dependencies: [], evidenceRefs: [], history: [], createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z" }); assert.equal(workspace.kind, "virtual"); assert.equal(workspace.defaultRef, "main"); assert.equal((await hub.tree(workspace.id))[0]?.type, "tree"); assert.equal((await hub.file(workspace.id, "README.md")).ref, "main"); assert.equal((await hub.issues(workspace.id))[0]?.title, "Issue"); assert.equal((await hub.changeRequests(workspace.id))[0]?.sourceBranch, "feature"); assert.equal((((await hub.kanban(workspace.id)).tasks as unknown[]) ?? []).length, 1); assert.equal((await hub.comments(workspace.id, "change-request", 2))[0]?.body, "Looks good"); assert.equal(((await hub.overview(workspace.id)).summary as JsonObject).issues, 1); });
