import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { realpathSync } from "node:fs";
import { isAbsolute, relative } from "node:path";
import type { AgentService, TokenUsageSummary } from "./agents.js";
import type { DevOpsOverview, DevOpsService } from "./devops.js";
import { ValidationError } from "./errors.js";
import type { ComplianceReport, HarnessService } from "./harness.js";
import { isRecord, type JsonObject, type JsonValue, utcNow } from "./models.js";
import { fingerprintRepositoryState } from "./repository-state.js";
import type { Workspace } from "./storage.js";
import type { Task } from "./tasks.js";
import type { ManagedWorkspace, WorkspaceHub } from "./workspace-hub.js";

export const automationChecks = ["dependencies", "test-failures", "change-risk", "release-health", "blocked-tasks"] as const;
export type AutomationCheck = typeof automationChecks[number];
export type AutomationTrigger = "manual" | "schedule" | "catch-up";
export type FindingSeverity = "critical" | "high" | "medium" | "low" | "info";
export type AutomationHealth = "healthy" | "at-risk" | "blocked" | "unknown";

export interface AutomationDefinition {
  schemaVersion: 1; id: string; name: string; kind: "daily-repository-review"; workspaceId: string; branch: string;
  schedule: { days: "daily" | "weekdays"; time: string; timezone: string }; enabled: boolean; checks: AutomationCheck[];
  thresholds: { staleTaskBusinessDays: number; reviewWaitingHours: number; repeatedTestFailureCount: number; highRiskChangeScore: number };
  lastRunAt?: string; nextRunAt?: string; createdAt: string; updatedAt: string;
}
export interface AutomationClaim { schemaVersion: 1; automationId: string; runId: string; processId: number; processInstanceId: string; claimedAt: string }
export interface AutomationRun { schemaVersion: 1; id: string; automationId: string; workspaceId: string; trigger: AutomationTrigger; status: "running" | "succeeded" | "partial" | "failed"; definitionSnapshotId: string; reportId?: string; startedAt: string; completedAt?: string; error?: string; processId: number; processInstanceId: string }
export interface AutomationSignalSnapshot { schemaVersion: 1; id: string; digest: string; automationId: string; runId: string; workspaceId: string; definitionSnapshotId: string; repository: { baseCommitSha: string; headCommitSha: string; repositoryStateDigest: string; changedFiles: string[]; dirtyPaths: string[] }; tasks: Array<{ id: string; changeId: string; status: string; owner: string; dependencies: string[]; acceptanceCriteriaCount: number; updatedAt: string }>; devopsRuns: Array<{ id: string; kind: string; status: string; name?: string; changeId?: string; startedAt?: string; completedAt?: string }>; complianceReports: Array<{ id: string; taskId: string; status: string; repositoryStateDigest: string; createdAt: string; checks: Array<{ checkId: string; status: string }> }>; sourceStatus: AutomationReport["sourceStatus"]; createdAt: string }
export interface AutomationFinding {
  id: string; fingerprint: string; category: "dependency" | "test" | "change-risk" | "release" | "blocked-task" | "data-quality"; severity: FindingSeverity; lifecycle: "new" | "ongoing" | "resolved";
  title: string; facts: string[]; hypothesis?: string; recommendations: string[]; confidence: "high" | "medium" | "low"; workspaceId: string; changeId?: string; taskId?: string; firstObservedAt: string; lastObservedAt: string; resolvedAt?: string;
}
export interface AutomationReport {
  schemaVersion: 1; id: string; digest: string; automationId: string; runId: string; workspaceId: string; definitionSnapshotId: string; signalSnapshotId: string; signalSnapshotDigest: string; collectionStatus: "complete" | "partial" | "failed"; analysisStatus: "succeeded" | "failed";
  baseCommitSha?: string; headCommitSha?: string; repositoryStateDigest?: string; health: AutomationHealth; findings: AutomationFinding[];
  dependencySummary: { added: string[]; removed: string[]; changed: string[]; lockfileChanged: boolean; taskDependencyProblems: number };
  testSummary: { latestStatus: string; failedRuns: number; repeatedFailures: number; harnessFailed: number; harnessStale: number };
  changeRiskSummary: { score: number; level: "low" | "medium" | "high" | "critical"; changedFiles: string[]; factors: string[]; hardBlockers: string[] };
  releaseSummary: { releases7d: number; releases30d: number; successRate?: number; rollbackCount: number; readiness: AutomationHealth; readinessScore: number; blockers: string[]; warnings: string[]; prediction: { status: "available" | "unknown"; window?: string; confidence?: "low" | "medium" | "high"; reason?: string } };
  blockedTaskSummary: Array<{ taskId: string; title: string; classification: "explicitly-blocked" | "suspected-blocked"; owner: string; facts: string[]; recommendations: string[]; confidence: "high" | "medium" | "low" }>;
  deterministicSummary: string; sourceStatus: Array<{ source: string; status: "complete" | "partial" | "failed"; observedAt: string; message?: string }>; tokenUsage: TokenUsageSummary; createdAt: string;
}

interface AutomationDependencies { workspaces: WorkspaceHub; tasks(): Task[]; devops: DevOpsService; harness: HarnessService; agents: AgentService }
interface CreateInput { name: string; workspaceId: string; branch?: string; schedule?: Partial<AutomationDefinition["schedule"]>; enabled?: boolean; checks?: AutomationCheck[]; thresholds?: Partial<AutomationDefinition["thresholds"]> }
const defaults: AutomationDefinition["thresholds"] = { staleTaskBusinessDays: 3, reviewWaitingHours: 48, repeatedTestFailureCount: 3, highRiskChangeScore: 60 };
const identifier = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;
function digest(value: unknown): string { return `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`; }
function definitionDigest(value: AutomationDefinition): string { return digest({ schemaVersion: value.schemaVersion, id: value.id, name: value.name, kind: value.kind, workspaceId: value.workspaceId, branch: value.branch, schedule: value.schedule, enabled: value.enabled, checks: value.checks, thresholds: value.thresholds }); }
function required(value: unknown, key: string): string { if (typeof value !== "string" || !value.trim()) throw new ValidationError(`${key} is required`); return value.trim(); }
function number(value: unknown, key: string, min: number, max: number): number { const result = Number(value); if (!Number.isInteger(result) || result < min || result > max) throw new ValidationError(`${key} must be between ${min} and ${max}`); return result; }
function str(value: unknown, key: string): string | undefined { return isRecord(value) && typeof value[key] === "string" ? value[key] : undefined; }
function timeOf(value: JsonObject): string { return str(value, "completedAt") ?? str(value, "createdAt") ?? str(value, "startedAt") ?? str(value, "updatedAt") ?? ""; }
function statusOf(value: JsonObject): string { return (str(value, "status") ?? "unknown").toLowerCase(); }
function isSuccess(value: string): boolean { return ["passed", "succeeded", "success", "successful", "healthy", "completed"].includes(value); }
function isFailure(value: string): boolean { return ["failed", "failure", "error", "timed_out", "cancelled", "canceled"].includes(value); }
function severityRank(value: FindingSeverity): number { return { info: 0, low: 1, medium: 2, high: 3, critical: 4 }[value]; }
function subtractBusinessDays(now: Date, days: number): number { const value = new Date(now); let remaining = days; while (remaining > 0) { value.setUTCDate(value.getUTCDate() - 1); const weekday = value.getUTCDay(); if (weekday !== 0 && weekday !== 6) remaining -= 1; } return value.getTime(); }

export class AutomationService {
  private readonly processInstanceId = randomUUID();
  constructor(readonly storage: Workspace, private readonly dependencies: AutomationDependencies) { this.recoverInterruptedRuns(); }

  list(): AutomationDefinition[] { return this.storage.listAutomationDefinitions<AutomationDefinition>().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  get(id: string): AutomationDefinition { return this.storage.getAutomationDefinition<AutomationDefinition>(id); }
  listRuns(automationId?: string): AutomationRun[] { return this.storage.listAutomationRuns<AutomationRun>().filter((run) => !automationId || run.automationId === automationId).sort((a, b) => b.startedAt.localeCompare(a.startedAt)); }
  listReports(automationId?: string): AutomationReport[] { return this.storage.listAutomationReports<AutomationReport>().filter((report) => !automationId || report.automationId === automationId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  getRun(id: string): AutomationRun { return this.storage.getAutomationRun<AutomationRun>(id); }
  getReport(id: string): AutomationReport { return this.storage.getAutomationReport<AutomationReport>(id); }
  listFindings(automationId?: string): AutomationFinding[] { return this.storage.listAutomationFindings<AutomationFinding>().filter((finding) => !automationId || this.listReports(automationId).some((report) => report.findings.some((item) => item.id === finding.id))).sort((a, b) => b.lastObservedAt.localeCompare(a.lastObservedAt)); }
  reportView(id: string): AutomationReport & { stale: boolean } { const report = this.getReport(id); const definition = this.list().find((item) => item.id === report.automationId); if (!definition) return { ...report, stale: true }; const workspace = this.localWorkspace(report.workspaceId); let currentHead = ""; let currentStateDigest = ""; try { const root = realpathSync(workspace.rootPath); currentHead = execFileSync("git", ["-C", root, "rev-parse", "--verify", definition.branch], { encoding: "utf8", timeout: 10_000, maxBuffer: 65_536, stdio: ["ignore", "pipe", "ignore"] }).trim(); currentStateDigest = fingerprintRepositoryState(root, this.storage.root); } catch { return { ...report, stale: true }; } return { ...report, stale: currentHead !== report.headCommitSha || currentStateDigest !== report.repositoryStateDigest || definitionDigest(definition) !== this.snapshotDigest(report.definitionSnapshotId) }; }

  create(input: CreateInput): AutomationDefinition {
    const workspace = this.localWorkspace(input.workspaceId); const now = utcNow(); const id = `automation-${randomUUID().replaceAll("-", "")}`;
    const definition = this.normalize({ schemaVersion: 1, id, name: input.name, kind: "daily-repository-review", workspaceId: workspace.id, branch: input.branch ?? workspace.defaultRef ?? "HEAD", schedule: { days: input.schedule?.days ?? "weekdays", time: input.schedule?.time ?? "09:00", timezone: input.schedule?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone }, enabled: input.enabled ?? true, checks: input.checks ?? [...automationChecks], thresholds: { ...defaults, ...input.thresholds }, createdAt: now, updatedAt: now });
    if (definition.enabled) definition.nextRunAt = this.nextScheduledAt(definition, new Date(now)); this.storage.saveAutomationDefinition(definition); return definition;
  }
  update(id: string, input: Partial<CreateInput>): AutomationDefinition {
    const current = this.get(id); const workspace = this.localWorkspace(input.workspaceId ?? current.workspaceId); const updated = this.normalize({ ...current, ...(input.name !== undefined ? { name: input.name } : {}), workspaceId: workspace.id, ...(input.branch !== undefined ? { branch: input.branch } : {}), ...(input.schedule ? { schedule: { ...current.schedule, ...input.schedule } } : {}), ...(input.enabled !== undefined ? { enabled: input.enabled } : {}), ...(input.checks ? { checks: input.checks } : {}), ...(input.thresholds ? { thresholds: { ...current.thresholds, ...input.thresholds } } : {}), updatedAt: utcNow() });
    if (updated.enabled) updated.nextRunAt = this.nextScheduledAt(updated, new Date()); else delete updated.nextRunAt; this.storage.saveAutomationDefinition(updated); return updated;
  }
  remove(id: string): void { this.get(id); this.storage.removeAutomationDefinition(id); }
  enable(id: string, enabled: boolean): AutomationDefinition { return this.update(id, { enabled }); }

  async run(id: string, trigger: AutomationTrigger = "manual"): Promise<AutomationRun> {
    const definition = this.get(id); const existing = this.listRuns(id).find((item) => item.status === "running"); if (existing) return existing;
    const runId = `automation-run-${randomUUID().replaceAll("-", "")}`; const claim: AutomationClaim = { schemaVersion: 1, automationId: id, runId, processId: process.pid, processInstanceId: this.processInstanceId, claimedAt: utcNow() };
    if (!this.storage.createAutomationClaim(claim)) { const activeClaim = this.storage.getAutomationClaim(id); if (activeClaim) { try { const activeRun = this.getRun(activeClaim.runId); if (activeRun.status === "running") return activeRun; } catch { /* the claimant may still be persisting its run */ } if (this.claimIsActive(activeClaim)) throw new ValidationError("automation run is already claimed"); this.storage.removeAutomationClaim(id, activeClaim.runId); } if (!this.storage.createAutomationClaim(claim)) throw new ValidationError("automation run is already claimed"); }
    const definitionSnapshot = { schemaVersion: 1, id: `automation-definition-snapshot-${randomUUID().replaceAll("-", "")}`, digest: definitionDigest(definition), definition, createdAt: utcNow() }; const run: AutomationRun = { schemaVersion: 1, id: runId, automationId: id, workspaceId: definition.workspaceId, trigger, status: "running", definitionSnapshotId: definitionSnapshot.id, startedAt: utcNow(), processId: process.pid, processInstanceId: this.processInstanceId };
    try { this.storage.saveAutomationDefinitionSnapshot(definitionSnapshot); this.storage.saveAutomationRun(run); const report = await this.analyze(definition, run, definitionSnapshot.id); run.reportId = report.id; run.status = report.collectionStatus === "partial" ? "partial" : "succeeded"; }
    catch (error) { run.status = "failed"; run.error = error instanceof Error ? error.message.slice(0, 500) : String(error).slice(0, 500); }
    finally { run.completedAt = utcNow(); try { this.storage.saveAutomationRun(run); const current = this.list().find((item) => item.id === id); if (current) { current.lastRunAt = run.completedAt; current.nextRunAt = current.enabled ? this.nextScheduledAt(current, new Date(run.completedAt)) : undefined; current.updatedAt = run.completedAt; this.storage.saveAutomationDefinition(current); } } finally { this.storage.removeAutomationClaim(id, run.id); } }
    return run;
  }

  async runDue(now = new Date()): Promise<AutomationRun[]> {
    const due = this.list().filter((item) => item.enabled && item.nextRunAt && new Date(item.nextRunAt).getTime() <= now.getTime()); const results: AutomationRun[] = [];
    for (const item of due) { try { const scheduledAt = new Date(item.nextRunAt!).getTime(); const trigger: AutomationTrigger = now.getTime() - scheduledAt > 90_000 ? "catch-up" : "schedule"; results.push(await this.run(item.id, trigger)); } catch { /* another local scheduler may hold the atomic claim */ } } return results;
  }

  summary(): { enabled: number; running: number; failed: number; latestHealth?: AutomationHealth } { const definitions = this.list(); const runs = this.listRuns(); return { enabled: definitions.filter((item) => item.enabled).length, running: runs.filter((item) => item.status === "running").length, failed: runs.filter((item) => item.status === "failed").length, ...(this.listReports()[0]?.health ? { latestHealth: this.listReports()[0]!.health } : {}) }; }

  private async analyze(definition: AutomationDefinition, run: AutomationRun, definitionSnapshotId: string): Promise<AutomationReport> {
    const workspace = this.localWorkspace(definition.workspaceId); const root = realpathSync(workspace.rootPath!); const sourceStatus: AutomationReport["sourceStatus"] = [{ source: "repository", status: "complete", observedAt: utcNow() }, { source: "tasks", status: "complete", observedAt: utcNow() }];
    const git = (args: string[], allowFailure = false) => { try { return execFileSync("git", ["-C", root, ...args], { encoding: "utf8", timeout: 10_000, maxBuffer: 4 * 1_048_576, stdio: ["ignore", "pipe", allowFailure ? "ignore" : "pipe"] }); } catch (error) { if (allowFailure) return ""; throw new ValidationError(`automation Git read failed: ${error instanceof Error ? error.message.split("\n")[0] : String(error)}`); } };
    const head = git(["rev-parse", "--verify", definition.branch]).trim(); const prior = this.listReports(definition.id).find((item) => item.analysisStatus === "succeeded" && item.headCommitSha); const base = prior?.headCommitSha ?? head; const changedFiles = base === head ? [] : git(["diff", "--name-only", base, head], true).split("\n").filter(Boolean).slice(0, 500); const stateRelative = relative(root, this.storage.root); const protectedPrefix = !stateRelative || stateRelative.startsWith("..") || isAbsolute(stateRelative) ? undefined : stateRelative.replaceAll("\\", "/"); const dirtyPaths = git(["status", "--porcelain=v1"], true).split("\n").filter(Boolean).map((line) => line.slice(3)).filter((path) => !protectedPrefix || path !== protectedPrefix && !path.startsWith(`${protectedPrefix}/`)).slice(0, 500); const repositoryStateDigest = fingerprintRepositoryState(root, this.storage.root);
    const tasks = this.dependencies.tasks().filter((task) => task.workspaceId === definition.workspaceId); const needsDevOps = definition.checks.includes("test-failures") || definition.checks.includes("release-health"); let devops: DevOpsOverview | undefined; if (needsDevOps && this.dependencies.devops.configured()) { try { devops = await this.dependencies.devops.overview(undefined, definition.workspaceId); sourceStatus.push({ source: "devops", status: "complete", observedAt: utcNow() }); } catch (error) { sourceStatus.push({ source: "devops", status: "failed", observedAt: utcNow(), message: error instanceof Error ? error.message : String(error) }); } } else if (needsDevOps) sourceStatus.push({ source: "devops", status: "partial", observedAt: utcNow(), message: "DevOps Adapter is not configured" });
    const compliance = definition.checks.includes("test-failures") ? this.dependencies.harness.listReports().filter((item) => item.workspaceId === definition.workspaceId) as ComplianceReport[] : []; if (definition.checks.includes("test-failures")) sourceStatus.push({ source: "harness", status: "complete", observedAt: utcNow() });
    const observedAt = utcNow(); const signalBase = { schemaVersion: 1 as const, id: `automation-signal-snapshot-${randomUUID().replaceAll("-", "")}`, automationId: definition.id, runId: run.id, workspaceId: definition.workspaceId, definitionSnapshotId, repository: { baseCommitSha: base, headCommitSha: head, repositoryStateDigest, changedFiles, dirtyPaths }, tasks: tasks.map((task) => ({ id: task.id, changeId: task.changeId, status: task.status, owner: task.owner, dependencies: [...task.dependencies], acceptanceCriteriaCount: task.acceptanceCriteria.length, updatedAt: task.updatedAt })), devopsRuns: (devops?.runs ?? []).map((item) => ({ id: str(item, "id") ?? str(item, "runId") ?? "unknown", kind: str(item, "kind") ?? "unknown", status: statusOf(item), ...(str(item, "name") ? { name: str(item, "name") } : {}), ...(str(item, "changeId") ? { changeId: str(item, "changeId") } : {}), ...(str(item, "startedAt") ? { startedAt: str(item, "startedAt") } : {}), ...(str(item, "completedAt") ? { completedAt: str(item, "completedAt") } : {}) })), complianceReports: compliance.map((item) => ({ id: item.id, taskId: item.taskId, status: item.status, repositoryStateDigest: item.repositoryStateDigest, createdAt: item.createdAt, checks: item.checks.map((check) => ({ checkId: check.checkId, status: check.status })) })), sourceStatus, createdAt: observedAt }; const signalSnapshot: AutomationSignalSnapshot = { ...signalBase, digest: digest(signalBase) }; this.storage.saveAutomationSignalSnapshot(signalSnapshot);
    const findings: AutomationFinding[] = []; const add = (input: Omit<AutomationFinding, "id" | "fingerprint" | "lifecycle" | "firstObservedAt" | "lastObservedAt"> & { key: string }) => { const fingerprint = digest([definition.workspaceId, input.category, input.key]); const previous = this.listReports(definition.id).flatMap((report) => report.findings).find((finding) => finding.fingerprint === fingerprint && finding.lifecycle !== "resolved"); const now = utcNow(); findings.push({ ...input, id: `finding-${randomUUID().replaceAll("-", "")}`, fingerprint, lifecycle: previous ? "ongoing" : "new", firstObservedAt: previous?.firstObservedAt ?? now, lastObservedAt: now }); }; for (const source of sourceStatus.filter((item) => item.status !== "complete")) add({ key: source.source, category: "data-quality", severity: source.status === "failed" ? "high" : "medium", title: `${source.source} 审计信号不完整`, facts: [source.message ?? `${source.source} 返回 ${source.status}`], recommendations: ["恢复只读数据源后重新运行审计"], confidence: "high", workspaceId: definition.workspaceId });

    const dependency = definition.checks.includes("dependencies") ? this.dependencyDiff(base, head, git) : { added: [], removed: [], changed: [], lockfileChanged: false }; const lockfileChangedInRange = base !== head && changedFiles.some((file) => ["package-lock.json", "pnpm-lock.yaml", "yarn.lock"].includes(file)); let taskDependencyProblems = 0;
    if (definition.checks.includes("dependencies")) { for (const task of tasks) for (const dependencyId of task.dependencies) { const upstream = tasks.find((item) => item.id === dependencyId || item.sourceTaskId === dependencyId); if (!upstream || upstream.status !== "done") { taskDependencyProblems += 1; add({ key: `${task.id}:${dependencyId}`, category: "dependency", severity: upstream?.status === "blocked" ? "high" : "medium", title: `${task.title} 的依赖尚未完成`, facts: [`依赖 ${dependencyId} 当前为 ${upstream?.status ?? "不存在"}`, `下游任务状态为 ${task.status}`], recommendations: ["确认依赖 Owner、完成条件和预计时间"], confidence: "high", workspaceId: definition.workspaceId, changeId: task.changeId, taskId: task.id }); } }
    if (dependency.lockfileChanged) add({ key: `lockfile:${base}:${head}`, category: "dependency", severity: dependency.changed.length > 10 ? "high" : "medium", title: "依赖锁文件发生变化", facts: [`新增 ${dependency.added.length}、删除 ${dependency.removed.length}、变更 ${dependency.changed.length} 个直接依赖`, "锁文件包含在本次代码范围中"], recommendations: ["复核依赖来源、主版本升级和安装脚本"], confidence: "high", workspaceId: definition.workspaceId }); }

    const runFacts = devops?.runs ?? []; const failedRuns = definition.checks.includes("test-failures") ? runFacts.filter((item) => isFailure(statusOf(item))).length : 0; const latestStatus = definition.checks.includes("test-failures") && runFacts.sort((a, b) => timeOf(b).localeCompare(timeOf(a)))[0] ? statusOf(runFacts[0]!) : "not-checked"; const repeatedFailures = failedRuns >= definition.thresholds.repeatedTestFailureCount ? failedRuns : 0; if (repeatedFailures) add({ key: "repeated-test-failures", category: "test", severity: "high", title: "DevOps 验证连续或集中失败", facts: [`当前采集窗口包含 ${failedRuns} 个失败运行`, `升级阈值为 ${definition.thresholds.repeatedTestFailureCount}`], recommendations: ["定位最早失败 Commit，并确认是否需要人工批准重跑"], confidence: "medium", workspaceId: definition.workspaceId });
    const harnessFailed = definition.checks.includes("test-failures") ? compliance.filter((item) => item.status === "failed").length : 0; const harnessStale = definition.checks.includes("test-failures") ? compliance.filter((item) => item.status === "passed" && item.repositoryStateDigest !== repositoryStateDigest).length : 0; if (harnessFailed) add({ key: "harness-failed", category: "test", severity: "high", title: "存在 Harness Compliance 失败", facts: [`${harnessFailed} 份合规报告失败`], recommendations: ["按 Task 检查失败的 postflight check 和当前代码状态"], confidence: "high", workspaceId: definition.workspaceId }); if (harnessStale) add({ key: "harness-stale", category: "test", severity: "high", title: "已通过的 Harness 报告与当前仓库状态不一致", facts: [`${harnessStale} 份通过报告绑定了旧仓库状态`], recommendations: ["对当前 HEAD 和工作区状态重新执行 postflight check"], confidence: "high", workspaceId: definition.workspaceId });

    const factors: string[] = []; const hardBlockers: string[] = []; let score = 0; if (definition.checks.includes("change-risk")) { if (changedFiles.length > 20) { score += 15; factors.push(`变更文件较多（${changedFiles.length}）`); } else if (changedFiles.length > 5) { score += 8; factors.push(`变更 ${changedFiles.length} 个文件`); }
    if (changedFiles.some((file) => /auth|permission|security|payment|migration|schema/i.test(file))) { score += 20; factors.push("包含安全、权限、支付或数据迁移敏感路径"); }
    if (lockfileChangedInRange) { score += 15; factors.push("依赖锁文件变化"); } if (dirtyPaths.length) { score += 10; factors.push(`工作区存在 ${dirtyPaths.length} 个未提交路径`); } if (failedRuns || harnessFailed || harnessStale) { score += 20; factors.push("存在失败或过期验证"); hardBlockers.push("验证或 Harness Compliance 未全部通过且保持当前"); }
    if (tasks.some((task) => task.status === "blocked")) { score += 10; factors.push("存在 blocked Task"); } }
    score = Math.min(100, score); const level: AutomationReport["changeRiskSummary"]["level"] = score >= 70 ? "critical" : score >= definition.thresholds.highRiskChangeScore ? "high" : score >= 30 ? "medium" : "low"; if (score >= definition.thresholds.highRiskChangeScore || hardBlockers.length) add({ key: `change-risk:${base}:${head}`, category: "change-risk", severity: level === "critical" ? "critical" : "high", title: `当前代码范围风险为 ${level.toUpperCase()}`, facts: factors.length ? factors : ["风险由当前代码与验证事实计算"], recommendations: ["在发布前处理硬阻断并重新生成审计报告"], confidence: "high", workspaceId: definition.workspaceId });

    const blockedTaskSummary: AutomationReport["blockedTaskSummary"] = []; const staleBefore = subtractBusinessDays(new Date(), definition.thresholds.staleTaskBusinessDays);
    for (const task of definition.checks.includes("blocked-tasks") ? tasks.filter((item) => item.status !== "done") : []) { const facts: string[] = []; const explicit = task.status === "blocked"; if (explicit) facts.push("Task 权威状态为 blocked"); if (new Date(task.updatedAt).getTime() < staleBefore) facts.push(`超过 ${definition.thresholds.staleTaskBusinessDays} 个工作日没有状态更新`); if (task.status === "review" && Date.now() - new Date(task.updatedAt).getTime() > definition.thresholds.reviewWaitingHours * 3_600_000) facts.push(`处于评审状态超过 ${definition.thresholds.reviewWaitingHours} 小时`); const unresolved = task.dependencies.filter((dependencyId) => tasks.find((item) => item.id === dependencyId || item.sourceTaskId === dependencyId)?.status !== "done"); if (unresolved.length) facts.push(`未完成依赖：${unresolved.join("、")}`); if (task.owner === "unassigned") facts.push("Task 没有 Owner"); if (!task.acceptanceCriteria.length) facts.push("Task 缺少验收标准"); if (explicit || facts.length >= 2) { const classification = explicit ? "explicitly-blocked" : "suspected-blocked"; blockedTaskSummary.push({ taskId: task.id, title: task.title, classification, owner: task.owner, facts, recommendations: ["确认阻塞事实、Owner 和下一步解除条件"], confidence: explicit || unresolved.length ? "high" : "medium" }); add({ key: task.id, category: "blocked-task", severity: explicit ? "high" : "medium", title: `${task.title} ${explicit ? "明确阻塞" : "疑似阻塞"}`, facts, recommendations: ["确认阻塞原因、责任人和预计解除时间"], confidence: explicit || unresolved.length ? "high" : "medium", workspaceId: definition.workspaceId, changeId: task.changeId, taskId: task.id }); } }

    const releaseSelected = definition.checks.includes("release-health"); const releaseRuns = releaseSelected ? runFacts.filter((item) => ["cd", "deploy", "deployment", "release"].includes((str(item, "kind") ?? str(item, "type") ?? "").toLowerCase())) : []; const failedReleaseRuns = releaseRuns.filter((item) => isFailure(statusOf(item))).length; const nowMs = Date.now(); const within = (days: number) => releaseRuns.filter((item) => { const parsed = Date.parse(timeOf(item)); return Number.isFinite(parsed) && parsed >= nowMs - days * 86_400_000; }); const releases7d = within(7).length; const releases30d = within(30).length; const successful = releaseRuns.filter((item) => isSuccess(statusOf(item))).length; const rollbackCount = releaseRuns.filter((item) => /rollback|rolled.?back/i.test(statusOf(item)) || /rollback/i.test(str(item, "name") ?? "")).length; const releaseTaskBlockers = releaseSelected ? tasks.filter((item) => item.status === "blocked").map((item) => `${item.id} 仍处于 blocked`) : []; const blockers = [...hardBlockers, ...releaseTaskBlockers]; if (releaseSelected && failedReleaseRuns) blockers.push(`${failedReleaseRuns} 个发布或部署运行失败`); const warnings = factors.slice(); if (releaseSelected && rollbackCount) warnings.push(`${rollbackCount} 次回滚记录`); const readinessScore = releaseSelected ? Math.max(0, 100 - score - blockedTaskSummary.length * 5) : 0; const readiness: AutomationHealth = !releaseSelected ? "unknown" : blockers.length ? "blocked" : readinessScore < 80 ? "at-risk" : sourceStatus.some((item) => item.status !== "complete") ? "unknown" : "healthy";
    if (releaseSelected && readiness === "blocked") add({ key: "release-blocked", category: "release", severity: "critical", title: "当前发布准备度为 BLOCKED", facts: blockers, recommendations: ["处理所有硬阻断后重新审计"], confidence: "high", workspaceId: definition.workspaceId });
    const releaseTimes = releaseRuns.filter((item) => isSuccess(statusOf(item))).map((item) => Date.parse(timeOf(item))).filter(Number.isFinite).sort((a, b) => a - b); const intervals = releaseTimes.slice(1).map((value, index) => value - releaseTimes[index]!).filter((value) => value > 0); const medianInterval = intervals.length ? [...intervals].sort((a, b) => a - b)[Math.floor(intervals.length / 2)]! : 0; const lastRelease = releaseTimes.at(-1); const predictedAt = lastRelease === undefined ? 0 : Math.max(nowMs, lastRelease + medianInterval); const prediction = !releaseSelected ? { status: "unknown" as const, reason: "发布健康检查未启用" } : releaseTimes.length >= 3 && medianInterval > 0 && lastRelease !== undefined && tasks.filter((item) => item.status === "done").length >= 10 ? { status: "available" as const, window: `${new Date(Math.max(nowMs, predictedAt - medianInterval * 0.25)).toISOString().slice(0, 10)} – ${new Date(predictedAt + medianInterval * 0.25).toISOString().slice(0, 10)}`, confidence: releaseTimes.length >= 8 ? "medium" as const : "low" as const } : { status: "unknown" as const, reason: "历史发布或已完成 Task 样本不足" };

    const previousOpen = this.listReports(definition.id)[0]?.findings.filter((item) => item.lifecycle !== "resolved") ?? []; for (const old of previousOpen.filter((item) => !findings.some((current) => current.fingerprint === item.fingerprint))) findings.push({ ...old, id: `finding-${randomUUID().replaceAll("-", "")}`, lifecycle: "resolved", lastObservedAt: utcNow(), resolvedAt: utcNow() });
    const active = findings.filter((item) => item.lifecycle !== "resolved"); const health: AutomationHealth = active.some((item) => item.severity === "critical") ? "blocked" : active.some((item) => severityRank(item.severity) >= severityRank("high")) ? "at-risk" : sourceStatus.some((item) => item.status !== "complete") ? "unknown" : "healthy"; const collectionStatus: AutomationReport["collectionStatus"] = sourceStatus.some((item) => item.status === "failed" || item.status === "partial") ? "partial" : "complete"; const summary = `审计发现 ${active.filter((item) => item.lifecycle === "new").length} 个新增、${active.filter((item) => item.lifecycle === "ongoing").length} 个持续问题；${blockedTaskSummary.length} 个明确或疑似卡住任务；当前发布状态为 ${readiness.toUpperCase()}。`;
    const reportBase = { schemaVersion: 1 as const, id: `automation-report-${randomUUID().replaceAll("-", "")}`, automationId: definition.id, runId: run.id, workspaceId: definition.workspaceId, definitionSnapshotId, signalSnapshotId: signalSnapshot.id, signalSnapshotDigest: signalSnapshot.digest, collectionStatus, analysisStatus: "succeeded" as const, baseCommitSha: base, headCommitSha: head, repositoryStateDigest, health, findings, dependencySummary: { ...dependency, taskDependencyProblems }, testSummary: { latestStatus, failedRuns, repeatedFailures, harnessFailed, harnessStale }, changeRiskSummary: { score, level, changedFiles, factors, hardBlockers }, releaseSummary: { releases7d, releases30d, ...(releaseRuns.length ? { successRate: Math.round(successful / releaseRuns.length * 1000) / 10 } : {}), rollbackCount, readiness, readinessScore, blockers, warnings, prediction }, blockedTaskSummary, deterministicSummary: summary, sourceStatus, tokenUsage: this.dependencies.agents.usageSummary({ kind: "automation-run", id: run.id }), createdAt: utcNow() };
    const report: AutomationReport = { ...reportBase, digest: digest(reportBase) }; this.storage.saveAutomationReport(report); for (const finding of findings) this.storage.saveAutomationFinding(finding); return report;
  }

  private dependencyDiff(base: string, head: string, git: (args: string[], allowFailure?: boolean) => string) {
    const readAt = (commit: string) => { const raw = git(["show", `${commit}:package.json`], true); if (!raw) return {}; try { const value = JSON.parse(raw) as JsonObject; return { ...(isRecord(value.dependencies) ? value.dependencies : {}), ...(isRecord(value.devDependencies) ? value.devDependencies : {}) }; } catch { return {}; } };
    const before = readAt(base) as Record<string, JsonValue>; const after = readAt(head) as Record<string, JsonValue>; const added = Object.keys(after).filter((key) => !(key in before)).sort(); const removed = Object.keys(before).filter((key) => !(key in after)).sort(); const changed = Object.keys(after).filter((key) => key in before && after[key] !== before[key]).sort(); const lockfileChanged = base !== head && git(["diff", "--name-only", base, head], true).split("\n").some((file) => ["package-lock.json", "pnpm-lock.yaml", "yarn.lock"].includes(file)); return { added, removed, changed, lockfileChanged };
  }

  private snapshotDigest(snapshotId: string): string { try { const value = this.storage.getAutomationDefinitionSnapshot<{ digest: string }>(snapshotId); return value.digest; } catch { return ""; } }
  private claimIsActive(claim: AutomationClaim): boolean { if (Date.now() - Date.parse(claim.claimedAt) > 2 * 60 * 60 * 1000) return false; try { process.kill(claim.processId, 0); return true; } catch { return false; } }
  private recoverInterruptedRuns(): void { for (const run of this.storage.listAutomationRuns<AutomationRun>().filter((item) => item.status === "running" && item.processInstanceId !== this.processInstanceId)) { const claim = this.storage.getAutomationClaim(run.automationId); if (claim?.runId === run.id && this.claimIsActive(claim)) continue; run.status = "failed"; run.completedAt = utcNow(); run.error = "Automation execution ownership was lost before this CJHX process started; the incomplete run is not trusted."; this.storage.saveAutomationRun(run); this.storage.removeAutomationClaim(run.automationId, run.id); } }
  private normalize(value: AutomationDefinition): AutomationDefinition {
    if (!identifier.test(value.id)) throw new ValidationError("automation id contains unsupported characters"); const name = required(value.name, "automation name"); const workspaceId = required(value.workspaceId, "workspaceId"); const branch = required(value.branch, "branch"); if (branch.startsWith("-") || branch.includes("\0")) throw new ValidationError("invalid automation branch"); if (value.schedule.days !== "daily" && value.schedule.days !== "weekdays") throw new ValidationError("invalid automation schedule days"); if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(value.schedule.time)) throw new ValidationError("automation time must use HH:mm"); try { new Intl.DateTimeFormat("en-US", { timeZone: value.schedule.timezone }).format(); } catch { throw new ValidationError("invalid automation timezone"); } const checks = [...new Set(value.checks)]; if (!checks.length || !checks.every((item) => automationChecks.includes(item))) throw new ValidationError("invalid automation checks"); const thresholds = { staleTaskBusinessDays: number(value.thresholds.staleTaskBusinessDays, "staleTaskBusinessDays", 1, 30), reviewWaitingHours: number(value.thresholds.reviewWaitingHours, "reviewWaitingHours", 1, 720), repeatedTestFailureCount: number(value.thresholds.repeatedTestFailureCount, "repeatedTestFailureCount", 1, 20), highRiskChangeScore: number(value.thresholds.highRiskChangeScore, "highRiskChangeScore", 1, 100) }; return { ...value, name, workspaceId, branch, checks, thresholds };
  }
  private localWorkspace(id: string): ManagedWorkspace & { rootPath: string } { const workspace = this.dependencies.workspaces.get(required(id, "workspaceId")); if (workspace.kind !== "local" || !workspace.rootPath) throw new ValidationError("daily repository review requires a local Workspace"); return { ...workspace, rootPath: workspace.rootPath }; }
  private nextScheduledAt(definition: AutomationDefinition, after: Date): string { const [hour, minute] = definition.schedule.time.split(":").map(Number) as [number, number]; const formatter = new Intl.DateTimeFormat("en-US", { timeZone: definition.schedule.timezone, weekday: "short", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }); let candidate = new Date(Math.floor(after.getTime() / 60_000) * 60_000 + 60_000); for (let index = 0; index < 8 * 24 * 60; index += 1, candidate = new Date(candidate.getTime() + 60_000)) { const parts = Object.fromEntries(formatter.formatToParts(candidate).map((part) => [part.type, part.value])); if (Number(parts.hour) === hour && Number(parts.minute) === minute && (definition.schedule.days === "daily" || !["Sat", "Sun"].includes(parts.weekday ?? ""))) return candidate.toISOString(); } throw new ValidationError("cannot calculate next automation schedule"); }
}
