import { randomUUID } from "node:crypto";
import { collaborationPlanBasis, collaborationPlanDigest, collaborationRoles, type AgentAssignment, type Collaboration, type CollaborationLimits, type CollaborationPlanSnapshot, type CollaborationRole } from "./collaboration.js";
import type { CapabilityContext, DelegationRequest } from "./collaboration-bridge.js";
import { PolicyDenied, ValidationError } from "./errors.js";
import { utcNow } from "./models.js";
import type { Workspace } from "./storage.js";
import type { Task } from "./tasks.js";

interface CollaborationWorkspace { id: string; kind: "local" | "virtual"; rootPath?: string }
interface CollaborationDependencies { task(id: string): Task; workspace(id: string): CollaborationWorkspace; agentIds(): string[]; harnessSnapshotDigest(taskId: string): string; resolveBaseCommit(workspaceId: string, revision: string): string }
export interface CreateCollaborationInput { taskId: string; title: string; objective: string; createdBy: string; limits?: Partial<CollaborationLimits> }
export interface CollaborationPlanInput { allowedAgentIds: string[]; allowedRoles: CollaborationRole[]; baseRevision?: string; allowReadOnlySharedSnapshot?: boolean; allowAgentDelegation?: boolean }
export interface HumanAssignmentInput { agentId: string; role: CollaborationRole; mode: "read-only" | "write"; objective: string; acceptanceCriteria: string[]; dependencyIds?: string[]; actor: string }
export interface CollaborationDetail { collaboration: Collaboration; plan?: CollaborationPlanSnapshot; assignments: AgentAssignment[] }

const identifier = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;
const defaults: CollaborationLimits = { maxAssignments: 8, maxDepth: 2, maxParallel: 3, maxMessages: 100, timeoutMinutes: 60 };
function id(value: unknown, label: string): string { if (typeof value !== "string" || !identifier.test(value)) throw new ValidationError(`${label} contains unsupported characters`); return value; }
function text(value: unknown, label: string, max = 4_096): string { if (typeof value !== "string" || !value.trim()) throw new ValidationError(`${label} is required`); const normalized = value.trim(); if (normalized.includes("\0") || Buffer.byteLength(normalized) > max) throw new ValidationError(`${label} exceeds its limit or contains unsupported characters`); return normalized; }
function uniqueIds(value: unknown, label: string): string[] { if (!Array.isArray(value) || !value.length) throw new ValidationError(`${label} requires at least one value`); const result = value.map((item) => id(item, label)); if (new Set(result).size !== result.length) throw new ValidationError(`${label} must not contain duplicates`); return result; }
function criteria(value: unknown): string[] { if (!Array.isArray(value) || !value.length || value.length > 20) throw new ValidationError("Assignment requires 1-20 acceptance criteria"); const result = value.map((item) => text(item, "acceptance criterion", 2_048)); if (new Set(result).size !== result.length) throw new ValidationError("Assignment acceptance criteria must not contain duplicates"); return result; }
function bounded(value: unknown, fallback: number, min: number, max: number, label: string): number { const result = value === undefined ? fallback : Number(value); if (!Number.isInteger(result) || result < min || result > max) throw new ValidationError(`${label} must be between ${min} and ${max}`); return result; }

export class CollaborationService {
  constructor(readonly storage: Workspace, private readonly dependencies: CollaborationDependencies) {}

  create(input: CreateCollaborationInput): Collaboration {
    const task = this.dependencies.task(id(input.taskId, "task id")); if (!task.workspaceId) throw new ValidationError("Collaboration requires a Task Workspace"); const workspace = this.dependencies.workspace(task.workspaceId); if (workspace.kind !== "local" || !workspace.rootPath) throw new ValidationError("Collaboration requires a local Workspace");
    const limits: CollaborationLimits = { maxAssignments: bounded(input.limits?.maxAssignments, defaults.maxAssignments, 1, 32, "maxAssignments"), maxDepth: bounded(input.limits?.maxDepth, defaults.maxDepth, 0, 5, "maxDepth"), maxParallel: bounded(input.limits?.maxParallel, defaults.maxParallel, 1, 8, "maxParallel"), maxMessages: bounded(input.limits?.maxMessages, defaults.maxMessages, 1, 1_000, "maxMessages"), timeoutMinutes: bounded(input.limits?.timeoutMinutes, defaults.timeoutMinutes, 1, 120, "timeoutMinutes"), ...(input.limits?.maxTokens !== undefined ? { maxTokens: bounded(input.limits.maxTokens, 0, 1, 1_000_000_000, "maxTokens") } : {}) };
    const now = utcNow(); const collaboration: Collaboration = { schemaVersion: 1, id: `collaboration-${randomUUID().replaceAll("-", "")}`, workspaceId: task.workspaceId, changeId: task.changeId, taskId: task.id, title: text(input.title, "Collaboration title", 512), objective: text(input.objective, "Collaboration objective", 16_384), status: "draft", limits, usage: { assignments: 0, runningAssignments: 0, messages: 0, tokens: 0 }, createdBy: text(input.createdBy, "createdBy", 256), createdAt: now, updatedAt: now }; this.storage.saveCollaboration(collaboration); return collaboration;
  }

  list(taskId?: string): Collaboration[] { return this.storage.listCollaborations().filter((item) => !taskId || item.taskId === taskId); }
  detail(collaborationId: string): CollaborationDetail { const collaboration = this.storage.getCollaboration(id(collaborationId, "collaboration id")); const plan = collaboration.planSnapshotId ? this.storage.getCollaborationPlanSnapshot(collaboration.planSnapshotId) : undefined; return { collaboration, ...(plan ? { plan } : {}), assignments: this.assignments(collaboration.id) }; }
  assignments(collaborationId: string): AgentAssignment[] { return this.storage.listAgentAssignments().filter((item) => item.collaborationId === id(collaborationId, "collaboration id")); }
  currentPlan(collaborationId: string): CollaborationPlanSnapshot { return this.assertPlanCurrent(this.storage.getCollaboration(id(collaborationId, "collaboration id"))); }

  previewPlan(collaborationId: string, input: CollaborationPlanInput): CollaborationPlanSnapshot {
    const collaboration = this.storage.getCollaboration(id(collaborationId, "collaboration id")); if (!["draft", "awaiting_approval"].includes(collaboration.status)) throw new ValidationError("only a draft Collaboration can preview a plan"); const known = new Set(this.dependencies.agentIds()); const allowedAgentIds = uniqueIds(input.allowedAgentIds, "allowedAgentIds"); if (allowedAgentIds.some((agentId) => !known.has(agentId))) throw new ValidationError("Collaboration plan contains an unknown Agent");
    if (!Array.isArray(input.allowedRoles) || !input.allowedRoles.length || input.allowedRoles.some((role) => !collaborationRoles.includes(role))) throw new ValidationError("Collaboration plan requires known roles"); const allowedRoles = [...new Set(input.allowedRoles)]; const baseRevision = text(input.baseRevision ?? "HEAD", "baseRevision", 256); if (baseRevision.startsWith("-")) throw new ValidationError("baseRevision cannot start with an option prefix"); const baseCommit = this.dependencies.resolveBaseCommit(collaboration.workspaceId, baseRevision); const createdAt = utcNow(); const basis = collaborationPlanBasis({ collaborationId: collaboration.id, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, allowedAgentIds, allowedRoles, limits: collaboration.limits, worktreePolicy: { writersRequireIsolatedWorktree: true as const, allowReadOnlySharedSnapshot: input.allowReadOnlySharedSnapshot !== false, baseRevision, baseCommit, autoMerge: false as const, autoPush: false as const }, delegationPolicy: { mode: "plan-bounded" as const, allowAgentDelegation: input.allowAgentDelegation !== false, requireAcceptanceCriteria: true as const, requireKnownAgent: true as const }, harnessRuleSnapshotDigest: this.dependencies.harnessSnapshotDigest(collaboration.taskId) });
    const plan: CollaborationPlanSnapshot = { schemaVersion: 1, id: `collaboration-plan-${randomUUID().replaceAll("-", "")}`, digest: collaborationPlanDigest(basis), ...basis, createdAt }; this.storage.saveCollaborationPlanSnapshot(plan); collaboration.status = "awaiting_approval"; collaboration.planSnapshotId = plan.id; collaboration.planDigest = plan.digest; collaboration.updatedAt = createdAt; this.storage.saveCollaboration(collaboration); return plan;
  }

  start(collaborationId: string, input: { approved: boolean; approvedPlanDigest: string }): Collaboration {
    if (!input.approved) throw new PolicyDenied("Collaboration start requires explicit human approval"); const collaboration = this.storage.getCollaboration(id(collaborationId, "collaboration id")); if (collaboration.status !== "awaiting_approval" || !collaboration.planSnapshotId || !collaboration.planDigest) throw new ValidationError("Collaboration has no plan awaiting approval"); if (input.approvedPlanDigest !== collaboration.planDigest) throw new PolicyDenied("Collaboration approval does not match the current plan snapshot"); this.assertPlanCurrent(collaboration); collaboration.status = "running"; collaboration.startedAt = utcNow(); collaboration.updatedAt = collaboration.startedAt; this.storage.saveCollaboration(collaboration); return collaboration;
  }

  addAssignment(collaborationId: string, input: HumanAssignmentInput): AgentAssignment {
    const collaboration = this.running(collaborationId); const plan = this.assertPlanCurrent(collaboration); if (this.assignments(collaboration.id).length >= plan.limits.maxAssignments) throw new PolicyDenied("Collaboration Assignment limit reached"); const proposal = this.proposal(collaboration, { agentId: input.agentId, role: input.role, mode: input.mode, objective: input.objective, acceptanceCriteria: input.acceptanceCriteria, dependencyIds: input.dependencyIds ?? [] }, { kind: "human", actor: text(input.actor, "actor", 256) }, 0); const violations = this.planViolations(plan, proposal, false); if (violations.length) throw new PolicyDenied(`Assignment exceeds approved Collaboration plan: ${violations.join(", ")}`); proposal.status = "ready"; return this.persistAssignment(collaboration, proposal);
  }

  delegate(context: CapabilityContext, input: DelegationRequest): AgentAssignment {
    const parent = context.assignment; const collaboration = this.running(parent.collaborationId); const plan = this.assertPlanCurrent(collaboration); if (parent.agentRunId !== context.capability.runId) throw new PolicyDenied("delegation capability does not match the active parent Run");
    const proposal = this.proposal(collaboration, input, { kind: "agent", agentId: parent.agentId, runId: context.capability.runId }, parent.depth + 1, parent.id); if (proposal.depth > plan.limits.maxDepth) throw new PolicyDenied("Collaboration delegation depth limit reached"); if (this.assignments(collaboration.id).length >= plan.limits.maxAssignments) throw new PolicyDenied("Collaboration Assignment limit reached");
    const violations = this.planViolations(plan, proposal, true); proposal.status = violations.length ? "awaiting_approval" : "ready"; if (violations.length) proposal.policyViolations = violations; return this.persistAssignment(collaboration, proposal);
  }

  approveAssignment(assignmentId: string, input: { approved: boolean; actor: string }): AgentAssignment {
    const assignment = this.storage.getAgentAssignment(id(assignmentId, "assignment id")); if (assignment.status !== "awaiting_approval") throw new ValidationError("Assignment is not awaiting approval"); if (!input.approved) { assignment.status = "cancelled"; assignment.completedAt = utcNow(); this.storage.saveAgentAssignment(assignment); return assignment; }
    text(input.actor, "actor", 256); const collaboration = this.running(assignment.collaborationId); const plan = this.assertPlanCurrent(collaboration); const violations = this.planViolations(plan, assignment, false); if (violations.length) throw new PolicyDenied(`Assignment requires a revised Collaboration plan: ${violations.join(", ")}`); assignment.status = "ready"; delete assignment.policyViolations; this.storage.saveAgentAssignment(assignment); return assignment;
  }

  private running(collaborationId: string): Collaboration { const collaboration = this.storage.getCollaboration(id(collaborationId, "collaboration id")); if (collaboration.status !== "running") throw new PolicyDenied("Collaboration is not running"); return collaboration; }
  private assertPlanCurrent(collaboration: Collaboration): CollaborationPlanSnapshot { if (!collaboration.planSnapshotId || !collaboration.planDigest) throw new ValidationError("Collaboration has no approved plan"); const plan = this.storage.getCollaborationPlanSnapshot(collaboration.planSnapshotId); if (plan.schemaVersion !== 1 || plan.collaborationId !== collaboration.id || plan.digest !== collaboration.planDigest || collaborationPlanDigest(plan) !== plan.digest) throw new PolicyDenied("Collaboration plan digest no longer matches"); if (plan.harnessRuleSnapshotDigest !== this.dependencies.harnessSnapshotDigest(collaboration.taskId)) throw new PolicyDenied("Harness rules changed after Collaboration approval"); return plan; }
  private proposal(collaboration: Collaboration, input: Pick<DelegationRequest, "agentId" | "role" | "mode" | "objective" | "acceptanceCriteria" | "dependencyIds">, proposedBy: AgentAssignment["proposedBy"], depth: number, parentAssignmentId?: string): AgentAssignment {
    const knownAgents = new Set(this.dependencies.agentIds()); const agentId = id(input.agentId, "Agent id"); if (!knownAgents.has(agentId)) throw new ValidationError("delegation targets an unknown Agent"); if (!collaborationRoles.includes(input.role as CollaborationRole)) throw new ValidationError("delegation uses an unknown role"); if (input.mode !== "read-only" && input.mode !== "write") throw new ValidationError("invalid Assignment mode"); const dependencyIds = input.dependencyIds === undefined ? [] : Array.isArray(input.dependencyIds) ? input.dependencyIds.map((item) => id(item, "dependency id")) : (() => { throw new ValidationError("dependencyIds must be an array"); })(); if (new Set(dependencyIds).size !== dependencyIds.length) throw new ValidationError("Assignment dependencies must not contain duplicates"); const existing = new Map(this.assignments(collaboration.id).map((item) => [item.id, item])); if (dependencyIds.some((dependencyId) => !existing.has(dependencyId))) throw new ValidationError("Assignment dependency is outside the Collaboration");
    return { schemaVersion: 1, id: `assignment-${randomUUID().replaceAll("-", "")}`, collaborationId: collaboration.id, ...(parentAssignmentId ? { parentAssignmentId } : {}), depth, workspaceId: collaboration.workspaceId, changeId: collaboration.changeId, taskId: collaboration.taskId, agentId, role: input.role as CollaborationRole, objective: text(input.objective, "Assignment objective", 16_384), acceptanceCriteria: criteria(input.acceptanceCriteria), mode: input.mode, dependencyIds, status: "proposed", proposedBy, createdAt: utcNow() };
  }
  private planViolations(plan: CollaborationPlanSnapshot, assignment: AgentAssignment, agentDelegation: boolean): string[] { const violations: string[] = []; if (agentDelegation && !plan.delegationPolicy.allowAgentDelegation) violations.push("agent delegation is disabled"); if (!plan.allowedAgentIds.includes(assignment.agentId)) violations.push(`Agent ${assignment.agentId} is not allowed`); if (!plan.allowedRoles.includes(assignment.role)) violations.push(`role ${assignment.role} is not allowed`); return violations; }
  private persistAssignment(collaboration: Collaboration, assignment: AgentAssignment): AgentAssignment { this.storage.saveAgentAssignment(assignment); collaboration.usage.assignments = this.assignments(collaboration.id).length; collaboration.updatedAt = utcNow(); if (!collaboration.rootAssignmentId && !assignment.parentAssignmentId) collaboration.rootAssignmentId = assignment.id; this.storage.saveCollaboration(collaboration); return assignment; }
}
