import type { SourceControlAdapter } from "./adapters.js";
import { AdapterError, ValidationError } from "./errors.js";
import { isRecord, type JsonObject, type JsonValue } from "./models.js";
import { SourceControlIntegrationManager } from "./source-control-config.js";
import type { Workspace } from "./storage.js";
import type { RemoteWorkspaceBrowser, WorkspaceChangeRequest, WorkspaceComment, WorkspaceCommit, WorkspaceCommitCheck, WorkspaceFile, WorkspaceIssue, WorkspaceRef } from "./workspace-hub.js";

export const gitHubAuthTypes = ["bearer", "token", "none"] as const;
export type GitHubAuthType = typeof gitHubAuthTypes[number];
export interface GitHubHttpConfig { schemaVersion: 1; baseUrl: string; apiPath: string; authType: GitHubAuthType; credential?: string; repository?: string; apiVersion: string; timeoutSeconds: number; savedAt: string; lastTestedAt: string }
export interface GitHubConfigInput { baseUrl: string; apiPath?: string; authType: GitHubAuthType; credential?: string; repository?: string; apiVersion?: string; timeoutSeconds?: number }
export interface GitHubConfigSummary { configured: boolean; active: boolean; source: "none" | "workspace"; baseUrl?: string; apiPath?: string; authType?: GitHubAuthType; credentialConfigured: boolean; repository?: string; apiVersion?: string; timeoutSeconds?: number; savedAt?: string; lastTestedAt?: string }

function required(value: unknown, key: string): string { if (typeof value !== "string" || !value.trim()) throw new ValidationError(`${key} is required`); return value.trim(); }
function optional(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
function normalizeBaseUrl(value: unknown): string { let url: URL; try { url = new URL(required(value, "baseUrl")); } catch { throw new ValidationError("baseUrl must be a valid absolute URL"); } if (url.username || url.password) throw new ValidationError("baseUrl cannot contain credentials"); if (url.search || url.hash) throw new ValidationError("baseUrl cannot contain query parameters or fragments"); const loopback = ["localhost", "127.0.0.1", "::1"].includes(url.hostname.replace(/^\[|\]$/g, "")); if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback)) throw new ValidationError("baseUrl must use HTTPS unless it targets loopback"); return url.toString().replace(/\/$/, ""); }
function normalizeApiPath(value: unknown): string { const path = optional(value) ?? ""; if (path && (!/^\/[A-Za-z0-9/_-]*$/.test(path) || path.includes("..") || path.endsWith("/"))) throw new ValidationError("apiPath must be empty or an absolute path without a trailing slash"); return path; }
function normalizeAuthType(value: unknown): GitHubAuthType { if (typeof value !== "string" || !gitHubAuthTypes.includes(value as GitHubAuthType)) throw new ValidationError("invalid GitHub auth type"); return value as GitHubAuthType; }
function normalizeTimeout(value: unknown): number { const result = value === undefined ? 15 : Number(value); if (!Number.isInteger(result) || result < 1 || result > 60) throw new ValidationError("timeoutSeconds must be between 1 and 60"); return result; }
function normalizeRepository(value: unknown): string | undefined { const repository = optional(value); if (repository && !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)) throw new ValidationError("repository must use owner/name format"); return repository; }
function stringField(value: JsonObject, key: string): string { return required(value[key], key); }

export class GitHubSourceControlAdapter implements SourceControlAdapter, RemoteWorkspaceBrowser {
  constructor(readonly config: GitHubHttpConfig) {}
  async testConnection(): Promise<JsonObject> { return this.config.repository ? await this.getRepository(this.config.repository) : await this.object("/meta", { method: "GET" }); }
  async getRepository(id: string): Promise<JsonObject> { return await this.object(`/repos/${this.repository(id)}`, { method: "GET" }); }
  async createBranch(id: string, name: string, revision: string): Promise<JsonObject> { const repository = this.repository(id); const sha = await this.resolveRevision(repository, revision); return await this.object(`/repos/${repository}/git/refs`, { method: "POST", body: { ref: `refs/heads/${required(name, "name")}`, sha } }); }
  async createChangeRequest(request: JsonObject): Promise<JsonObject> { const repository = this.repository(optional(request.repositoryId) ?? this.config.repository); return await this.object(`/repos/${repository}/pulls`, { method: "POST", body: { head: stringField(request, "sourceBranch"), base: stringField(request, "targetBranch"), title: stringField(request, "title"), ...(optional(request.description) ? { body: optional(request.description) } : {}) } }); }
  async publishCommitStatus(status: JsonObject): Promise<JsonObject> { const repository = this.repository(optional(status.repositoryId) ?? this.config.repository); return await this.object(`/repos/${repository}/statuses/${encodeURIComponent(stringField(status, "sha"))}`, { method: "POST", body: { state: stringField(status, "state"), ...(optional(status.context) ? { context: optional(status.context) } : {}), ...(optional(status.targetUrl) ? { target_url: optional(status.targetUrl) } : {}), ...(optional(status.description) ? { description: optional(status.description) } : {}) } }); }
  async listTree(id: string, path: string, ref?: string): Promise<JsonObject[]> { const suffix = ref ? `?ref=${encodeURIComponent(ref)}` : ""; const encoded = path.split("/").filter(Boolean).map(encodeURIComponent).join("/"); const value = await this.json(`/repos/${this.repository(id)}/contents${encoded ? `/${encoded}` : ""}${suffix}`, { method: "GET" }); if (Array.isArray(value) && value.every(isRecord)) return value as JsonObject[]; if (isRecord(value)) return [value as JsonObject]; throw new AdapterError("GitHub tree response is invalid"); }
  async getFile(id: string, path: string, ref?: string): Promise<WorkspaceFile> { const suffix = ref ? `?ref=${encodeURIComponent(ref)}` : ""; const value = await this.object(`/repos/${this.repository(id)}/contents/${path.split("/").map(encodeURIComponent).join("/")}${suffix}`, { method: "GET" }); if (typeof value.content !== "string" || value.encoding !== "base64") throw new AdapterError("GitHub file response is invalid"); const bytes = Buffer.from(value.content.replaceAll("\n", ""), "base64"); if (bytes.length > 1_048_576 || bytes.includes(0)) throw new AdapterError("GitHub file cannot be previewed"); return { path, content: bytes.toString("utf8"), encoding: "utf8", size: bytes.length, ...(ref ? { ref } : {}) }; }
  async listRefs(id: string): Promise<WorkspaceRef[]> { const repository = this.repository(id); const [branches, tags] = await Promise.all([this.array(`/repos/${repository}/branches?per_page=100`), this.array(`/repos/${repository}/tags?per_page=100`)]); return [...branches.map((item) => ({ name: String(item.name ?? ""), type: "branch" as const, ...(isRecord(item.commit) && typeof item.commit.sha === "string" ? { sha: item.commit.sha } : {}) })), ...tags.map((item) => ({ name: String(item.name ?? ""), type: "tag" as const, ...(isRecord(item.commit) && typeof item.commit.sha === "string" ? { sha: item.commit.sha } : {}) }))]; }
  async listCommits(id: string, ref?: string): Promise<WorkspaceCommit[]> { const query = ref ? `?per_page=50&sha=${encodeURIComponent(ref)}` : "?per_page=50"; return (await this.array(`/repos/${this.repository(id)}/commits${query}`)).map((item) => { const commit = isRecord(item.commit) ? item.commit : {}; const author = isRecord(commit.author) ? commit.author : {}; return { sha: String(item.sha ?? ""), shortSha: String(item.sha ?? "").slice(0, 8), subject: String(commit.message ?? "").split("\n")[0] ?? "", author: String(author.name ?? ""), authoredAt: String(author.date ?? "") }; }); }
  async inspectCommit(id: string, sha: string): Promise<WorkspaceCommitCheck> { const repository = this.repository(id); const encoded = encodeURIComponent(sha); const [commit, statuses, checkRuns] = await Promise.all([this.object(`/repos/${repository}/commits/${encoded}`, { method: "GET" }), this.array(`/repos/${repository}/commits/${encoded}/statuses?per_page=100`), this.object(`/repos/${repository}/commits/${encoded}/check-runs?per_page=100`, { method: "GET" })]); const files = Array.isArray(commit.files) ? commit.files.flatMap((file) => isRecord(file) ? [String(file.filename ?? "")] : []) : []; const modern = Array.isArray(checkRuns.check_runs) ? checkRuns.check_runs.flatMap((check) => isRecord(check) ? [check as JsonObject] : []) : []; const failed = statuses.some((status) => status.state === "failure" || status.state === "error") || modern.some((check) => ["failure", "cancelled", "timed_out", "action_required"].includes(String(check.conclusion ?? ""))); return { sha: String(commit.sha ?? sha), valid: !failed, signature: isRecord(commit.commit) && isRecord(commit.commit.verification) ? String(commit.commit.verification.verified === true ? "verified" : commit.commit.verification.reason ?? "unverified") : "unknown", whitespaceErrors: [], changedFiles: files, checks: [...statuses, ...modern] }; }
  async listIssues(id: string): Promise<WorkspaceIssue[]> { return (await this.array(`/repos/${this.repository(id)}/issues?state=all&per_page=100`)).filter((item) => !isRecord(item.pull_request)).map((item) => this.issue(item)); }
  async listChangeRequests(id: string): Promise<WorkspaceChangeRequest[]> { return (await this.array(`/repos/${this.repository(id)}/pulls?state=all&per_page=100`)).map((item) => ({ ...this.issue(item), ...(isRecord(item.head) && typeof item.head.ref === "string" ? { sourceBranch: item.head.ref } : {}), ...(isRecord(item.base) && typeof item.base.ref === "string" ? { targetBranch: item.base.ref } : {}), draft: item.draft === true })); }
  async listComments(id: string, kind: "issue" | "change-request", number: number): Promise<WorkspaceComment[]> { const repository = this.repository(id); const comments = kind === "change-request" ? (await Promise.all([this.array(`/repos/${repository}/issues/${number}/comments?per_page=100`), this.array(`/repos/${repository}/pulls/${number}/comments?per_page=100`)])).flat() : await this.array(`/repos/${repository}/issues/${number}/comments?per_page=100`); return comments.map((item) => ({ id: String(item.id ?? ""), ...(isRecord(item.user) && typeof item.user.login === "string" ? { author: item.user.login } : {}), body: String(item.body ?? ""), ...(typeof item.created_at === "string" ? { createdAt: item.created_at } : {}), ...(typeof item.updated_at === "string" ? { updatedAt: item.updated_at } : {}) })).sort((a, b) => (a.createdAt ?? "").localeCompare(b.createdAt ?? "")); }
  private issue(item: JsonObject): WorkspaceIssue { return { id: String(item.id ?? item.number ?? ""), number: Number(item.number ?? 0), title: String(item.title ?? ""), state: String(item.state ?? "unknown"), ...(isRecord(item.user) && typeof item.user.login === "string" ? { author: item.user.login } : {}), assignees: Array.isArray(item.assignees) ? item.assignees.flatMap((user) => isRecord(user) ? [String(user.login ?? "")] : []) : [], labels: Array.isArray(item.labels) ? item.labels.map((label) => isRecord(label) ? String(label.name ?? "") : String(label)) : [], ...(typeof item.updated_at === "string" ? { updatedAt: item.updated_at } : {}), ...(typeof item.html_url === "string" ? { url: item.html_url } : {}) }; }
  private async resolveRevision(repository: string, revision: string): Promise<string> { const value = required(revision, "revision"); if (/^[a-f0-9]{40}$/i.test(value)) return value; const ref = await this.object(`/repos/${repository}/git/ref/heads/${encodeURIComponent(value)}`, { method: "GET" }); if (!isRecord(ref.object) || typeof ref.object.sha !== "string") throw new AdapterError("GitHub reference response is invalid"); return ref.object.sha; }
  private repository(value: unknown): string { const repository = normalizeRepository(value); if (!repository) throw new ValidationError("repositoryId is required"); return repository.split("/").map(encodeURIComponent).join("/"); }
  private async object(path: string, input: { method: "GET" | "POST"; body?: JsonObject }): Promise<JsonObject> { const value = await this.json(path, input); if (!isRecord(value)) throw new AdapterError("GitHub returned an invalid object"); return value as JsonObject; }
  private async array(path: string): Promise<JsonObject[]> { const value = await this.json(path, { method: "GET" }); if (!Array.isArray(value) || !value.every(isRecord)) throw new AdapterError("GitHub returned an invalid list"); return value as JsonObject[]; }
  private async json(path: string, input: { method: "GET" | "POST"; body?: JsonObject }): Promise<unknown> { const headers = new Headers({ accept: "application/vnd.github+json", "x-github-api-version": this.config.apiVersion }); if (input.body) headers.set("content-type", "application/json"); const credential = this.config.credential; if (this.config.authType === "bearer" && credential) headers.set("authorization", `Bearer ${credential}`); if (this.config.authType === "token" && credential) headers.set("authorization", `token ${credential}`); let response: Response; try { response = await fetch(`${this.config.baseUrl}${this.config.apiPath}${path}`, { method: input.method, headers, ...(input.body ? { body: JSON.stringify(input.body) } : {}), redirect: "error", signal: AbortSignal.timeout(this.config.timeoutSeconds * 1000) }); } catch (error) { throw new AdapterError(`GitHub request failed: ${error instanceof Error ? error.message : String(error)}`); } const length = Number(response.headers.get("content-length") ?? 0); if (length > 1_048_576) throw new AdapterError("GitHub response exceeds 1 MB"); const payload = await this.responseText(response); if (!response.ok) throw new AdapterError(`GitHub returned HTTP ${response.status}`); try { return JSON.parse(payload) as unknown; } catch { throw new AdapterError("GitHub response is not valid JSON"); } }
  private async responseText(response: Response): Promise<string> { if (!response.body) return ""; const reader = response.body.getReader(); const decoder = new TextDecoder(); let size = 0; let result = ""; try { while (true) { const chunk = await reader.read(); if (chunk.done) break; size += chunk.value.byteLength; if (size > 1_048_576) { await reader.cancel(); throw new AdapterError("GitHub response exceeds 1 MB"); } result += decoder.decode(chunk.value, { stream: true }); } return result + decoder.decode(); } finally { reader.releaseLock(); } }
}

export class GitHubIntegrationManager {
  constructor(private readonly workspace: Workspace, private readonly sourceControl: SourceControlIntegrationManager) { this.restore(); }
  summary(): GitHubConfigSummary { if (!this.workspace.integrationExists("github")) return { configured: false, active: false, source: "none", credentialConfigured: false }; const config = this.read(); return { configured: true, active: this.sourceControl.isActive("github"), source: "workspace", baseUrl: config.baseUrl, apiPath: config.apiPath, authType: config.authType, credentialConfigured: Boolean(config.credential), ...(config.repository ? { repository: config.repository } : {}), apiVersion: config.apiVersion, timeoutSeconds: config.timeoutSeconds, savedAt: config.savedAt, lastTestedAt: config.lastTestedAt }; }
  async test(input: GitHubConfigInput): Promise<{ status: "connected"; testedAt: string }> { const config = this.normalize(input, false); await new GitHubSourceControlAdapter(config).testConnection(); return { status: "connected", testedAt: config.lastTestedAt }; }
  async save(input: GitHubConfigInput): Promise<GitHubConfigSummary> { const config = this.normalize(input, true); const adapter = new GitHubSourceControlAdapter(config); await adapter.testConnection(); this.workspace.saveIntegrationConfig("github", config as unknown as JsonValue); this.sourceControl.activate("github", adapter); return this.summary(); }
  activate(): GitHubConfigSummary { if (!this.workspace.integrationExists("github")) throw new ValidationError("GitHub Adapter is not configured"); this.sourceControl.activate("github", new GitHubSourceControlAdapter(this.read())); return this.summary(); }
  remove(): GitHubConfigSummary { this.workspace.removeIntegrationConfig("github"); this.sourceControl.remove("github"); return this.summary(); }
  browser(): GitHubSourceControlAdapter | undefined { return this.workspace.integrationExists("github") ? new GitHubSourceControlAdapter(this.read()) : undefined; }
  private restore(): void { if (this.sourceControl.isActive("github")) { if (!this.workspace.integrationExists("github")) throw new ValidationError("active GitHub Adapter configuration is missing"); this.sourceControl.activate("github", new GitHubSourceControlAdapter(this.read()), false); } }
  private read(): GitHubHttpConfig { const raw = this.workspace.getIntegrationConfig("github"); if (!isRecord(raw)) throw new ValidationError("invalid saved GitHub configuration"); return this.normalize(raw as unknown as GitHubConfigInput, true, true); }
  private normalize(input: GitHubConfigInput, saving: boolean, preserveDates = false): GitHubHttpConfig { const existing = this.workspace.integrationExists("github") && !preserveDates ? this.read() : undefined; const type = normalizeAuthType(input.authType); const credential = optional(input.credential) ?? (existing?.authType === type ? existing.credential : undefined); if (type !== "none" && !credential) throw new ValidationError("credential is required for the selected authentication type"); const now = new Date().toISOString(); const raw = input as GitHubConfigInput & Partial<GitHubHttpConfig>; return { schemaVersion: 1, baseUrl: normalizeBaseUrl(input.baseUrl), apiPath: normalizeApiPath(input.apiPath), authType: type, ...(credential ? { credential } : {}), ...(normalizeRepository(input.repository) ? { repository: normalizeRepository(input.repository) } : {}), apiVersion: optional(input.apiVersion) ?? "2022-11-28", timeoutSeconds: normalizeTimeout(input.timeoutSeconds), savedAt: preserveDates && typeof raw.savedAt === "string" ? raw.savedAt : saving ? now : existing?.savedAt ?? now, lastTestedAt: preserveDates && typeof raw.lastTestedAt === "string" ? raw.lastTestedAt : now }; }
}
