import type { SourceControlAdapter } from "./adapters.js";
import { AdapterError, ValidationError } from "./errors.js";
import { isRecord, type JsonObject, type JsonValue } from "./models.js";
import { SourceControlIntegrationManager } from "./source-control-config.js";
import type { Workspace } from "./storage.js";

export const gitLabAuthTypes = ["private-token", "bearer", "job-token", "none"] as const;
export type GitLabAuthType = typeof gitLabAuthTypes[number];
export interface GitLabHttpConfig { schemaVersion: 1; baseUrl: string; apiPath: string; authType: GitLabAuthType; credential?: string; projectId?: string; timeoutSeconds: number; savedAt: string; lastTestedAt: string }
export interface GitLabConfigInput { baseUrl: string; apiPath?: string; authType: GitLabAuthType; credential?: string; projectId?: string; timeoutSeconds?: number }
export interface GitLabConfigSummary { configured: boolean; active: boolean; source: "none" | "workspace"; baseUrl?: string; apiPath?: string; authType?: GitLabAuthType; credentialConfigured: boolean; projectId?: string; timeoutSeconds?: number; savedAt?: string; lastTestedAt?: string }

function required(value: unknown, key: string): string { if (typeof value !== "string" || !value.trim()) throw new ValidationError(`${key} is required`); return value.trim(); }
function optional(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
function normalizeBaseUrl(value: unknown): string { let url: URL; try { url = new URL(required(value, "baseUrl")); } catch { throw new ValidationError("baseUrl must be a valid absolute URL"); } if (url.username || url.password) throw new ValidationError("baseUrl cannot contain credentials"); if (url.search || url.hash) throw new ValidationError("baseUrl cannot contain query parameters or fragments"); const loopback = ["localhost", "127.0.0.1", "::1"].includes(url.hostname.replace(/^\[|\]$/g, "")); if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback)) throw new ValidationError("baseUrl must use HTTPS unless it targets loopback"); return url.toString().replace(/\/$/, ""); }
function normalizeApiPath(value: unknown): string { const path = optional(value) ?? "/api/v4"; if (!/^\/[A-Za-z0-9/_-]*$/.test(path) || path.includes("..") || path.endsWith("/")) throw new ValidationError("apiPath must be an absolute path without a trailing slash"); return path; }
function normalizeAuthType(value: unknown): GitLabAuthType { if (typeof value !== "string" || !gitLabAuthTypes.includes(value as GitLabAuthType)) throw new ValidationError("invalid GitLab auth type"); return value as GitLabAuthType; }
function normalizeTimeout(value: unknown): number { const result = value === undefined ? 15 : Number(value); if (!Number.isInteger(result) || result < 1 || result > 60) throw new ValidationError("timeoutSeconds must be between 1 and 60"); return result; }
function stringField(value: JsonObject, key: string): string { return required(value[key], key); }

export class GitLabSourceControlAdapter implements SourceControlAdapter {
  constructor(readonly config: GitLabHttpConfig) {}
  async testConnection(): Promise<JsonObject> { return this.config.projectId ? await this.getRepository(this.config.projectId) : await this.object("/version", { method: "GET" }); }
  async getRepository(id: string): Promise<JsonObject> { return await this.object(`/projects/${encodeURIComponent(required(id, "repositoryId"))}`, { method: "GET" }); }
  async createBranch(id: string, name: string, revision: string): Promise<JsonObject> { return await this.object(`/projects/${encodeURIComponent(required(id, "repositoryId"))}/repository/branches`, { method: "POST", body: { branch: required(name, "name"), ref: required(revision, "revision") } }); }
  async createChangeRequest(request: JsonObject): Promise<JsonObject> { const project = optional(request.repositoryId) ?? optional(request.projectId) ?? this.config.projectId; if (!project) throw new ValidationError("repositoryId is required"); return await this.object(`/projects/${encodeURIComponent(project)}/merge_requests`, { method: "POST", body: { source_branch: stringField(request, "sourceBranch"), target_branch: stringField(request, "targetBranch"), title: stringField(request, "title"), ...(optional(request.description) ? { description: optional(request.description) } : {}) } }); }
  async publishCommitStatus(status: JsonObject): Promise<JsonObject> { const project = optional(status.repositoryId) ?? optional(status.projectId) ?? this.config.projectId; if (!project) throw new ValidationError("repositoryId is required"); const sha = stringField(status, "sha"); return await this.object(`/projects/${encodeURIComponent(project)}/statuses/${encodeURIComponent(sha)}`, { method: "POST", body: { state: stringField(status, "state"), ...(optional(status.context) ? { name: optional(status.context) } : {}), ...(optional(status.targetUrl) ? { target_url: optional(status.targetUrl) } : {}), ...(optional(status.description) ? { description: optional(status.description) } : {}) } }); }
  private async object(path: string, input: { method: "GET" | "POST"; body?: JsonObject }): Promise<JsonObject> { const headers = new Headers({ accept: "application/json" }); if (input.body) headers.set("content-type", "application/json"); const credential = this.config.credential; if (this.config.authType === "private-token" && credential) headers.set("private-token", credential); if (this.config.authType === "bearer" && credential) headers.set("authorization", `Bearer ${credential}`); if (this.config.authType === "job-token" && credential) headers.set("job-token", credential); let response: Response; try { response = await fetch(`${this.config.baseUrl}${this.config.apiPath}${path}`, { method: input.method, headers, ...(input.body ? { body: JSON.stringify(input.body) } : {}), redirect: "error", signal: AbortSignal.timeout(this.config.timeoutSeconds * 1000) }); } catch (error) { throw new AdapterError(`GitLab request failed: ${error instanceof Error ? error.message : String(error)}`); } const length = Number(response.headers.get("content-length") ?? 0); if (length > 1_048_576) throw new AdapterError("GitLab response exceeds 1 MB"); const payload = await this.responseText(response); if (!response.ok) throw new AdapterError(`GitLab returned HTTP ${response.status}`); let value: unknown; try { value = JSON.parse(payload) as unknown; } catch { throw new AdapterError("GitLab response is not valid JSON"); } if (!isRecord(value)) throw new AdapterError("GitLab returned an invalid object"); return value as JsonObject; }
  private async responseText(response: Response): Promise<string> { if (!response.body) return ""; const reader = response.body.getReader(); const decoder = new TextDecoder(); let size = 0; let result = ""; try { while (true) { const chunk = await reader.read(); if (chunk.done) break; size += chunk.value.byteLength; if (size > 1_048_576) { await reader.cancel(); throw new AdapterError("GitLab response exceeds 1 MB"); } result += decoder.decode(chunk.value, { stream: true }); } return result + decoder.decode(); } finally { reader.releaseLock(); } }
}

export class GitLabIntegrationManager {
  constructor(private readonly workspace: Workspace, private readonly sourceControl: SourceControlIntegrationManager) { this.restore(); }
  summary(): GitLabConfigSummary { if (!this.workspace.integrationExists("gitlab")) return { configured: false, active: false, source: "none", credentialConfigured: false }; const config = this.read(); return { configured: true, active: this.sourceControl.isActive("gitlab"), source: "workspace", baseUrl: config.baseUrl, apiPath: config.apiPath, authType: config.authType, credentialConfigured: Boolean(config.credential), ...(config.projectId ? { projectId: config.projectId } : {}), timeoutSeconds: config.timeoutSeconds, savedAt: config.savedAt, lastTestedAt: config.lastTestedAt }; }
  async test(input: GitLabConfigInput): Promise<{ status: "connected"; testedAt: string }> { const config = this.normalize(input, false); await new GitLabSourceControlAdapter(config).testConnection(); return { status: "connected", testedAt: config.lastTestedAt }; }
  async save(input: GitLabConfigInput): Promise<GitLabConfigSummary> { const config = this.normalize(input, true); const adapter = new GitLabSourceControlAdapter(config); await adapter.testConnection(); this.workspace.saveIntegrationConfig("gitlab", config as unknown as JsonValue); this.sourceControl.activate("gitlab", adapter); return this.summary(); }
  activate(): GitLabConfigSummary { if (!this.workspace.integrationExists("gitlab")) throw new ValidationError("GitLab Adapter is not configured"); this.sourceControl.activate("gitlab", new GitLabSourceControlAdapter(this.read())); return this.summary(); }
  remove(): GitLabConfigSummary { this.workspace.removeIntegrationConfig("gitlab"); this.sourceControl.remove("gitlab"); return this.summary(); }
  private restore(): void { if (this.sourceControl.isActive("gitlab")) { if (!this.workspace.integrationExists("gitlab")) throw new ValidationError("active GitLab Adapter configuration is missing"); this.sourceControl.activate("gitlab", new GitLabSourceControlAdapter(this.read()), false); } }
  private read(): GitLabHttpConfig { const raw = this.workspace.getIntegrationConfig("gitlab"); if (!isRecord(raw)) throw new ValidationError("invalid saved GitLab configuration"); return this.normalize(raw as unknown as GitLabConfigInput, true, true); }
  private normalize(input: GitLabConfigInput, saving: boolean, preserveDates = false): GitLabHttpConfig { const existing = this.workspace.integrationExists("gitlab") && !preserveDates ? this.read() : undefined; const type = normalizeAuthType(input.authType); const credential = optional(input.credential) ?? (existing?.authType === type ? existing.credential : undefined); if (type !== "none" && !credential) throw new ValidationError("credential is required for the selected authentication type"); const now = new Date().toISOString(); const raw = input as GitLabConfigInput & Partial<GitLabHttpConfig>; return { schemaVersion: 1, baseUrl: normalizeBaseUrl(input.baseUrl), apiPath: normalizeApiPath(input.apiPath), authType: type, ...(credential ? { credential } : {}), ...(optional(input.projectId) ? { projectId: optional(input.projectId) } : {}), timeoutSeconds: normalizeTimeout(input.timeoutSeconds), savedAt: preserveDates && typeof raw.savedAt === "string" ? raw.savedAt : saving ? now : existing?.savedAt ?? now, lastTestedAt: preserveDates && typeof raw.lastTestedAt === "string" ? raw.lastTestedAt : now }; }
}
