import type { JiraAdapter, ToolBroker } from "./adapters.js";
import { AdapterError, ValidationError } from "./errors.js";
import { isRecord, type JsonObject, type JsonValue } from "./models.js";
import type { Workspace } from "./storage.js";

export const jiraAuthTypes = ["none", "bearer", "api-key", "basic"] as const;
export type JiraAuthType = typeof jiraAuthTypes[number];
export interface JiraHttpConfig { schemaVersion: 1; baseUrl: string; authType: JiraAuthType; credential?: string; apiKeyHeader: string; projectKey?: string; issueType?: string; timeoutSeconds: number; savedAt: string; lastTestedAt: string }
export interface JiraConfigInput { baseUrl: string; authType: JiraAuthType; credential?: string; apiKeyHeader?: string; projectKey?: string; issueType?: string; timeoutSeconds?: number }
export interface JiraConfigSummary { configured: boolean; source: "none" | "runtime" | "workspace"; baseUrl?: string; authType?: JiraAuthType; credentialConfigured: boolean; apiKeyHeader?: string; projectKey?: string; issueType?: string; timeoutSeconds?: number; savedAt?: string; lastTestedAt?: string }

const forbiddenHeaders = new Set(["authorization", "cookie", "host", "content-length", "connection", "transfer-encoding"]);
function required(value: unknown, key: string): string { if (typeof value !== "string" || !value.trim()) throw new ValidationError(`${key} is required`); return value.trim(); }
function optional(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
function normalizeBaseUrl(value: unknown): string { let url: URL; try { url = new URL(required(value, "baseUrl")); } catch { throw new ValidationError("baseUrl must be a valid absolute URL"); } if (url.username || url.password) throw new ValidationError("baseUrl cannot contain credentials"); if (url.search || url.hash) throw new ValidationError("baseUrl cannot contain query parameters or fragments"); const loopback = ["localhost", "127.0.0.1", "::1"].includes(url.hostname.replace(/^\[|\]$/g, "")); if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback)) throw new ValidationError("baseUrl must use HTTPS unless it targets loopback"); return url.toString().replace(/\/$/, ""); }
function normalizeHeader(value: unknown): string { const result = optional(value) ?? "X-API-Key"; if (!/^[A-Za-z0-9-]+$/.test(result) || forbiddenHeaders.has(result.toLowerCase())) throw new ValidationError("apiKeyHeader is not allowed"); return result; }
function normalizeTimeout(value: unknown): number { const result = value === undefined ? 15 : Number(value); if (!Number.isInteger(result) || result < 1 || result > 60) throw new ValidationError("timeoutSeconds must be between 1 and 60"); return result; }
function normalizeAuthType(value: unknown): JiraAuthType { if (typeof value !== "string" || !jiraAuthTypes.includes(value as JiraAuthType)) throw new ValidationError("invalid Jira auth type"); return value as JiraAuthType; }

export class HttpJiraAdapter implements JiraAdapter {
  constructor(readonly config: JiraHttpConfig) {}
  async testConnection(): Promise<JsonObject> { return await this.object("/health", { method: "GET" }); }
  async getIssue(key: string): Promise<JsonObject> { return await this.object(`/issues/${encodeURIComponent(required(key, "key"))}`, { method: "GET" }); }
  async createIssue(fields: JsonObject): Promise<JsonObject> { return await this.object("/issues", { method: "POST", body: { ...(this.config.projectKey ? { projectKey: this.config.projectKey } : {}), ...(this.config.issueType ? { issueType: this.config.issueType } : {}), ...fields } }); }
  async updateIssue(key: string, fields: JsonObject): Promise<JsonObject> { return await this.object(`/issues/${encodeURIComponent(required(key, "key"))}`, { method: "PATCH", body: fields }); }
  async transitionIssue(key: string, state: string): Promise<JsonObject> { return await this.object(`/issues/${encodeURIComponent(required(key, "key"))}/transitions`, { method: "POST", body: { state: required(state, "state") } }); }
  private async object(path: string, input: { method: "GET" | "POST" | "PATCH"; body?: JsonObject }): Promise<JsonObject> { const value = await this.value(path, input); if (!isRecord(value)) throw new AdapterError("Jira Gateway returned an invalid object"); return value as JsonObject; }
  private async value(path: string, input: { method: "GET" | "POST" | "PATCH"; body?: JsonObject }): Promise<JsonValue> {
    const headers = new Headers({ accept: "application/json" }); if (input.body) headers.set("content-type", "application/json"); const credential = this.config.credential;
    if (this.config.authType === "bearer" && credential) headers.set("authorization", `Bearer ${credential}`); if (this.config.authType === "basic" && credential) headers.set("authorization", `Basic ${credential}`); if (this.config.authType === "api-key" && credential) headers.set(this.config.apiKeyHeader, credential);
    let response: Response; try { response = await fetch(`${this.config.baseUrl}${path}`, { method: input.method, headers, ...(input.body ? { body: JSON.stringify(input.body) } : {}), redirect: "error", signal: AbortSignal.timeout(this.config.timeoutSeconds * 1000) }); } catch (error) { throw new AdapterError(`Jira Gateway request failed: ${error instanceof Error ? error.message : String(error)}`); }
    const length = Number(response.headers.get("content-length") ?? 0); if (length > 1_048_576) throw new AdapterError("Jira Gateway response exceeds 1 MB"); const payload = await this.responseText(response); if (!response.ok) throw new AdapterError(`Jira Gateway returned HTTP ${response.status}`); try { return JSON.parse(payload) as JsonValue; } catch { throw new AdapterError("Jira Gateway response is not valid JSON"); }
  }
  private async responseText(response: Response): Promise<string> { if (!response.body) return ""; const reader = response.body.getReader(); const decoder = new TextDecoder(); let size = 0; let result = ""; try { while (true) { const chunk = await reader.read(); if (chunk.done) break; size += chunk.value.byteLength; if (size > 1_048_576) { await reader.cancel(); throw new AdapterError("Jira Gateway response exceeds 1 MB"); } result += decoder.decode(chunk.value, { stream: true }); } return result + decoder.decode(); } finally { reader.releaseLock(); } }
}

export class JiraIntegrationManager {
  private readonly fallback: JiraAdapter | undefined;
  constructor(private readonly workspace: Workspace, private readonly tools: ToolBroker) { this.fallback = tools.getAdapter("jira"); this.restore(); }
  summary(): JiraConfigSummary { if (!this.workspace.integrationExists("jira")) return { configured: this.tools.hasAdapter("jira"), source: this.tools.hasAdapter("jira") ? "runtime" : "none", credentialConfigured: false }; const config = this.read(); return { configured: true, source: "workspace", baseUrl: config.baseUrl, authType: config.authType, credentialConfigured: Boolean(config.credential), apiKeyHeader: config.apiKeyHeader, ...(config.projectKey ? { projectKey: config.projectKey } : {}), ...(config.issueType ? { issueType: config.issueType } : {}), timeoutSeconds: config.timeoutSeconds, savedAt: config.savedAt, lastTestedAt: config.lastTestedAt }; }
  async test(input: JiraConfigInput): Promise<{ status: "connected"; testedAt: string }> { const config = this.normalize(input, false); await new HttpJiraAdapter(config).testConnection(); return { status: "connected", testedAt: config.lastTestedAt }; }
  async save(input: JiraConfigInput): Promise<JiraConfigSummary> { const config = this.normalize(input, true); await new HttpJiraAdapter(config).testConnection(); this.workspace.saveIntegrationConfig("jira", config as unknown as JsonValue); this.tools.setAdapter("jira", new HttpJiraAdapter(config)); return this.summary(); }
  remove(): JiraConfigSummary { this.workspace.removeIntegrationConfig("jira"); if (this.fallback) this.tools.setAdapter("jira", this.fallback); else this.tools.removeAdapter("jira"); return this.summary(); }
  private restore(): void { if (this.workspace.integrationExists("jira")) this.tools.setAdapter("jira", new HttpJiraAdapter(this.read())); }
  private read(): JiraHttpConfig { const raw = this.workspace.getIntegrationConfig("jira"); if (!isRecord(raw)) throw new ValidationError("invalid saved Jira configuration"); return this.normalize(raw as unknown as JiraConfigInput, true, true); }
  private normalize(input: JiraConfigInput, saving: boolean, preserveDates = false): JiraHttpConfig { const existing = this.workspace.integrationExists("jira") && !preserveDates ? this.read() : undefined; const type = normalizeAuthType(input.authType); const credential = optional(input.credential) ?? (existing?.authType === type ? existing.credential : undefined); if (type !== "none" && !credential) throw new ValidationError("credential is required for the selected authentication type"); const now = new Date().toISOString(); const raw = input as JiraConfigInput & Partial<JiraHttpConfig>; return { schemaVersion: 1, baseUrl: normalizeBaseUrl(input.baseUrl), authType: type, ...(credential ? { credential } : {}), apiKeyHeader: normalizeHeader(input.apiKeyHeader), ...(optional(input.projectKey) ? { projectKey: optional(input.projectKey) } : {}), ...(optional(input.issueType) ? { issueType: optional(input.issueType) } : {}), timeoutSeconds: normalizeTimeout(input.timeoutSeconds), savedAt: preserveDates && typeof raw.savedAt === "string" ? raw.savedAt : saving ? now : existing?.savedAt ?? now, lastTestedAt: preserveDates && typeof raw.lastTestedAt === "string" ? raw.lastTestedAt : now }; }
}
