import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmSync } from "node:fs";
import { basename, dirname, relative, resolve, sep } from "node:path";
import { ValidationError } from "./errors.js";
import { isRecord, type Change, type JsonObject, type JsonValue } from "./models.js";
import type { Workspace } from "./storage.js";
import type { Task } from "./tasks.js";

export const workspaceKinds = ["local", "virtual"] as const;
export const workspaceProviders = ["local", "gitlab", "github"] as const;
export type ManagedWorkspaceKind = typeof workspaceKinds[number];
export type WorkspaceProvider = typeof workspaceProviders[number];
export interface ManagedWorkspace { schemaVersion: 1; id: string; name: string; kind: ManagedWorkspaceKind; provider: WorkspaceProvider; repositoryId: string; rootPath?: string; defaultRef?: string; createdAt: string; updatedAt: string }
export interface WorkspaceTreeEntry { path: string; name: string; type: "tree" | "blob"; size?: number }
export interface WorkspaceFile { path: string; content: string; encoding: "utf8"; size: number; ref?: string }
export interface WorkspaceRef { name: string; type: "branch" | "tag"; sha?: string }
export interface WorkspaceCommit { sha: string; shortSha: string; subject: string; author: string; authoredAt: string }
export interface WorkspaceCommitCheck { sha: string; valid: boolean; signature: string; whitespaceErrors: string[]; changedFiles: string[]; checks: JsonObject[] }
export interface WorkspaceWorktree { path: string; head?: string; branch?: string; bare?: boolean; detached?: boolean }
export interface WorkspaceIssue { id: string; number: number; title: string; state: string; author?: string; assignees: string[]; labels: string[]; updatedAt?: string; url?: string }
export interface WorkspaceChangeRequest extends WorkspaceIssue { sourceBranch?: string; targetBranch?: string; draft?: boolean }
export interface WorkspaceComment { id: string; author?: string; body: string; createdAt?: string; updatedAt?: string }
export interface RemoteWorkspaceBrowser {
  getRepository(id: string): Promise<JsonObject>;
  listTree(id: string, path: string, ref?: string): Promise<JsonObject[]>;
  getFile(id: string, path: string, ref?: string): Promise<WorkspaceFile>;
  listRefs(id: string): Promise<WorkspaceRef[]>;
  listCommits(id: string, ref?: string): Promise<WorkspaceCommit[]>;
  inspectCommit(id: string, sha: string): Promise<WorkspaceCommitCheck>;
  listIssues(id: string): Promise<WorkspaceIssue[]>;
  listChangeRequests(id: string): Promise<WorkspaceChangeRequest[]>;
  listComments(id: string, kind: "issue" | "change-request", number: number): Promise<WorkspaceComment[]>;
}
export interface WorkspaceHubOptions { remote(provider: "gitlab" | "github"): RemoteWorkspaceBrowser | undefined; changes(): Change[]; tasks(): Task[]; runs(): JsonValue[] }

function required(value: unknown, key: string): string { if (typeof value !== "string" || !value.trim()) throw new ValidationError(`${key} is required`); return value.trim(); }
function safeId(value: string): string { const slug = value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 32) || "workspace"; return `${slug}-${randomUUID().slice(0, 8)}`; }
function record(value: JsonValue): JsonObject | undefined { return isRecord(value) ? value as JsonObject : undefined; }

export class WorkspaceHub {
  private readonly directory: string;
  constructor(private readonly storage: Workspace, private readonly options: WorkspaceHubOptions) { this.directory = storage.workspaces; }
  initialize(): void { this.storage.initialize(); mkdirSync(this.directory, { recursive: true }); }
  list(): ManagedWorkspace[] { this.initialize(); return readdirSync(this.directory, { withFileTypes: true }).filter((entry) => entry.isFile() && entry.name.endsWith(".json")).map((entry) => this.storage.readJson(resolve(this.directory, entry.name)) as unknown as ManagedWorkspace).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  get(id: string): ManagedWorkspace { const workspace = this.list().find((item) => item.id === id); if (!workspace) throw new ValidationError(`workspace not found: ${id}`); return workspace; }
  addLocal(input: { name?: string; path: string }): ManagedWorkspace { const rootPath = this.gitRoot(required(input.path, "path")); const duplicate = this.list().find((item) => item.kind === "local" && item.rootPath === rootPath); if (duplicate) return duplicate; const now = new Date().toISOString(); const name = input.name?.trim() || basename(rootPath); const item: ManagedWorkspace = { schemaVersion: 1, id: safeId(name), name, kind: "local", provider: "local", repositoryId: rootPath, rootPath, defaultRef: this.git(rootPath, ["symbolic-ref", "--quiet", "--short", "HEAD"], true).trim() || "HEAD", createdAt: now, updatedAt: now }; this.save(item); return item; }
  async addVirtual(input: { name?: string; provider: "gitlab" | "github"; repositoryId: string; defaultRef?: string }): Promise<ManagedWorkspace> { const repositoryId = required(input.repositoryId, "repositoryId"); const browser = this.browser(input.provider); const repository = await browser.getRepository(repositoryId); const duplicate = this.list().find((item) => item.provider === input.provider && item.repositoryId === repositoryId); if (duplicate) return duplicate; const name = input.name?.trim() || this.repositoryName(repository, repositoryId); const defaultRef = input.defaultRef?.trim() || this.string(repository, "default_branch") || this.string(repository, "defaultBranch") || "HEAD"; const now = new Date().toISOString(); const item: ManagedWorkspace = { schemaVersion: 1, id: safeId(name), name, kind: "virtual", provider: input.provider, repositoryId, defaultRef, createdAt: now, updatedAt: now }; this.save(item); return item; }
  remove(id: string): void { this.get(id); const file = resolve(this.directory, `${id}.json`); this.ensureEntityFile(file); rmSync(file, { force: true }); }
  async overview(id: string): Promise<JsonObject> { const item = this.get(id); if (item.kind === "virtual") { const repository = await this.browser(item.provider).getRepository(item.repositoryId); const [refs, commits, issues, changes] = await Promise.all([this.refs(id), this.commits(id), this.issues(id), this.changeRequests(id)]); return { workspace: item as unknown as JsonValue, repository, summary: { refs: refs.length, commits: commits.length, issues: issues.filter((issue) => this.isOpen(issue.state)).length, changeRequests: changes.filter((change) => this.isOpen(change.state)).length } } as unknown as JsonObject; }
    const root = this.localRoot(item); const status = this.git(root, ["status", "--porcelain=v1", "--branch"], true).split("\n").filter(Boolean); const [head = "", ...changes] = status; const commits = this.localCommits(root); return { workspace: item as unknown as JsonValue, repository: { path: root, branch: head.replace(/^##\s*/, ""), clean: changes.length === 0 }, summary: { changedFiles: changes.length, worktrees: this.localWorktrees(root).length, refs: this.localRefs(root).length, commits: commits.length }, recentCommits: commits.slice(0, 8) as unknown as JsonValue } as unknown as JsonObject;
  }
  async kanban(id: string): Promise<JsonObject> { const item = this.get(id); const primaryLocal = this.list().filter((entry) => entry.kind === "local").at(-1)?.id; const tasks = this.options.tasks().filter((task) => task.workspaceId === id || (!task.workspaceId && id === primaryLocal)); if (item.kind === "virtual") { const [issues, changes] = await Promise.all([this.issues(id), this.changeRequests(id)]); return { source: item.provider, columns: ["backlog", "in_progress", "review", "done"], tasks: tasks as unknown as JsonValue, issues: issues as unknown as JsonValue, changeRequests: changes as unknown as JsonValue } as unknown as JsonObject; } return { source: "cjhx", tasks: tasks as unknown as JsonValue } as unknown as JsonObject; }
  sessions(id: string): JsonValue[] { const item = this.get(id); const primaryLocal = this.list().filter((entry) => entry.kind === "local").at(-1)?.id; return this.options.runs().filter((value) => { const run = record(value); return run?.workspaceId === id || (!run?.workspaceId && item.kind === "local" && id === primaryLocal); }); }
  async team(id: string): Promise<JsonObject[]> { const item = this.get(id); const primaryLocal = this.list().filter((entry) => entry.kind === "local").at(-1)?.id; const members = new Map<string, { name: string; changes: number; tasks: number; active: number }>(); const add = (name: string, key: "changes" | "tasks", active: boolean) => { if (!name) return; const member = members.get(name) ?? { name, changes: 0, tasks: 0, active: 0 }; member[key] += 1; if (active) member.active += 1; members.set(name, member); }; for (const change of this.options.changes().filter((change) => change.workspaceId === id || (!change.workspaceId && id === primaryLocal))) add(change.owner, "changes", change.state !== "outcome_validated"); for (const task of this.options.tasks().filter((task) => task.workspaceId === id || (!task.workspaceId && id === primaryLocal))) add(task.owner, "tasks", task.status !== "done"); if (item.kind === "virtual") { const [issues, requests] = await Promise.all([this.issues(id), this.changeRequests(id)]); for (const issue of issues) { if (issue.author) add(issue.author, "tasks", this.isOpen(issue.state)); for (const assignee of issue.assignees) add(assignee, "tasks", this.isOpen(issue.state)); } for (const request of requests) { if (request.author) add(request.author, "changes", this.isOpen(request.state)); for (const assignee of request.assignees) add(assignee, "changes", this.isOpen(request.state)); } } return [...members.values()].sort((a, b) => b.active - a.active) as unknown as JsonObject[]; }
  async tree(id: string, path = "", ref?: string): Promise<WorkspaceTreeEntry[]> { const item = this.get(id); if (item.kind === "virtual") return (await this.browser(item.provider).listTree(item.repositoryId, path, ref ?? item.defaultRef)).map((entry): WorkspaceTreeEntry => ({ path: String(entry.path ?? entry.name ?? ""), name: String(entry.name ?? basename(String(entry.path ?? ""))), type: entry.type === "tree" || entry.type === "dir" ? "tree" : "blob", ...(typeof entry.size === "number" ? { size: entry.size } : {}) })); const root = this.localRoot(item); const directory = this.safeLocalPath(root, path); if (!lstatSync(directory).isDirectory()) throw new ValidationError("path is not a directory"); return readdirSync(directory, { withFileTypes: true }).filter((entry) => { const absolute = resolve(directory, entry.name); return entry.name !== ".git" && entry.name !== "node_modules" && !entry.isSymbolicLink() && !this.isStatePath(absolute); }).map((entry): WorkspaceTreeEntry => { const absolute = resolve(directory, entry.name); const itemPath = relative(root, absolute).split(sep).join("/"); return { path: itemPath, name: entry.name, type: entry.isDirectory() ? "tree" : "blob", ...(!entry.isDirectory() ? { size: lstatSync(absolute).size } : {}) }; }).sort((a, b) => a.type === b.type ? a.name.localeCompare(b.name) : a.type === "tree" ? -1 : 1);
  }
  async file(id: string, path: string, ref?: string): Promise<WorkspaceFile> { const item = this.get(id); if (item.kind === "virtual") return await this.browser(item.provider).getFile(item.repositoryId, required(path, "path"), ref ?? item.defaultRef); const root = this.localRoot(item); const file = this.safeLocalPath(root, required(path, "path")); const stat = lstatSync(file); if (!stat.isFile()) throw new ValidationError("path is not a file"); if (stat.size > 1_048_576) throw new ValidationError("file exceeds 1 MB"); const content = readFileSync(file, "utf8"); if (content.includes("\0")) throw new ValidationError("binary files cannot be previewed"); return { path: relative(root, file).split(sep).join("/"), content, encoding: "utf8", size: stat.size };
  }
  search(id: string, query: string): JsonObject[] { const item = this.get(id); if (item.kind !== "local") throw new ValidationError("remote code search is not available; browse the virtual workspace tree instead"); const root = this.localRoot(item); const needle = required(query, "query").toLowerCase(); const output: JsonObject[] = []; let scanned = 0; const walk = (directory: string) => { if (output.length >= 200 || scanned >= 10_000) return; for (const entry of readdirSync(directory, { withFileTypes: true })) { if (++scanned > 10_000) break; if ([".git", "node_modules", "dist"].includes(entry.name) || entry.isSymbolicLink()) continue; const absolute = resolve(directory, entry.name); if (this.isStatePath(absolute)) continue; const itemPath = relative(root, absolute).split(sep).join("/"); if (entry.isDirectory()) walk(absolute); else if (entry.isFile() && lstatSync(absolute).size <= 262_144) { if (entry.name.toLowerCase().includes(needle)) output.push({ path: itemPath, line: 0, preview: entry.name }); if (output.length >= 200) break; const content = readFileSync(absolute, "utf8"); if (content.includes("\0")) continue; for (const [index, line] of content.split("\n").entries()) if (line.toLowerCase().includes(needle)) { output.push({ path: itemPath, line: index + 1, preview: line.trim().slice(0, 240) }); if (output.length >= 200) break; } } } }; walk(root); return output;
  }
  async refs(id: string): Promise<WorkspaceRef[]> { const item = this.get(id); return item.kind === "virtual" ? await this.browser(item.provider).listRefs(item.repositoryId) : this.localRefs(this.localRoot(item)); }
  async commits(id: string, ref?: string): Promise<WorkspaceCommit[]> { const item = this.get(id); return item.kind === "virtual" ? await this.browser(item.provider).listCommits(item.repositoryId, ref ?? item.defaultRef) : this.localCommits(this.localRoot(item), ref === undefined ? undefined : this.revision(ref)); }
  createRef(id: string, input: { name: string; revision: string; type: "branch" | "tag"; approved: boolean }): WorkspaceRef[] { if (!input.approved) throw new ValidationError("Git ref operation requires human approval"); const item = this.get(id); const root = this.localRoot(item); const name = this.refName(input.name); const revision = this.revision(input.revision); this.git(root, input.type === "tag" ? ["tag", name, revision] : ["branch", name, revision]); return this.localRefs(root); }
  deleteRef(id: string, input: { name: string; type: "branch" | "tag"; approved: boolean }): WorkspaceRef[] { if (!input.approved) throw new ValidationError("Git ref operation requires human approval"); const item = this.get(id); const root = this.localRoot(item); const name = this.refName(input.name); const current = this.git(root, ["symbolic-ref", "--quiet", "--short", "HEAD"], true).trim(); if (input.type === "branch" && current === name) throw new ValidationError("current branch cannot be deleted"); this.git(root, input.type === "tag" ? ["tag", "-d", name] : ["branch", "-D", name]); return this.localRefs(root); }
  async inspectCommit(id: string, sha: string): Promise<WorkspaceCommitCheck> { const item = this.get(id); if (item.kind === "virtual") return await this.browser(item.provider).inspectCommit(item.repositoryId, required(sha, "sha")); const root = this.localRoot(item); const revision = this.revision(sha); this.git(root, ["rev-parse", "--verify", `${revision}^{commit}`]); const whitespace = this.git(root, ["diff-tree", "--check", `${revision}^!`], true).split("\n").filter(Boolean); const changedFiles = this.git(root, ["diff-tree", "--root", "--no-commit-id", "--name-only", "-r", revision], true).split("\n").filter(Boolean); const signature = this.git(root, ["show", "-s", "--format=%G?", revision], true).trim() || "N"; return { sha: this.git(root, ["rev-parse", revision]).trim(), valid: whitespace.length === 0, signature, whitespaceErrors: whitespace, changedFiles, checks: [] };
  }
  worktrees(id: string): WorkspaceWorktree[] { const item = this.get(id); if (item.kind !== "local") return []; return this.localWorktrees(this.localRoot(item)); }
  addWorktree(id: string, input: { path: string; ref: string; createBranch?: string; approved: boolean }): WorkspaceWorktree[] { if (!input.approved) throw new ValidationError("worktree operation requires human approval"); const item = this.get(id); const root = this.localRoot(item); const target = resolve(required(input.path, "path")); const ref = this.revision(input.ref); const args = ["worktree", "add"]; if (input.createBranch?.trim()) args.push("-b", this.refName(input.createBranch)); args.push(target, ref); this.git(root, args); return this.localWorktrees(root); }
  removeWorktree(id: string, input: { path: string; approved: boolean }): WorkspaceWorktree[] { if (!input.approved) throw new ValidationError("worktree operation requires human approval"); const item = this.get(id); const root = this.localRoot(item); const path = realpathSync(resolve(required(input.path, "path"))); if (!this.localWorktrees(root).some((worktree) => realpathSync(worktree.path) === path)) throw new ValidationError("worktree is not registered for this repository"); if (path === root) throw new ValidationError("main worktree cannot be removed"); this.git(root, ["worktree", "remove", path]); return this.localWorktrees(root); }
  async issues(id: string): Promise<WorkspaceIssue[]> { const item = this.get(id); return item.kind === "virtual" ? await this.browser(item.provider).listIssues(item.repositoryId) : []; }
  async changeRequests(id: string): Promise<WorkspaceChangeRequest[]> { const item = this.get(id); return item.kind === "virtual" ? await this.browser(item.provider).listChangeRequests(item.repositoryId) : []; }
  async comments(id: string, kind: "issue" | "change-request", number: number): Promise<WorkspaceComment[]> { const item = this.get(id); if (item.kind !== "virtual") return []; if (!Number.isInteger(number) || number <= 0) throw new ValidationError("number must be a positive integer"); return await this.browser(item.provider).listComments(item.repositoryId, kind, number); }
  private browser(provider: WorkspaceProvider): RemoteWorkspaceBrowser { if (provider === "local") throw new ValidationError("local workspace does not use a remote browser"); const browser = this.options.remote(provider); if (!browser) throw new ValidationError(`${provider} Adapter is not configured`); return browser; }
  private save(item: ManagedWorkspace): void { this.initialize(); this.ensureEntityFile(resolve(this.directory, `${item.id}.json`)); this.storage.writeJson(resolve(this.directory, `${item.id}.json`), item as unknown as JsonValue); }
  private ensureEntityFile(path: string): void { if (dirname(path) !== this.directory || !/^[A-Za-z0-9][A-Za-z0-9_-]*\.json$/.test(basename(path))) throw new ValidationError("workspace id contains unsupported characters"); }
  private gitRoot(path: string): string { const resolved = realpathSync(resolve(path)); const root = this.git(resolved, ["rev-parse", "--show-toplevel"]).trim(); if (!root) throw new ValidationError("path is not inside a Git repository"); return realpathSync(root); }
  private localRoot(item: ManagedWorkspace): string { if (item.kind !== "local" || !item.rootPath) throw new ValidationError("workspace is not local"); if (!existsSync(item.rootPath)) throw new ValidationError("local repository no longer exists"); return realpathSync(item.rootPath); }
  private safeLocalPath(root: string, path: string): string { const candidate = resolve(root, path || "."); const relativePath = relative(root, candidate); if (relativePath === ".." || relativePath.startsWith(`..${sep}`) || resolve(candidate) === resolve(root, ".git") || relativePath.startsWith(`.git${sep}`) || this.isStatePath(candidate)) throw new ValidationError("path escapes the repository root or enters CJHX state"); if (!existsSync(candidate)) throw new ValidationError("path does not exist"); const actual = realpathSync(candidate); const actualRelative = relative(root, actual); if (actualRelative === ".." || actualRelative.startsWith(`..${sep}`) || actual === resolve(root, ".git") || actualRelative.startsWith(`.git${sep}`) || this.isStatePath(actual)) throw new ValidationError("path escapes the repository root or enters protected state"); return actual; }
  private isStatePath(path: string): boolean { const state = existsSync(this.storage.root) ? realpathSync(this.storage.root) : resolve(this.storage.root); const candidate = existsSync(path) ? realpathSync(path) : resolve(path); const relation = relative(state, candidate); return relation === "" || (!relation.startsWith(`..${sep}`) && relation !== ".."); }
  private git(root: string, args: string[], allowFailure = false): string { try { return execFileSync("git", ["-C", root, ...args], { encoding: "utf8", timeout: 10_000, maxBuffer: 1_048_576, stdio: ["ignore", "pipe", allowFailure ? "ignore" : "pipe"] }); } catch (error) { if (allowFailure) return ""; throw new ValidationError(`Git operation failed: ${error instanceof Error ? error.message.split("\n")[0] : String(error)}`); } }
  private revision(value: unknown): string { const revision = required(value, "revision"); if (revision.startsWith("-")) throw new ValidationError("Git revision cannot start with an option prefix"); return revision; }
  private refName(value: unknown): string { const name = required(value, "name"); if (name.startsWith("-") || name.includes("..") || name.includes("@{") || /[~^:?*[\\\s]/.test(name) || name.endsWith("/") || name.endsWith(".")) throw new ValidationError("invalid Git ref name"); return name; }
  private localRefs(root: string): WorkspaceRef[] { const format = "%(refname:short)%00%(objectname)%00%(refname)"; return this.git(root, ["for-each-ref", `--format=${format}`, "refs/heads", "refs/tags"], true).split("\n").filter(Boolean).map((line) => { const [name = "", sha = "", full = ""] = line.split("\0"); return { name, sha, type: full.startsWith("refs/tags/") ? "tag" : "branch" }; }); }
  private localCommits(root: string, ref = "HEAD"): WorkspaceCommit[] { const format = "%H%x00%h%x00%s%x00%an%x00%aI"; return this.git(root, ["log", "-50", `--format=${format}`, ref], true).split("\n").filter(Boolean).map((line) => { const [sha = "", shortSha = "", subject = "", author = "", authoredAt = ""] = line.split("\0"); return { sha, shortSha, subject, author, authoredAt }; }); }
  private localWorktrees(root: string): WorkspaceWorktree[] { const output = this.git(root, ["worktree", "list", "--porcelain"], true); const result: WorkspaceWorktree[] = []; let current: WorkspaceWorktree | undefined; for (const line of output.split("\n")) { if (line.startsWith("worktree ")) { current = { path: line.slice(9) }; result.push(current); } else if (current && line.startsWith("HEAD ")) current.head = line.slice(5); else if (current && line.startsWith("branch ")) current.branch = line.slice(7).replace("refs/heads/", ""); else if (current && line === "bare") current.bare = true; else if (current && line === "detached") current.detached = true; } return result; }
  private isOpen(state: string): boolean { return state === "open" || state === "opened" || state === "reopened"; }
  private repositoryName(repository: JsonObject, fallback: string): string { return this.string(repository, "name") || this.string(repository, "full_name") || this.string(repository, "path_with_namespace") || fallback; }
  private string(value: JsonObject, key: string): string | undefined { return typeof value[key] === "string" ? value[key] : undefined; }
}
