const lifecycle = ["intent_draft","intent_confirmed","requirement_ready","design_approved","implementing","reviewing","verified","accepted","release_approved","deploying","operating","outcome_validated"] as const;
type LifecycleState = typeof lifecycle[number];
type View = "changes" | "board" | "devops" | "skills" | "runs";
type EvidenceTab = "evidence" | "tasks" | "history" | "runs";
type TaskStatus = "clarification" | "todo" | "in_progress" | "review" | "verification" | "done" | "blocked";
interface Evidence { kind: string; source: string; status: string; subjectRef: string; createdAt: string }
interface TransitionRecord { fromState: LifecycleState; toState: LifecycleState; actor: string; reason: string; at: string }
interface AvailableTransition { target: LifecycleState; missingEvidence: string[] }
interface Change { id: string; title: string; owner: string; description: string; riskLevel: string; state: LifecycleState; createdAt: string; updatedAt: string; evidence: Evidence[]; history: TransitionRecord[]; nextTransitions: AvailableTransition[] }
interface SkillManifest { id: string; version: string; name: string; description: string; source: string; riskLevel: string }
interface InstalledSkill { id: string; digest: string; manifest: SkillManifest }
interface Run { id: string; status: string; completedAt: string; changeId?: string; skillId?: string; workflowId?: string; output?: Record<string, unknown>; [key: string]: unknown }
interface TaskHistory { fromStatus: TaskStatus; toStatus: TaskStatus; actor: string; reason: string; at: string; authority: "local-draft" | "jira" }
interface Task { id: string; changeId: string; title: string; description: string; owner: string; priority: string; riskLevel: string; status: TaskStatus; authority: "local-draft" | "jira"; acceptanceCriteria: string[]; dependencies: string[]; evidenceRefs: string[]; sourceRunId?: string; sourceTaskId?: string; jiraIssueKey?: string; jiraStatus?: string; jiraUrl?: string; lastSyncedAt?: string; history: TaskHistory[]; createdAt: string; updatedAt: string }
interface Snapshot { changes: Change[]; tasks: Task[]; skills: InstalledSkill[]; runs: Run[]; lifecycleStates: LifecycleState[]; workspace: string; integrations: { jiraConfigured: boolean; devopsConfigured: boolean } }
interface DevOpsItem { id?: string; pipelineId?: string; runId?: string; artifactId?: string; name?: string; pipelineName?: string; kind?: string; status?: string; version?: string; environment?: string; changeId?: string; ref?: string; url?: string; startedAt?: string; completedAt?: string; createdAt?: string; updatedAt?: string; [key: string]: unknown }
interface DevOpsOverview { pipelines: DevOpsItem[]; runs: DevOpsItem[]; artifacts: DevOpsItem[]; services: DevOpsItem[]; syncedAt: string }
interface ModalOptions { title: string; description?: string; fields: string; submit?: string; wide?: boolean; onSubmit(data: FormData): Promise<void> }
interface FieldOptions { type?: "text" | "textarea" | "select"; full?: boolean; code?: boolean; required?: boolean; placeholder?: string; value?: string; help?: string; options?: [string, string][] }

function $<T extends Element = HTMLElement>(selector: string, root: ParentNode = document): T { const element = root.querySelector<T>(selector); if (!element) throw new Error(`UI element not found: ${selector}`); return element; }
function $$<T extends Element = HTMLElement>(selector: string, root: ParentNode = document): T[] { return [...root.querySelectorAll<T>(selector)]; }
const token = $<HTMLMetaElement>('meta[name="cjhx-ui-token"]').content;
const escapes: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" };
const esc = (value: unknown = ""): string => String(value).replace(/[&<>'"]/g, (char) => escapes[char] ?? char);
const stateLabels: Record<LifecycleState, string> = { intent_draft:"意图草拟",intent_confirmed:"意图确认",requirement_ready:"需求就绪",design_approved:"设计批准",implementing:"开发实现",reviewing:"代码评审",verified:"质量验证",accepted:"业务验收",release_approved:"发布批准",deploying:"部署中",operating:"运行中",outcome_validated:"结果验证" };
const stateGroups: Record<LifecycleState, string> = { intent_draft:"意图",intent_confirmed:"意图",requirement_ready:"需求",design_approved:"设计",implementing:"开发",reviewing:"评审",verified:"质量",accepted:"验收",release_approved:"发布",deploying:"部署",operating:"运行",outcome_validated:"度量" };
const evidenceLabels: Record<string, string> = { "intent-approval":"意图审批","requirement-spec":"需求规格","technical-design":"技术方案","design-approval":"设计审批","change-request":"代码变更请求","code-review":"代码评审","quality-verification":"质量验证","acceptance-approval":"业务验收","release-plan":"发布计划","release-approval":"发布审批","deployment-record":"部署记录","outcome-validation":"结果验证" };
const taskColumns: { status: TaskStatus; label: string; hint: string }[] = [{ status:"clarification",label:"待澄清",hint:"范围或条件待确认"},{status:"todo",label:"待开始",hint:"已就绪，尚未执行"},{status:"in_progress",label:"进行中",hint:"正在实现"},{status:"review",label:"评审中",hint:"等待或正在评审"},{status:"verification",label:"验证中",hint:"质量与验收验证"},{status:"done",label:"已完成",hint:"目标已验证"},{status:"blocked",label:"已阻塞",hint:"存在外部阻塞"}];
const taskStatusLabels = Object.fromEntries(taskColumns.map((column) => [column.status, column.label])) as Record<TaskStatus, string>;
const taskTransitions: Record<TaskStatus, TaskStatus[]> = { clarification:["todo","blocked"],todo:["clarification","in_progress","blocked"],in_progress:["todo","review","blocked"],review:["in_progress","verification","blocked"],verification:["in_progress","done","blocked"],done:["in_progress"],blocked:["clarification","todo","in_progress","review","verification"] };
const app: { snapshot: Snapshot; view: View; selectedChange: string | null; evidenceTab: EvidenceTab; boardFilters: { changeId: string; owner: string; risk: string; status: string }; devops: DevOpsOverview | null; devopsChangeId: string; devopsLoading: boolean; devopsError: string } = { snapshot: { changes: [], tasks: [], skills: [], runs: [], lifecycleStates: [...lifecycle], workspace: "", integrations: { jiraConfigured: false, devopsConfigured: false } }, view: "changes", selectedChange: localStorage.getItem("cjhx:selected-change"), evidenceTab: "evidence", boardFilters: { changeId: "", owner: "", risk: "", status: "" }, devops: null, devopsChangeId: "", devopsLoading: false, devopsError: "" };

async function request<T = Record<string, unknown>>(path: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(path, { ...options, headers: { ...(options.body ? { "content-type": "application/json" } : {}), ...(options.method && options.method !== "GET" ? { "x-cjhx-ui-token": token } : {}), ...Object.fromEntries(new Headers(options.headers).entries()) } });
  const value = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(value.error || `请求失败 (${response.status})`); return value;
}
async function refresh({ quiet = false }: { quiet?: boolean } = {}): Promise<void> {
  if (!quiet) $("#sync-state").innerHTML = "<i></i> 正在读取";
  try { app.snapshot = await request<Snapshot>("/api/snapshot"); normalizeSelection(); render(); $("#sync-state").classList.remove("failed"); $("#sync-state").innerHTML = "<i></i> 已连接"; }
  catch (error) { $("#sync-state").classList.add("failed"); $("#sync-state").innerHTML = "<i></i> 连接失败"; toast(errorMessage(error), true); }
}
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function normalizeSelection(): void { const changes = app.snapshot.changes; if (!changes.some((change) => change.id === app.selectedChange)) app.selectedChange = changes[0]?.id || null; if (app.selectedChange) localStorage.setItem("cjhx:selected-change", app.selectedChange); }
function formatTime(value: string | undefined): string { if (!value) return "—"; return new Intl.DateTimeFormat("zh-CN", { month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit" }).format(new Date(value)); }
function formatJson(value: unknown): string { return esc(JSON.stringify(value, null, 2)); }
function toast(message: string, error = false): void { const item = document.createElement("div"); item.className = `toast${error ? " error" : ""}`; item.textContent = message; $("#toast-root").append(item); setTimeout(() => item.remove(), 3600); }
function selectedChange(): Change | undefined { return app.snapshot.changes.find((change) => change.id === app.selectedChange); }
function requireChange(): Change { const change = selectedChange(); if (!change) throw new Error("请先选择研发变更"); return change; }
function formValues(data: FormData): Record<string, string> { return Object.fromEntries([...data.entries()].map(([key, value]) => [key, String(value)])); }

function render() {
  const { changes = [], tasks = [], skills = [], runs = [] } = app.snapshot;
  $("#change-count").textContent = String(changes.length); $("#task-count").textContent = String(tasks.length); $("#devops-count").textContent = app.snapshot.integrations.devopsConfigured ? String(app.devops?.runs.length ?? 0) : "—"; $("#skill-count").textContent = String(skills.length); $("#run-count").textContent = String(runs.length);
  renderChangeList(); $$<HTMLElement>(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === app.view));
  const titles: Record<View, string> = { changes: selectedChange()?.id || "研发变更", board: "任务看板", devops:"DevOps", skills:"Skill Library", runs:"运行记录" }; $("#page-title").textContent = titles[app.view];
  $("#primary-action").textContent = app.view === "changes" ? "创建变更" : app.view === "board" ? "新建任务" : app.view === "devops" ? "触发流水线" : app.view === "skills" ? "安装 Skill" : "运行 Workflow";
  $<HTMLButtonElement>("#primary-action").disabled = app.view === "devops" && !app.snapshot.integrations.devopsConfigured;
  $("#install-skill").hidden = app.view === "skills";
  if (app.view === "board") renderBoard(); else if (app.view === "devops") renderDevOps(); else if (app.view === "skills") renderSkills(); else if (app.view === "runs") renderRuns(); else renderChange();
}
function renderChangeList() {
  const query = $<HTMLInputElement>("#change-search").value.trim().toLowerCase(); const changes = (app.snapshot?.changes || []).filter((change) => `${change.id} ${change.title} ${change.owner}`.toLowerCase().includes(query));
  $("#change-list").innerHTML = changes.length ? changes.map((change) => `<button class="change-row ${change.id === app.selectedChange ? "current" : ""}" data-change-id="${esc(change.id)}"><div class="change-row-top"><span class="state-dot ${["outcome_validated"].includes(change.state) ? "" : "active"}"></span><span class="change-key">${esc(change.id)}</span><span class="risk">${esc(change.riskLevel)}</span></div><div class="change-title">${esc(change.title)}</div></button>`).join("") : `<div class="sidebar-empty">${query ? "没有匹配的变更" : "尚未创建研发变更"}</div>`;
}
function renderChange() {
  const change = selectedChange(); if (!change) { $("#content").innerHTML = `<div class="empty-state"><div class="empty-inner"><div class="empty-icon">⌘</div><h2>从一个研发变更开始</h2><p>创建工作项后，可在一个界面中编排需求、设计、开发、质量验证和发布证据。</p><button class="button primary" data-action="new-change">创建第一个变更</button></div></div>`; return; }
  const currentIndex = app.snapshot.lifecycleStates.indexOf(change.state); const next = change.nextTransitions || [];
  $("#content").innerHTML = `<div class="page-header"><div><div class="eyebrow">CHANGE / ${esc(change.id)}</div><h1>${esc(change.title)}</h1><p>${esc(change.description || "暂无变更说明")}</p></div><div class="header-meta"><span class="badge">${esc(change.riskLevel)} 风险</span><span class="badge good">● ${esc(stateLabels[change.state])}</span><button class="button secondary" data-action="run-workflow">↯ 运行 Workflow</button></div></div>
  <section class="lifecycle-card"><div class="card-heading"><div><h2>研发交付生命周期</h2><p>阶段推进由权威平台证据和人工门禁共同约束</p></div><span class="badge">${currentIndex + 1} / ${app.snapshot.lifecycleStates.length}</span></div><div class="lifecycle">${app.snapshot.lifecycleStates.map((state,index) => `<div class="stage ${index < currentIndex ? "complete" : index === currentIndex ? "current" : ""}" aria-label="${esc(stateLabels[state])}：${index < currentIndex ? "已完成" : index === currentIndex ? "当前阶段" : "待开始"}"><div class="stage-node" aria-hidden="true">${index < currentIndex ? "✓" : ""}</div><div class="stage-label"><span class="muted">${esc(stateGroups[state])}</span><br>${esc(stateLabels[state])}</div></div>`).join("")}</div></section>
  <div class="dashboard-grid"><div class="panel"><div class="tabs"><button class="tab ${app.evidenceTab === "evidence" ? "active" : ""}" data-tab="evidence">证据 <span class="muted">${change.evidence.length}</span></button><button class="tab ${app.evidenceTab === "tasks" ? "active" : ""}" data-tab="tasks">拆解任务 <span class="muted">${app.snapshot.tasks.filter((task) => task.changeId === change.id).length}</span></button><button class="tab ${app.evidenceTab === "history" ? "active" : ""}" data-tab="history">阶段历史 <span class="muted">${change.history.length}</span></button><button class="tab ${app.evidenceTab === "runs" ? "active" : ""}" data-tab="runs">关联运行</button></div><div class="panel-body">${renderChangeTab(change)}</div></div>
  <div><section class="panel"><div class="panel-header"><h2>阶段操作</h2><button class="button ghost" data-action="add-evidence">＋ 添加证据</button></div><div class="panel-body">${renderTransitions(next)}</div></section><section class="panel panel-spaced"><div class="panel-header"><h2>变更上下文</h2></div><div class="panel-body overview-grid"><div class="datum"><div class="datum-label">Owner</div><div class="datum-value">${esc(change.owner)}</div></div><div class="datum"><div class="datum-label">风险等级</div><div class="datum-value">${esc(change.riskLevel)}</div></div><div class="datum"><div class="datum-label">创建时间</div><div class="datum-value">${formatTime(change.createdAt)}</div></div><div class="datum"><div class="datum-label">最后更新</div><div class="datum-value">${formatTime(change.updatedAt)}</div></div></div></section><section class="panel panel-spaced"><div class="panel-header"><h2>Agentic Actions</h2></div><div class="panel-body action-row"><button class="button secondary" data-action="run-skill">◇ 运行 Skill</button><button class="button secondary" data-action="run-workflow">↯ 运行 Workflow</button></div></section></div></div>`;
}
function renderTransitions(transitions: AvailableTransition[]): string {
  if (!transitions.length) return `<div class="empty-list">当前阶段没有可用转换</div>`;
  const blocked = transitions.filter((item) => item.missingEvidence.length); const banner = blocked.length ? `<div class="gate-banner"><strong>存在未满足的证据门禁</strong><p>${blocked.flatMap((item) => item.missingEvidence).map((kind) => evidenceLabels[kind] || kind).join("、")}</p></div>` : "";
  return `${banner}<div class="next-actions">${transitions.map((item) => `<button class="transition-button" data-transition="${esc(item.target)}" ${item.missingEvidence.length ? "disabled" : ""}><span><strong>${item.target === "intent_draft" || app.snapshot.lifecycleStates.indexOf(item.target) < app.snapshot.lifecycleStates.indexOf(selectedChange()?.state ?? "intent_draft") ? "回退至" : "推进至"} ${esc(stateLabels[item.target])}</strong><small>${item.missingEvidence.length ? `缺少：${item.missingEvidence.map((kind) => evidenceLabels[kind] || kind).join("、")}` : "门禁已满足，可提交转换"}</small></span><span class="chevron">›</span></button>`).join("")}</div>`;
}
function renderChangeTab(change: Change): string {
  if (app.evidenceTab === "tasks") { const tasks = app.snapshot.tasks.filter((task) => task.changeId === change.id); return tasks.length ? tasks.map((task) => `<div class="evidence-row clickable" data-task-id="${esc(task.id)}"><span class="item-icon">▦</span><div><div class="item-title">${esc(task.title)} <span class="badge">${esc(taskStatusLabels[task.status])}</span></div><div class="item-sub">${esc(task.owner)} · ${esc(task.priority)} · ${esc(task.authority === "jira" ? task.jiraIssueKey : "本地草稿")}</div></div><time class="item-time">${formatTime(task.updatedAt)}</time></div>`).join("") : `<div class="empty-list">尚无拆解任务。运行需求拆解 Skill 后可从运行记录添加到看板。</div>`; }
  if (app.evidenceTab === "history") return change.history.length ? [...change.history].reverse().map((record) => `<div class="evidence-row"><span class="item-icon">↗</span><div><div class="item-title">${esc(stateLabels[record.fromState])} → ${esc(stateLabels[record.toState])}</div><div class="item-sub">${esc(record.actor)} · ${esc(record.reason)}</div></div><time class="item-time">${formatTime(record.at)}</time></div>`).join("") : `<div class="empty-list">尚无阶段转换记录</div>`;
  if (app.evidenceTab === "runs") { const runs = (app.snapshot.runs || []).filter((run) => run.changeId === change.id); return runs.length ? runs.map(runRow).join("") : `<div class="empty-list">尚无关联的 Skill 或 Workflow 运行</div>`; }
  return change.evidence.length ? [...change.evidence].reverse().map((evidence) => `<div class="evidence-row"><span class="item-icon">✓</span><div><div class="item-title">${esc(evidenceLabels[evidence.kind] || evidence.kind)} <span class="badge ${["approved","passed","valid"].includes(evidence.status.toLowerCase()) ? "good" : "warn"}">${esc(evidence.status)}</span></div><div class="item-sub">${esc(evidence.source)} · ${esc(evidence.subjectRef)}</div></div><time class="item-time">${formatTime(evidence.createdAt)}</time></div>`).join("") : `<div class="empty-list">尚无证据。添加权威平台引用以满足阶段门禁。</div>`;
}
function runRow(run: Run): string { const name = run.skillId || run.workflowId || "workflow"; return `<div class="run-row clickable" data-run-id="${esc(run.id)}"><span class="item-icon">${run.skillId ? "◇" : "↯"}</span><div><div class="item-title">${esc(name)}</div><div class="item-sub">${esc(run.id)}</div></div><time class="item-time ${run.status === "succeeded" ? "status-success" : "status-failed"}">${esc(run.status)}</time></div>`; }
function renderBoard(): void {
  const owners = [...new Set(app.snapshot.tasks.map((task) => task.owner))].sort(); const changes: [string, string][] = [["", "全部变更"], ...app.snapshot.changes.map((change): [string, string] => [change.id, `${change.id} · ${change.title}`])];
  const filtered = app.snapshot.tasks.filter((task) => (!app.boardFilters.changeId || task.changeId === app.boardFilters.changeId) && (!app.boardFilters.owner || task.owner === app.boardFilters.owner) && (!app.boardFilters.risk || task.riskLevel === app.boardFilters.risk) && (!app.boardFilters.status || task.status === app.boardFilters.status));
  const candidates = app.snapshot.runs.filter((run) => run.status === "succeeded" && run.changeId && Array.isArray(run.output?.tasks) && !app.snapshot.tasks.some((task) => task.sourceRunId === run.id));
  const jiraStatus = app.snapshot.integrations.jiraConfigured ? `<span class="badge good">● Jira 已连接</span>` : `<span class="badge warn">Jira Adapter 未配置</span>`;
  $("#content").innerHTML = `<div class="board-page"><div class="section-toolbar board-toolbar"><div><h1>需求任务看板</h1><p class="muted">本地草稿可在 CJHX 中流转；发布后 Jira 成为任务状态事实源</p></div><div class="header-meta">${jiraStatus}${candidates.length ? `<button class="button secondary" data-action="import-tasks">↓ 导入拆解任务 (${candidates.length})</button>` : ""}<button class="button primary" data-action="new-task">＋ 新建任务</button></div></div><div class="board-filters"><label>变更<select data-board-filter="changeId">${changes.map(([value,label]) => `<option value="${esc(value)}">${esc(label)}</option>`).join("")}</select></label><label>Owner<select data-board-filter="owner"><option value="">全部 Owner</option>${owners.map((owner) => `<option value="${esc(owner)}">${esc(owner)}</option>`).join("")}</select></label><label>风险<select data-board-filter="risk"><option value="">全部风险</option>${["L0","L1","L2","L3","L4","L5"].map((risk) => `<option value="${risk}">${risk}</option>`).join("")}</select></label><label>状态<select data-board-filter="status"><option value="">全部状态</option>${taskColumns.map((column)=>`<option value="${column.status}">${column.label}</option>`).join("")}</select></label><span class="muted">${filtered.length} 个任务</span></div><div class="kanban scrollbar">${taskColumns.map((column) => renderTaskColumn(column, filtered)).join("")}</div></div>`;
  for (const [name, value] of Object.entries(app.boardFilters)) $<HTMLSelectElement>(`[data-board-filter="${name}"]`).value = value;
}
function renderTaskColumn(column: { status: TaskStatus; label: string; hint: string }, tasks: Task[]): string {
  const items = tasks.filter((task) => task.status === column.status); return `<section class="kanban-column"><header><div><strong>${esc(column.label)}</strong><small>${esc(column.hint)}</small></div><span>${items.length}</span></header><div class="kanban-cards">${items.length ? items.map(renderTaskCard).join("") : `<div class="kanban-empty">暂无任务</div>`}</div></section>`;
}
function renderTaskCard(task: Task): string {
  const change = app.snapshot.changes.find((item) => item.id === task.changeId); const authority = task.authority === "jira" ? task.jiraIssueKey ?? "Jira" : "本地草稿"; const summary = change?.title ?? (task.description || "暂无说明"); return `<article class="task-card" role="button" tabindex="0" aria-label="${esc(task.title)}，${esc(taskStatusLabels[task.status])}" data-task-id="${esc(task.id)}"><div class="task-card-meta"><span class="change-key">${esc(task.changeId)}</span><span class="risk">${esc(task.priority)}</span><span class="risk">${esc(task.riskLevel)}</span></div><h3>${esc(task.title)}</h3><p>${esc(summary)}</p><div class="task-card-footer"><span>◎ ${esc(task.owner)}</span><span class="${task.authority === "jira" ? "status-success" : "muted"}">${esc(authority)}</span></div>${task.dependencies.length ? `<div class="task-dependency">↳ ${task.dependencies.length} 个依赖</div>` : ""}</article>`;
}
function renderDevOps(): void {
  const configured = app.snapshot.integrations.devopsConfigured; const overview = app.devops; const changes: [string,string][] = [["","全部变更"],...app.snapshot.changes.map((change):[string,string]=>[change.id,`${change.id} · ${change.title}`])];
  if (!configured) { $("#content").innerHTML = `<div class="devops-page"><div class="section-toolbar"><div><h1>DevOps</h1><p class="muted">流水线、制品与服务运行状态的权威投影</p></div><span class="badge warn">Adapter 未配置</span></div><div class="empty-state devops-empty"><div class="empty-inner"><div class="empty-icon">▷</div><h2>尚未连接 DevOps</h2><p>实现并配置 DevOpsAdapter 后，可在此读取流水线、运行、制品和服务，并通过人工审批触发 CI/CD 或启停服务。UI 不会伪造执行结果。</p></div></div></div>`; return; }
  const toolbar = `<div class="section-toolbar devops-toolbar"><div><h1>DevOps</h1><p class="muted">数据直接来自已配置 Adapter；写操作要求显式审批</p></div><div class="header-meta"><span class="badge good">● Adapter 已连接</span><button class="button secondary" data-action="refresh-devops">↻ 刷新</button><button class="button primary" data-action="trigger-pipeline" ${overview?.pipelines.length ? "" : "disabled"}>▷ 触发流水线</button></div></div><div class="devops-filter"><label>关联变更<select data-devops-filter="changeId">${changes.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join("")}</select></label><span>${overview ? `同步于 ${formatTime(overview.syncedAt)}` : "尚未同步"}</span></div>`;
  if (app.devopsLoading) { $("#content").innerHTML = `<div class="devops-page">${toolbar}<div class="skeleton loading"></div></div>`; setDevOpsFilter(); return; }
  if (app.devopsError) { $("#content").innerHTML = `<div class="devops-page">${toolbar}<div class="gate-banner"><strong>DevOps 数据读取失败</strong><p>${esc(app.devopsError)}</p></div></div>`; setDevOpsFilter(); return; }
  if (!overview) { $("#content").innerHTML = `<div class="devops-page">${toolbar}<div class="empty-list">正在准备 DevOps 数据…</div></div>`; setDevOpsFilter(); return; }
  $("#content").innerHTML = `<div class="devops-page">${toolbar}<div class="devops-kpis"><div><span>流水线</span><strong>${overview.pipelines.length}</strong></div><div><span>最近运行</span><strong>${overview.runs.length}</strong></div><div><span>制品</span><strong>${overview.artifacts.length}</strong></div><div><span>服务</span><strong>${overview.services.length}</strong></div></div><div class="devops-grid"><section class="panel"><div class="panel-header"><h2>流水线状态</h2></div><div class="panel-body devops-list">${overview.pipelines.length ? overview.pipelines.map(pipelineRow).join("") : emptyDevOps("暂无流水线")}</div></section><section class="panel"><div class="panel-header"><h2>最近运行</h2></div><div class="panel-body devops-list">${overview.runs.length ? overview.runs.map(runProjectionRow).join("") : emptyDevOps("暂无运行")}</div></section><section class="panel"><div class="panel-header"><h2>制品信息</h2></div><div class="panel-body devops-list">${overview.artifacts.length ? overview.artifacts.map(artifactRow).join("") : emptyDevOps("暂无制品")}</div></section><section class="panel"><div class="panel-header"><h2>服务状态</h2></div><div class="panel-body devops-list">${overview.services.length ? overview.services.map(serviceRow).join("") : emptyDevOps("暂无服务")}</div></section></div></div>`; setDevOpsFilter();
}
function emptyDevOps(message:string):string{return `<div class="empty-list">${esc(message)}</div>`} function itemId(item:DevOpsItem):string{return String(item.id??item.pipelineId??item.runId??item.artifactId??"—")} function itemName(item:DevOpsItem):string{return String(item.name??item.pipelineName??itemId(item))} function statusBadge(status:unknown):string{const value=String(status??"unknown");const normalized=value.toLowerCase();const tone=["succeeded","success","healthy","ready","running","online","built"].includes(normalized)?"good":["failed","error","stopped","offline"].includes(normalized)?"bad":"warn";return `<span class="badge ${tone}">${esc(value)}</span>`}
function pipelineRow(item:DevOpsItem):string{return `<div class="devops-row"><span class="item-icon">${item.kind==="cd"?"↗":"▷"}</span><div><div class="item-title">${esc(itemName(item))}</div><div class="item-sub">${esc(itemId(item))} · ${esc(String(item.kind??"pipeline").toUpperCase())}${item.changeId?` · ${esc(item.changeId)}`:""}</div></div>${statusBadge(item.status)}<button class="button ghost" data-pipeline-id="${esc(itemId(item))}" data-pipeline-kind="${item.kind==="cd"?"cd":"ci"}">触发</button></div>`}
function runProjectionRow(item:DevOpsItem):string{const runId=String(item.runId??itemId(item));return `<div class="devops-row"><span class="item-icon">↯</span><div><div class="item-title">${esc(itemName(item))}</div><div class="item-sub">${esc(runId)}${item.environment?` · ${esc(item.environment)}`:""}</div></div>${statusBadge(item.status)}<time class="item-time">${formatTime(String(item.completedAt??item.startedAt??""))}</time></div>`}
function artifactRow(item:DevOpsItem):string{return `<div class="devops-row"><span class="item-icon">⬡</span><div><div class="item-title">${esc(itemName(item))} <span class="artifact-version">${esc(item.version??"—")}</span></div><div class="item-sub">${esc(itemId(item))}${item.changeId?` · ${esc(item.changeId)}`:""}</div></div>${statusBadge(item.status)}<time class="item-time">${formatTime(String(item.createdAt??""))}</time></div>`}
function serviceRow(item:DevOpsItem):string{return `<div class="devops-row service-row"><span class="service-dot ${String(item.status).toLowerCase()==="running"?"running":""}"></span><div><div class="item-title">${esc(itemName(item))}</div><div class="item-sub">${esc(itemId(item))} · ${esc(item.environment??"—")} · ${esc(item.version??"—")}</div></div>${statusBadge(item.status)}<div class="service-actions"><button class="button ghost" data-service-id="${esc(itemId(item))}" data-service-action="start">启动</button><button class="button ghost" data-service-id="${esc(itemId(item))}" data-service-action="restart">重启</button><button class="button ghost danger" data-service-id="${esc(itemId(item))}" data-service-action="stop">停止</button></div></div>`}
function setDevOpsFilter():void{const select=document.querySelector<HTMLSelectElement>('[data-devops-filter="changeId"]');if(select)select.value=app.devopsChangeId}
async function loadDevOps():Promise<void>{if(!app.snapshot.integrations.devopsConfigured)return;app.devopsLoading=true;app.devopsError="";if(app.view==="devops")renderDevOps();try{app.devops=await request<DevOpsOverview>(`/api/devops/overview${app.devopsChangeId?`?changeId=${encodeURIComponent(app.devopsChangeId)}`:""}`)}catch(error){app.devops=null;app.devopsError=errorMessage(error)}finally{app.devopsLoading=false;if(app.view==="devops")render()}}
function renderSkills() {
  const skills = app.snapshot.skills || []; $("#content").innerHTML = `<div class="skill-page"><div class="section-toolbar"><div><h1>Skill Library</h1><p class="muted">安装、治理并按最小权限运行企业能力</p></div><button class="button primary" data-action="install-skill">＋ 安装 Skill</button></div>${skills.length ? `<div class="skill-grid">${skills.map(({ manifest, digest }) => `<article class="skill-card"><div class="skill-card-top"><span class="skill-glyph">◇</span><div><h3>${esc(manifest.name)}</h3><div class="skill-id">${esc(manifest.id)} @ ${esc(manifest.version)}</div></div><span class="badge skill-risk ${Number(manifest.riskLevel.slice(1)) >= 4 ? "warn" : ""}">${esc(manifest.riskLevel)}</span></div><p class="skill-description">${esc(manifest.description)}</p><div class="skill-footer"><span class="badge">${esc(manifest.source)}</span><button class="button secondary" data-run-skill="${esc(manifest.id)}">运行</button></div></article>`).join("")}</div>` : `<div class="empty-state"><div class="empty-inner"><div class="empty-icon">◇</div><h2>尚未安装 Skill</h2><p>从企业自研包或经治理的外部包安装 Skill。版本和摘要将被锁定。</p><button class="button primary" data-action="install-skill">安装第一个 Skill</button></div></div>`}</div>`;
}
function renderRuns() {
  const runs = app.snapshot.runs || []; $("#content").innerHTML = `<div class="runs-page"><div class="section-toolbar"><div><h1>运行记录</h1><p class="muted">Skill 与 Workflow 的不可变执行轨迹</p></div><button class="button primary" data-action="run-workflow">↯ 运行 Workflow</button></div>${runs.length ? `<div class="runs-table">${runs.map((run) => `<div class="run-row clickable" data-run-id="${esc(run.id)}"><span class="item-icon">${run.skillId ? "◇" : "↯"}</span><div><div class="item-title">${esc(run.skillId || run.workflowId || "workflow")}</div><div class="item-sub">${esc(run.id)}</div></div><span class="change-key">${esc(run.changeId || "—")}</span><span class="${run.status === "succeeded" ? "status-success" : "status-failed"}">${esc(run.status)}</span><time class="item-time">${formatTime(run.completedAt)}</time></div>`).join("")}</div>` : `<div class="empty-state"><div class="empty-inner"><div class="empty-icon">↯</div><h2>尚无运行记录</h2><p>运行一个 Skill 或 Workflow 后，结果、证据与审计输出将在此显示。</p><button class="button primary" data-action="run-workflow">运行 Workflow</button></div></div>`}</div>`;
}

function modal({ title, description = "", fields, submit = "确认", wide = false, onSubmit }: ModalOptions): void {
  $("#modal-root").innerHTML = `<div class="modal-backdrop"><form class="modal ${wide ? "wide" : ""}"><div class="modal-header"><div><h2>${esc(title)}</h2><p>${esc(description)}</p></div><button type="button" class="icon-button" data-close aria-label="关闭">×</button></div><div class="modal-body"><div class="error-inline"></div><div class="form-grid">${fields}</div></div><div class="modal-footer"><button type="button" class="button ghost" data-close>取消</button><button type="submit" class="button primary">${esc(submit)}</button></div></form></div>`;
  const form = $<HTMLFormElement>("#modal-root form"); const close = () => { $("#modal-root").innerHTML = ""; }; $$('[data-close]', form).forEach((button) => button.addEventListener("click", close)); $(".modal-backdrop").addEventListener("mousedown", (event) => { if (event.target === event.currentTarget) close(); });
  form.addEventListener("submit", async (event) => { event.preventDefault(); const button = $<HTMLButtonElement>('button[type="submit"]', form); const errorBox = $(".error-inline", form); button.disabled = true; errorBox.classList.remove("visible"); try { await onSubmit(new FormData(form)); close(); await refresh({ quiet:true }); } catch (error) { errorBox.textContent = errorMessage(error); errorBox.classList.add("visible"); } finally { button.disabled = false; } }); setTimeout(() => $<HTMLElement>("input,textarea,select", form).focus(), 0);
}
const field = (label: string, name: string, options: FieldOptions = {}): string => `<div class="field ${options.full ? "full" : ""}"><label for="f-${esc(name)}">${esc(label)}</label>${options.type === "textarea" ? `<textarea id="f-${esc(name)}" name="${esc(name)}" class="${options.code ? "code" : ""}" ${options.required ? "required" : ""} placeholder="${esc(options.placeholder || "")}">${esc(options.value || "")}</textarea>` : options.type === "select" ? `<select id="f-${esc(name)}" name="${esc(name)}">${(options.options ?? []).map(([value,text]) => `<option value="${esc(value)}">${esc(text)}</option>`).join("")}</select>` : `<input id="f-${esc(name)}" name="${esc(name)}" type="${esc(options.type || "text")}" value="${esc(options.value || "")}" placeholder="${esc(options.placeholder || "")}" ${options.required ? "required" : ""}>`}${options.help ? `<small>${esc(options.help)}</small>` : ""}</div>`;
function createChangeModal(): void {
  modal({ title: "创建研发变更", description: "Jira Key 将作为跨平台关联的 change_id。", fields: field("Change ID", "id", { required: true, placeholder: "PAY-128" }) + field("Owner", "owner", { required: true, placeholder: "product-owner" }) + field("标题", "title", { required: true, full: true, placeholder: "批量取消订单" }) + field("风险等级", "riskLevel", { type: "select", options: ["L1", "L0", "L2", "L3", "L4", "L5"].map((value): [string, string] => [value, value]) }) + field("说明", "description", { type: "textarea", full: true, placeholder: "目标、范围和成功指标" }), submit: "创建变更", onSubmit: async (data) => { const result = await request<{ id: string }>("/api/changes", { method: "POST", body: JSON.stringify(formValues(data)) }); app.selectedChange = result.id; app.view = "changes"; toast("研发变更已创建"); } });
}
function addEvidenceModal(): void {
  const change = requireChange(); const needed = [...new Set(change.nextTransitions.flatMap((item) => item.missingEvidence))];
  modal({ title: "添加交付证据", description: `证据将关联到 ${change.id}，事实内容仍保留在权威平台。`, fields: field("证据类型", "kind", { type: "select", options: (needed.length ? needed : Object.keys(evidenceLabels)).map((value): [string, string] => [value, evidenceLabels[value] ?? value]) }) + field("状态", "status", { type: "select", options: [["approved", "approved"], ["passed", "passed"], ["valid", "valid"], ["pending", "pending"]] }) + field("来源平台", "source", { required: true, value: "jira", placeholder: "jira / confluence / devops" }) + field("事实引用", "subjectRef", { required: true, placeholder: "jira://PAY-128" }) + field("可访问 URI", "uri", { full: true, placeholder: "https://…" }), submit: "添加证据", onSubmit: async (data) => { await request(`/api/changes/${encodeURIComponent(change.id)}/evidence`, { method: "POST", body: JSON.stringify(formValues(data)) }); toast("证据已添加"); } });
}
function transitionModal(target: LifecycleState): void {
  const change = requireChange(); modal({ title: `转换至${stateLabels[target]}`, description: "转换将写入不可变历史；关键前进阶段仍受证据门禁约束。", fields: field("执行人", "actor", { required: true, value: change.owner }) + field("转换原因", "reason", { required: true, full: true, placeholder: "说明阶段目标和门禁已满足" }), submit: "确认转换", onSubmit: async (data) => { await request(`/api/changes/${encodeURIComponent(change.id)}/transitions`, { method: "POST", body: JSON.stringify({ target, ...formValues(data) }) }); toast(`已转换至${stateLabels[target]}`); } });
}
function installSkillModal(): void {
  modal({ title: "安装 Skill", description: "安装包必须包含 skill.json；版本内容将按 SHA-256 锁定。", fields: field("Skill 包目录", "packagePath", { required: true, full: true, placeholder: "/absolute/path/to/my-skill", help: "服务器本机上的绝对或相对目录。生产环境应由企业 Registry 提供。" }), submit: "安装并锁定", onSubmit: async (data) => { await request("/api/skills/install", { method: "POST", body: JSON.stringify(formValues(data)) }); app.view = "skills"; toast("Skill 已安装并锁定"); } });
}
function runSkillModal(skillId?: string): void {
  const skills = app.snapshot.skills; if (!skills.length) { installSkillModal(); return; } const chosen = skillId ?? skills[0]!.id;
  const skillOptions = skills.map((item): [string, string] => [item.id, `${item.manifest.name} · ${item.id}`]); const changeOptions = app.snapshot.changes.map((item): [string, string] => [item.id, `${item.id} · ${item.title}`]);
  modal({ title: "运行 Skill", description: "输入将按 Skill 协议执行；平台操作仍经过 ToolBroker 权限检查。", wide: true, fields: field("Skill", "skillId", { type: "select", full: true, options: skillOptions }) + field("关联变更", "changeId", { type: "select", options: [["", "不关联"], ...changeOptions] }) + `<div class="field"><label class="checkbox"><input type="checkbox" name="approved" value="true"> 已获得本次写操作/高风险执行审批</label></div>` + field("JSON 输入", "input", { type: "textarea", code: true, full: true, required: true, value: '{\n  "requirement": "支持批量取消；保留审计日志"\n}' }), submit: "运行 Skill", onSubmit: async (data) => { const values = formValues(data); let input: unknown; try { input = JSON.parse(values.input ?? ""); } catch { throw new Error("JSON 输入格式无效"); } await request(`/api/skills/${encodeURIComponent(values.skillId ?? "")}/runs`, { method: "POST", body: JSON.stringify({ input, changeId: values.changeId || undefined, approved: values.approved === "true" }) }); app.view = "runs"; toast("Skill 运行完成"); } });
  setTimeout(() => { $<HTMLSelectElement>('[name="skillId"]').value = chosen; const change = selectedChange(); if (change) $<HTMLSelectElement>('[name="changeId"]').value = change.id; }, 0);
}
function runWorkflowModal(): void {
  const sample = { id: "requirement-to-tests", version: "1.0.0", name: "需求到测试", steps: [{ id: "decompose", skill: "requirement.decompose", input: { requirement: { $ref: "input.requirement" } } }, { id: "test-cases", skill: "test.case.generate", input: { feature: { $ref: "input.feature" }, acceptanceCriteria: { $ref: "input.acceptanceCriteria" }, tasks: { $ref: "steps.decompose.output.tasks" } } }] }; const changeOptions = app.snapshot.changes.map((item): [string, string] => [item.id, `${item.id} · ${item.title}`]);
  modal({ title: "运行 Workflow", description: "按声明式步骤编排已安装 Skills，并通过 $ref 传递上下文。", wide: true, fields: field("关联变更", "changeId", { type: "select", full: true, options: [["", "不关联"], ...changeOptions] }) + field("Workflow 定义", "definition", { type: "textarea", code: true, full: true, required: true, value: JSON.stringify(sample, null, 2) }) + field("Workflow 输入", "input", { type: "textarea", code: true, full: true, required: true, value: '{\n  "requirement": "支持批量取消订单",\n  "feature": "批量取消",\n  "acceptanceCriteria": ["返回每个订单的处理结果"]\n}' }), submit: "运行 Workflow", onSubmit: async (data) => { const values = formValues(data); let definition: unknown; let input: unknown; try { definition = JSON.parse(values.definition ?? ""); input = JSON.parse(values.input ?? ""); } catch { throw new Error("Workflow 定义或输入不是有效 JSON"); } await request("/api/workflows/runs", { method: "POST", body: JSON.stringify({ definition, input, changeId: values.changeId || undefined, approvedSteps: [] }) }); app.view = "runs"; toast("Workflow 运行完成"); } });
  setTimeout(() => { const change = selectedChange(); if (change) $<HTMLSelectElement>('[name="changeId"]').value = change.id; }, 0);
}
function triggerPipelineModal(pipelineId?:string,kind?:"ci"|"cd"):void{const pipelines=app.devops?.pipelines??[];if(!pipelines.length){toast("没有可触发的流水线",true);return;}const selected=pipelines.find((item)=>itemId(item)===pipelineId)??pipelines[0]!;modal({title:"触发 DevOps 流水线",description:"将向 DevOps 发起真实执行请求；操作必须获得人工审批。",fields:field("流水线","pipelineId",{type:"select",full:true,options:pipelines.map((item):[string,string]=>[itemId(item),`${itemName(item)} · ${String(item.kind??"pipeline").toUpperCase()}`])})+field("执行类型","kind",{type:"select",options:[["ci","CI · 构建验证"],["cd","CD · 部署发布"]]})+field("关联变更","changeId",{type:"select",options:[["","不关联"],...app.snapshot.changes.map((change):[string,string]=>[change.id,`${change.id} · ${change.title}`])]})+field("代码引用","ref",{placeholder:"main / tag / commit"})+field("目标环境","environment",{placeholder:"test / staging / production"})+field("操作人","actor",{required:true,value:selectedChange()?.owner??"release-owner"})+field("执行原因","reason",{required:true,full:true,placeholder:"说明本次 CI/CD 执行目的"})+`<div class="field full"><label class="checkbox"><input type="checkbox" name="approved" value="true"> 已获得本次流水线执行的人工审批</label><small>CI/CD 是外部写操作，未确认审批时后端会拒绝。</small></div>`,submit:"确认触发",onSubmit:async(data)=>{const values=formValues(data);await request("/api/devops/pipelines/trigger",{method:"POST",body:JSON.stringify({...values,approved:values.approved==="true"})});app.devops=null;await loadDevOps();toast(`${String(values.kind).toUpperCase()} 流水线已触发`);}});setTimeout(()=>{$<HTMLSelectElement>('[name="pipelineId"]').value=itemId(selected);$<HTMLSelectElement>('[name="kind"]').value=kind??(selected.kind==="cd"?"cd":"ci");const change=selectedChange();if(change)$<HTMLSelectElement>('[name="changeId"]').value=change.id},0)}
function serviceControlModal(serviceId:string,action:"start"|"stop"|"restart"):void{const service=app.devops?.services.find((item)=>itemId(item)===serviceId);if(!service)return;const actionLabels={start:"启动",stop:"停止",restart:"重启"};modal({title:`${actionLabels[action]}服务`,description:`${itemName(service)} · ${service.environment??"未指定环境"}。该操作将由 DevOps 执行。`,fields:field("服务 ID","serviceId",{required:true,full:true,value:serviceId})+field("目标环境","environment",{value:String(service.environment??"")})+field("操作人","actor",{required:true,value:selectedChange()?.owner??"operator"})+field("操作原因","reason",{required:true,full:true,placeholder:`说明${actionLabels[action]}服务的原因`})+`<div class="field full"><label class="checkbox"><input type="checkbox" name="approved" value="true"> 已获得本次服务${actionLabels[action]}操作的人工审批</label><small>未确认审批时后端会拒绝执行。</small></div>`,submit:`确认${actionLabels[action]}`,onSubmit:async(data)=>{const values=formValues(data);await request("/api/devops/services/control",{method:"POST",body:JSON.stringify({...values,action,approved:values.approved==="true"})});app.devops=null;await loadDevOps();toast(`服务${actionLabels[action]}请求已提交`);}})}
function showRun(id: string): void { const run = app.snapshot.runs.find((item) => item.id === id); if (!run) return; const canImport = run.status === "succeeded" && run.changeId && Array.isArray(run.output?.tasks) && !app.snapshot.tasks.some((task) => task.sourceRunId === run.id); modal({ title: run.skillId ?? run.workflowId ?? "运行详情", description: `${run.id} · ${run.status}`, wide: true, fields: `${canImport ? `<div class="field full"><button type="button" class="button secondary" data-import-run="${esc(run.id)}">↓ 将拆解任务添加到看板</button></div>` : ""}<div class="field full"><label>执行记录</label><pre class="detail-pre">${formatJson(run)}</pre></div>`, submit: "关闭", onSubmit: async () => {} }); const button = document.querySelector<HTMLElement>("[data-import-run]"); button?.addEventListener("click", () => importRunTasks(run.id, run.changeId!)); }
function newTaskModal(): void {
  if (!app.snapshot.changes.length) { toast("请先创建研发变更", true); createChangeModal(); return; } const changeOptions = app.snapshot.changes.map((change): [string,string] => [change.id, `${change.id} · ${change.title}`]);
  modal({ title:"新建本地任务", description:"任务将作为本地草稿保存；发布到 Jira 后状态权威转移至 Jira。", fields:field("关联变更","changeId",{type:"select",options:changeOptions})+field("Owner","owner",{required:true,value:selectedChange()?.owner??"unassigned"})+field("任务标题","title",{required:true,full:true,placeholder:"实现批量取消接口"})+field("优先级","priority",{type:"select",options:["P0","P1","P2","P3","P4"].map((value):[string,string]=>[value,value])})+field("风险等级","riskLevel",{type:"select",options:["L1","L0","L2","L3","L4","L5"].map((value):[string,string]=>[value,value])})+field("任务说明","description",{type:"textarea",full:true})+field("验收标准","acceptanceCriteria",{type:"textarea",full:true,placeholder:"每行一条验收标准"})+field("依赖任务 ID","dependencies",{full:true,placeholder:"TASK-01, TASK-02"})+field("证据引用","evidenceRefs",{full:true,placeholder:"artifact://report-1, jira://PAY-1"}), submit:"创建任务", onSubmit:async(data)=>{const values=formValues(data);await request("/api/tasks",{method:"POST",body:JSON.stringify({...values,acceptanceCriteria:lines(values.acceptanceCriteria),dependencies:csv(values.dependencies),evidenceRefs:csv(values.evidenceRefs)})});app.view="board";toast("本地任务已创建");} });
  setTimeout(()=>{const change=selectedChange();if(change)$<HTMLSelectElement>('[name="changeId"]').value=change.id},0);
}
function importTasksModal(): void { const candidates=app.snapshot.runs.filter((run)=>run.status==="succeeded"&&run.changeId&&Array.isArray(run.output?.tasks)&&!app.snapshot.tasks.some((task)=>task.sourceRunId===run.id));if(!candidates.length){toast("没有待导入的需求拆解运行",true);return;}modal({title:"导入需求拆解任务",description:"导入操作幂等；每个运行只会生成一组本地草稿。",fields:field("Skill Run","runId",{type:"select",full:true,options:candidates.map((run):[string,string]=>[run.id,`${run.changeId} · ${run.id}`])}),submit:"添加到看板",onSubmit:async(data)=>{const runId=formValues(data).runId??"";const run=candidates.find((item)=>item.id===runId);if(!run?.changeId)throw new Error("运行未关联研发变更");await request(`/api/runs/${encodeURIComponent(run.id)}/tasks/import`,{method:"POST",body:JSON.stringify({changeId:run.changeId})});app.view="board";toast("拆解任务已添加到看板");}}); }
async function importRunTasks(runId:string,changeId:string):Promise<void>{try{await request(`/api/runs/${encodeURIComponent(runId)}/tasks/import`,{method:"POST",body:JSON.stringify({changeId})});$("#modal-root").innerHTML="";app.view="board";await refresh({quiet:true});toast("拆解任务已添加到看板");}catch(error){toast(errorMessage(error),true)}}
function taskDetailModal(taskId:string):void{const task=app.snapshot.tasks.find((item)=>item.id===taskId);if(!task)return;const transitions=taskColumns.filter((column)=>taskTransitions[task.status].includes(column.status));const criteria=task.acceptanceCriteria.length?`<ul>${task.acceptanceCriteria.map((item)=>`<li>${esc(item)}</li>`).join("")}</ul>`:"未填写";const deps=task.dependencies.length?task.dependencies.map(esc).join("、"):"无";const source=task.sourceRunId?`<button type="button" class="button ghost" data-open-run="${esc(task.sourceRunId)}">${esc(task.sourceRunId)}</button>`:"手工创建";const publish=task.authority==="local-draft"?`<button type="button" class="button secondary" data-task-publish ${app.snapshot.integrations.jiraConfigured?"":"disabled"}>发布到 Jira</button>`:`<button type="button" class="button secondary" data-task-sync>同步 Jira 状态</button>`;modal({title:task.title,description:`${task.changeId} · ${taskStatusLabels[task.status]} · ${task.authority==="jira"?task.jiraIssueKey:"本地草稿"}`,wide:true,fields:`<div class="task-detail-grid field full"><section><label>验收标准</label><div class="task-detail-copy">${criteria}</div></section><section><label>依赖</label><div class="task-detail-copy">${deps}</div></section><section><label>证据引用</label><div class="task-detail-copy">${task.evidenceRefs.length?task.evidenceRefs.map(esc).join("、"):"暂无"}</div></section><section><label>来源运行</label><div>${source}</div></section></div><div class="field"><label>目标状态</label><select name="targetStatus">${transitions.map((item)=>`<option value="${item.status}">${item.label}</option>`).join("")}</select></div>${field("执行人","taskActor",{required:true,value:task.owner})}${field("转换原因","taskReason",{required:true,full:true,value:"任务状态已更新"})}<div class="field full"><label class="checkbox"><input type="checkbox" name="taskApproved" value="true"> 已批准 Jira 发布或状态写回</label><small>${app.snapshot.integrations.jiraConfigured?"Jira 写操作必须显式审批。":"当前未配置 Jira Adapter；可继续使用本地草稿状态。"}</small></div><div class="field full task-detail-actions"><button type="button" class="button primary" data-task-transition>更新状态</button>${publish}</div>`,submit:"关闭",onSubmit:async()=>{}});const root=$("#modal-root");root.addEventListener("click",(event)=>{const target=event.target instanceof Element?event.target.closest<HTMLElement>("button"):null;if(!target)return;if(target.dataset.openRun){$("#modal-root").innerHTML="";showRun(target.dataset.openRun)}else if(target.hasAttribute("data-task-transition")){void mutateTask(task,"transition")}else if(target.hasAttribute("data-task-publish")){void mutateTask(task,"publish")}else if(target.hasAttribute("data-task-sync")){void mutateTask(task,"sync")}});}
async function mutateTask(task:Task,action:"transition"|"publish"|"sync"):Promise<void>{try{if(action==="transition"){const target=$<HTMLSelectElement>('[name="targetStatus"]').value as TaskStatus;await request(`/api/tasks/${encodeURIComponent(task.id)}/transitions`,{method:"POST",body:JSON.stringify({target,actor:$<HTMLInputElement>('[name="taskActor"]').value,reason:$<HTMLInputElement>('[name="taskReason"]').value,approved:$<HTMLInputElement>('[name="taskApproved"]').checked})})}else if(action==="publish"){const approved=$<HTMLInputElement>('[name="taskApproved"]').checked;await request(`/api/tasks/${encodeURIComponent(task.id)}/jira/publish`,{method:"POST",body:JSON.stringify({approved})})}else await request(`/api/tasks/${encodeURIComponent(task.id)}/jira/sync`,{method:"POST",body:"{}"});$("#modal-root").innerHTML="";await refresh({quiet:true});toast(action==="sync"?"Jira 状态已同步":"任务已更新")}catch(error){const box=$(".error-inline");box.textContent=errorMessage(error);box.classList.add("visible")}}
function lines(value:string|undefined):string[]{return(value??"").split("\n").map((item)=>item.trim()).filter(Boolean)}function csv(value:string|undefined):string[]{return(value??"").split(",").map((item)=>item.trim()).filter(Boolean)}

$<HTMLInputElement>("#change-search").addEventListener("input", renderChangeList); $("#new-change").addEventListener("click", createChangeModal); $("#theme-toggle").addEventListener("click", () => { document.documentElement.classList.toggle("dark"); localStorage.setItem("cjhx:theme", document.documentElement.classList.contains("dark") ? "dark" : "light"); });
if (localStorage.getItem("cjhx:theme") === "dark" || (!localStorage.getItem("cjhx:theme") && matchMedia("(prefers-color-scheme: dark)").matches)) document.documentElement.classList.add("dark");
$$<HTMLElement>(".nav-item").forEach((item) => item.addEventListener("click", () => { const view = item.dataset.view; if (view === "changes" || view === "board" || view === "devops" || view === "skills" || view === "runs") { app.view = view; render(); if(view==="devops"&&!app.devops&&!app.devopsLoading)void loadDevOps(); } })); $("#primary-action").addEventListener("click", () => app.view === "changes" ? createChangeModal() : app.view === "board" ? newTaskModal() : app.view === "devops" ? triggerPipelineModal() : app.view === "skills" ? installSkillModal() : runWorkflowModal()); $("#install-skill").addEventListener("click", installSkillModal);
$("#change-list").addEventListener("click", (event) => { const row = event.target instanceof Element ? rowWithData(event.target, "[data-change-id]") : null; const id = row?.dataset.changeId; if (id) { app.selectedChange = id; app.view = "changes"; localStorage.setItem("cjhx:selected-change", id); render(); } });
$("#content").addEventListener("change", (event) => { const select = event.target instanceof HTMLSelectElement ? event.target : null; const filter = select?.dataset.boardFilter; if (select && (filter === "changeId" || filter === "owner" || filter === "risk" || filter === "status")) { app.boardFilters[filter] = select.value; renderBoard(); } else if(select?.dataset.devopsFilter==="changeId"){app.devopsChangeId=select.value;app.devops=null;void loadDevOps()} });
$("#content").addEventListener("click", (event) => { const target = event.target instanceof Element ? rowWithData(event.target, "button,[data-run-id],[data-task-id]") : null; if (!target) return; const tab = target.dataset.tab; if (tab === "evidence" || tab === "tasks" || tab === "history" || tab === "runs") { app.evidenceTab = tab; renderChange(); } else if (target.dataset.taskId) taskDetailModal(target.dataset.taskId); else if (target.dataset.transition && lifecycle.includes(target.dataset.transition as LifecycleState)) transitionModal(target.dataset.transition as LifecycleState); else if (target.dataset.runSkill) runSkillModal(target.dataset.runSkill); else if (target.dataset.runId) showRun(target.dataset.runId); else if(target.dataset.pipelineId)triggerPipelineModal(target.dataset.pipelineId,target.dataset.pipelineKind==="cd"?"cd":"ci");else if(target.dataset.serviceId&&(target.dataset.serviceAction==="start"||target.dataset.serviceAction==="stop"||target.dataset.serviceAction==="restart"))serviceControlModal(target.dataset.serviceId,target.dataset.serviceAction);else { const actions: Record<string, () => void> = { "new-change": createChangeModal, "new-task": newTaskModal, "import-tasks": importTasksModal, "add-evidence": addEvidenceModal, "install-skill": installSkillModal, "run-skill": () => runSkillModal(), "run-workflow": runWorkflowModal, "refresh-devops":()=>{void loadDevOps()}, "trigger-pipeline":()=>triggerPipelineModal() }; const action = target.dataset.action; if (action) actions[action]?.(); } });
$("#content").addEventListener("keydown", (event) => { if (event.key !== "Enter" && event.key !== " ") return; const target = event.target instanceof Element ? rowWithData(event.target, "[data-task-id]") : null; if (target?.dataset.taskId) { event.preventDefault(); taskDetailModal(target.dataset.taskId); } });
function rowWithData(target: Element, selector: string): HTMLElement | null { const row = target.closest(selector); return row instanceof HTMLElement ? row : null; }
document.addEventListener("keydown", (event) => { const mod = navigator.userAgent.includes("Mac") ? event.metaKey : event.ctrlKey; if (mod && event.key.toLowerCase() === "k") { event.preventDefault(); $<HTMLInputElement>("#change-search").focus(); } if (event.key === "Escape" && $("#modal-root").children.length) $("#modal-root").innerHTML = ""; }); $("#search-key").textContent = navigator.userAgent.includes("Mac") ? "⌘K" : "Ctrl+K";
void refresh(); setInterval(() => void (async()=>{await refresh({quiet:true});if(app.view==="devops"&&app.snapshot.integrations.devopsConfigured&&!app.devopsLoading)await loadDevOps()})(), 15000);
